alibaba/GraphScope

README.md
docs/reference/context.rst
python/graphscope/analytical/udf/patch.py
python/graphscope/client/session.py
python/graphscope/experimental/nx/classes/graph.py
python/graphscope/experimental/nx/utils/other.py
python/graphscope/framework/app.py
python/graphscope/framework/context.py
python/graphscope/framework/graph.py
python/graphscope/framework/operation.py
python/graphscope/interactive/query.py
python/graphscope/learning/graph.py

- Add more comments;
- Refine naming;

Refine some python files.

---

python/graphscope/deploy/kubernetes/cluster.py

Fix minikube service failed on python3.8+ by using threading replace multiprocessing.

Fix minikube service failed on python3.8+

---

scripts/prepare_env.sh
scripts/prepare_env_wsl.sh

- check docker is running in prepare_env.sh
Fixes #12

check docker is running or not in prepare_env.sh

---

coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/coordinator.py
python/graphscope/client/rpc.py
python/graphscope/client/session.py
python/graphscope/config.py
python/graphscope/deploy/kubernetes/cluster.py
python/graphscope/deploy/kubernetes/resource_builder.py
python/graphscope/deploy/kubernetes/utils.py

Make GraphScope support LoadBalancer service type.
Resolves #8 
This PR is incomplete at present,  where GIE gremlin server also needs to support it (Is going on).

Add load balance service type

---

.github/workflows/ci.yml

Fix release image step

---

coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/template/CMakeLists.template
interactive_engine/deploy/docker/dockerfile/create_maxgraph_instance.sh
interactive_engine/src/instance-manager/src/main/java/com/alibaba/maxgraph/admin/controller/InstanceManagerController.java
k8s/graphscope.Dockerfile
python/graphscope/deploy/kubernetes/cluster.py

- Check GIE gremlin service external ip is null by for loop.
- fix the stream log failed problem when the GIE manager image is not exist.

[BUGFIX] Expose the correct external IP of GIE.

---

python/graphscope/learning/graph.py

update graphlearn submodule to fix bug that session close get stuck in gl client.close
related graphlearn pr: https://github.com/alibaba/graph-learn/pull/137
@sighingnow

update graphlearn submodule

---

analytical_engine/apps/kshell/kshell.h
analytical_engine/apps/kshell/kshell_context.h
analytical_engine/test/run_app.cc
analytical_engine/test/run_app.h
coordinator/gscoordinator/builtin/app/.gs_conf.yaml
python/graphscope/analytical/app/__init__.py
python/graphscope/analytical/app/k_shell.py
python/tests/conftest.py
python/tests/test_app.py

Add kshell application to GraphScope analytical_engine.
Resolves #70.

add app kshell

---

.github/workflows/ci.yml
analytical_engine/CMakeLists.txt
analytical_engine/core/object/fragment_wrapper.h
analytical_engine/frame/project_frame.cc
interactive_engine/src/executor/runtime/native/CMakeLists.txt
interactive_engine/src/executor/runtime/native/graph_builder_ffi.cc
interactive_engine/src/executor/runtime/native/graph_schema.cc
interactive_engine/src/executor/runtime/native/graph_schema.h
interactive_engine/src/executor/runtime/native/htap_ds_impl.cc
interactive_engine/src/executor/runtime/native/property_graph_stream.cc
interactive_engine/src/executor/runtime/native/property_graph_stream.h
k8s/graphscope.Dockerfile
python/graphscope/client/session.py
python/graphscope/experimental/nx/tests/test_nx.py
python/requirements.txt

Note that this pull request also modifies the CI YAML configurations.
Fixes #75 along with this pull request.

Upgrade vineyard to v0.1.5.

---

README-zh.md
README.md
analytical_engine/README-zh.md
analytical_engine/README.md
interactive_engine/README-zh.md
interactive_engine/README.md
interactive_engine/benchmark/README-zh.md
interactive_engine/benchmark/README.md
learning_engine/README-zh.md
learning_engine/README.md

Update badges for docs.

---

.github/workflows/ci.yml
analytical_engine/CMakeLists.txt
analytical_engine/core/loader/arrow_fragment_loader.h
coordinator/gscoordinator/template/CMakeLists.template
docs/loading_graph.rst
docs/zh/loading_graph.rst
interactive_engine/src/executor/runtime/native/CMakeLists.txt
k8s/graphscope.Dockerfile
k8s/gsruntime.Dockerfile
python/graphscope/client/session.py
python/graphscope/framework/graph_utils.py
python/graphscope/framework/loader.py
python/requirements.txt

Add I/O support for aws s3.

---

python/graphscope/client/session.py
python/graphscope/deploy/kubernetes/cluster.py
python/graphscope/deploy/kubernetes/utils.py

Try to read namespace from kube config when missing k8s_namesapce param

---

python/graphscope/client/rpc.py
python/graphscope/client/session.py

Change session status to disconnected when gRPC failed to coordinator

---

k8s/gsruntime.Dockerfile
k8s/gsvineyard.Dockerfile

Boost 1.72.0 has [known compatibility issue](https://github.com/boostorg/process/issues/116) between boost::asio and boost::process, and has been fixed since 1.73.
N/A

Upgrade boost to v1.73.0.

---

python/graphscope/__init__.py

Add module level doc string for graphscope.
Fixes #104

Add module string.

---

analytical_engine/core/grape_instance.cc
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/object_manager.py

Fixes the` Graph.unload()` when closing session.
Fixes #144

Unload graph when session close

---

python/jupyter/ipygraphin/README.md
python/jupyter/ipygraphin/package.json

Fix: Update graphin jupyterlab extension's package version &&  readme file

---

research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/compiler/demo/server/MaxGraphOpProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/compiler/demo/server/result/GremlinResultProcessor.java

Fix for the new compiler of GIE, which combines the results returned by multiple streams.
Fixes

fix issue of union result parser

---

docs/deployment.rst
docs/zh/deployment.rst
scripts/launch_cluster.py

fix the requirements check in launch_cluster script and try to create directory before output config file.

fix the requirements check in launch_cluster script

---

python/graphscope/framework/graph.py

Fix bug about can not join current thread during graph unloading

---

charts/graphscope/README.md
coordinator/gscoordinator/coordinator.py
proto/message.proto
python/graphscope/client/rpc.py
python/graphscope/client/session.py

Some fixes for running with helm deployed

---

.github/workflows/docs.yml
docs/Makefile
docs/_templates/layout.html
docs/conf.py
docs/loading_graph.rst
docs/reference/selector.rst
docs/sphinx_ext.py
docs/zh/getting_started.rst
docs/zh/loading_graph.rst
python/graphscope/framework/context.py
python/graphscope/framework/graph.py
python/graphscope/framework/loader.py

Enable hosting multiple-version of docs on Github pages, generated using the CI action.
Preview:
Resolves #151.

Multi-version docs.

---

docs/Makefile

That is a bug introduced in #201.

Docs requires doxygen.

---

python/graphscope/deploy/tests/test_with_mars.py

[fix bug] test_with_mars not use data_dir

---

coordinator/gscoordinator/coordinator.py
python/graphscope/framework/graph.py
python/graphscope/framework/graph_schema.py
python/tests/test_graph.py

Fix several bugs:
1. Dump schema when project.
2. Check existence before `get_edge_relationship`.
3. Load immediately after `add_column`.
related issue: #206 
related pr: #215

Fix bugs of project/add column listed by #215

---

interactive_engine/src/executor/runtime/src/bin/executor.rs
python/graphscope/framework/graph.py
python/graphscope/framework/graph_schema.py
python/tests/test_create_graph.py
python/tests/test_graph.py

This PR introduce a few enhancement to graphs.
* Support initializes an empty graph.
* Support loads a graph without edges (only have vertices).
Related to #191

Support graphs that only have vertices or empty.

---

.github/workflows/local.yml
Makefile
charts/graphscope/templates/coordinator.yaml
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/launcher.py
interactive_engine/deploy/docker/dockerfile/create_maxgraph_instance.sh
interactive_engine/src/executor/runtime/src/bin/executor.rs
interactive_engine/src/executor/runtime/src/rpc/rpc_pegasus/async_maxgraph_service.rs
interactive_engine/src/executor/runtime/src/server/manager.rs
interactive_engine/src/instance-manager/bin/start.sh
interactive_engine/src/instance-manager/bin/stop.sh
interactive_engine/src/instance-manager/config/coordinator.local.application.properties.tpl
interactive_engine/src/instance-manager/config/executor.local.vineyard.properties.tpl
interactive_engine/src/instance-manager/config/frontend.local.vineyard.properties.tpl
interactive_engine/src/instance-manager/script/create_local_instance.sh
interactive_engine/src/instance-manager/script/start_local_coordinator.sh
interactive_engine/src/instance-manager/script/start_local_executor.sh
interactive_engine/src/instance-manager/script/start_local_frontend.sh
interactive_engine/src/instance-manager/src/main/java/com/alibaba/maxgraph/admin/controller/InstanceManagerController.java
interactive_engine/tests/function_test.sh
python/graphscope/client/session.py
python/graphscope/config.py
python/graphscope/deploy/hosts/cluster.py
python/graphscope/deploy/kubernetes/resource_builder.py
python/graphscope/deploy/tests/test_demo_script.py
python/graphscope/deploy/tests/test_with_mars.py
python/tests/test_run_locally.py

Support launch multiple session/instance in standalone mode

---

research/gaia/gremlin/gremlin_core/src/common/serde_dyn.rs
research/gaia/gremlin/gremlin_core/src/lib.rs

[GAIA] dead lock bug fix of GAIA

---

analytical_engine/core/fragment/dynamic_fragment.h
analytical_engine/core/fragment/dynamic_fragment_view.h
analytical_engine/core/fragment/dynamic_projected_fragment.h
analytical_engine/core/grape_instance.cc
analytical_engine/core/grape_instance.h
analytical_engine/core/object/fragment_wrapper.h
analytical_engine/core/object/i_fragment_wrapper.h
proto/types.proto
python/graphscope/experimental/nx/classes/digraph.py
python/graphscope/experimental/nx/classes/graph.py
python/graphscope/experimental/nx/tests/algorithms/builtin/test_ctx_builtin.py
python/graphscope/experimental/nx/tests/algorithms/builtin/test_shortest_paths.py
python/graphscope/experimental/nx/tests/classes/test_digraph.py
python/graphscope/experimental/nx/tests/classes/test_graphviews.py
python/graphscope/experimental/nx/tests/utils.py
python/graphscope/framework/dag_utils.py

implement graph views in engine side, including
- reverse view
- directed view
- undirected view
#62

[networkx] implement graph views in engine side

---

scripts/build.sh

Enhancement of build.sh

---

.github/workflows/ci.yml
.github/workflows/local.yml
analytical_engine/CMakeLists.txt
analytical_engine/core/grape_instance.cc
analytical_engine/core/launcher.cc
analytical_engine/core/loader/arrow_fragment_appender.h
coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/template/CMakeLists.template
interactive_engine/deploy/docker/dockerfile/coordinator.application.properties
interactive_engine/pom.xml
interactive_engine/src/coordinator/pom.xml
interactive_engine/src/executor/runtime/native/CMakeLists.txt
interactive_engine/src/instance-manager/src/main/java/com/alibaba/maxgraph/admin/controller/InstanceManagerController.java
k8s/gsvineyard.Dockerfile
python/graphscope/client/session.py
python/graphscope/deploy/kubernetes/cluster.py
python/graphscope/deploy/kubernetes/resource_builder.py
python/graphscope/deploy/kubernetes/utils.py
python/requirements.txt
scripts/build.sh

Bump up the dependent vineyard version to v0.2.1 as well.
Also Partial fixes #265

Generalize the Kubernetes deployment interface to make it extensible

---

docs/reference/networkx/builtin.rst
docs/reference/networkx/convert.rst
docs/reference/networkx/functions.rst
docs/reference/networkx/generators.rst
docs/reference/networkx/graphs.rst
docs/reference/networkx/index.rst
docs/reference/networkx/io.rst
docs/reference/networkx/relabel.rst
docs/sphinx_ext.py
docs/tutorials.rst
k8s/graphscope.Dockerfile
python/graphscope/experimental/nx/algorithms/builtin.py
python/graphscope/experimental/nx/classes/__init__.py
python/graphscope/experimental/nx/classes/dicts.py
python/graphscope/experimental/nx/classes/digraph.py
python/graphscope/experimental/nx/classes/function.py
python/graphscope/experimental/nx/classes/graph.py
python/graphscope/experimental/nx/generators/classic.py
python/graphscope/experimental/nx/readwrite/adjlist.py
python/graphscope/experimental/nx/readwrite/edgelist.py
python/graphscope/experimental/nx/tests/algorithms/builtin/test_bfs.py
python/graphscope/experimental/nx/tests/classes/test_function.py
python/graphscope/experimental/nx/tests/classes/test_graph.py
python/graphscope/experimental/nx/tests/classes/test_reportviews.py
python/graphscope/experimental/nx/tests/test_nx.py
python/graphscope/framework/graph.py
python/setup.cfg

- improve the document networkx style api
- add test cases of function
- add test cases of reportview
#62

[networkx] improve the document of networkx style api

---

blog/feed.xml
blog/index.html
blog/releasenotes/2021/05/10/release-notes-0.4.0.html
index.html

Add release note 0.4.0
Fixes #244.

Add release note 0.4.0

---

coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/launcher.py
coordinator/gscoordinator/utils.py
python/graphscope/config.py
python/graphscope/deploy/kubernetes/cluster.py
python/graphscope/deploy/kubernetes/resource_builder.py
python/graphscope/deploy/kubernetes/utils.py

Generalize the session interface to make it extensible

---

.github/workflows/ci.yml
analytical_engine/core/fragment/dynamic_fragment.h
tutorials/2_graph_manipulations_with_networkx_compatible_apis.ipynb
tutorials/zh/2_graph_manipulations_with_networkx_compatible_apis.ipynb

update networkx zh-cn tutorial and fix Graph.clear() bug
#62

update networkx zh-cn tutorial and fix Graph.clear() bug

---

python/jupyter/graphscope/setup.py

Fix install graphscope-jupyter extensions

---

python/jupyter/graphscope/graphscope_jupyter/graphin.py

Correct the visualization behavior

---

python/graphscope/framework/loader.py
python/jupyter/graphscope/package.json

Defaults to source when protocol not support vineyard io stream

---

docs/tutorials.rst
docs/zh/tutorials.rst

Fix the tutorial link of document

Fix the tutorial links of document

---

coordinator/gscoordinator/cluster.py
k8s/Makefile
python/graphscope/client/session.py
python/graphscope/deploy/hosts/cluster.py
python/graphscope/deploy/kubernetes/cluster.py

Reduce redundant copies of session parameters

---

research/gaia/pegasus/pegasus/src/operator/mod.rs
research/gaia/pegasus/pegasus/tests/subtask_test.rs

[BUG-Fix] Fix premature abnormal end of flatmap in subtask;

---

charts/graphscope-store-service/.helmignore
charts/graphscope-store-service/Chart.lock
charts/graphscope-store-service/Chart.yaml
charts/graphscope-store-service/README.md
charts/graphscope-store-service/templates/NOTES.txt
charts/graphscope-store-service/templates/_helpers.tpl
charts/graphscope-store-service/templates/configmap.yaml
charts/graphscope-store-service/templates/coordinator/statefulset.yaml
charts/graphscope-store-service/templates/coordinator/svc-headless.yaml
charts/graphscope-store-service/templates/frontend/statefulset.yaml
charts/graphscope-store-service/templates/frontend/svc-headless.yaml
charts/graphscope-store-service/templates/frontend/svc.yaml
charts/graphscope-store-service/templates/ingestor/statefulset.yaml
charts/graphscope-store-service/templates/ingestor/svc-headless.yaml
charts/graphscope-store-service/templates/serviceaccount.yaml
charts/graphscope-store-service/templates/store/statefulset.yaml
charts/graphscope-store-service/templates/store/svc-headless.yaml
charts/graphscope-store-service/values.yaml

Add helm charts

---

README.md
docs/frequently_asked_questions.rst
docs/index.rst
docs/installation.rst
docs/zh/frequently_asked_questions.rst
docs/zh/index.rst
docs/zh/installation.rst

Add FAQ doc

---

research/gaia/pegasus/pegasus/Cargo.toml
research/gaia/pegasus/pegasus/src/communication/output/output.rs
research/gaia/pegasus/pegasus/src/communication/output/session.rs
research/gaia/pegasus/pegasus/src/data.rs
research/gaia/pegasus/pegasus/src/event/utils.rs
research/gaia/pegasus/pegasus/src/operator/binary.rs
research/gaia/pegasus/pegasus/src/operator/cancel.rs
research/gaia/pegasus/pegasus/src/operator/iteration/feedback.rs
research/gaia/pegasus/pegasus/src/operator/iteration/merge_switch.rs
research/gaia/pegasus/pegasus/src/operator/iteration/mod.rs
research/gaia/pegasus/pegasus/src/tag/mod.rs
research/gaia/pegasus/pegasus/src/tag/tools/anti_chain.rs

New scope tag implementation, try to achieve zero-cost and lower overhead when calling `clone` or other methods of it;
#357

[GAIA] Redo scope tag implement, to reduce runtime overhead;

---

charts/graphscope/templates/coordinator.yaml
charts/graphscope/values.yaml

add coordinator params "preemptive" in graphscope charts

---

.github/workflows/ci.yml
.github/workflows/local.yml
analytical_engine/CMakeLists.txt
coordinator/gscoordinator/template/CMakeLists.template
interactive_engine/src/executor/runtime/native/CMakeLists.txt
k8s/graphscope.Dockerfile
k8s/graphstore.Dockerfile
k8s/gsvineyard.Dockerfile
scripts/build.sh

As we have included many bugfixes in the past month.

Upgrade vineyard to v0.2.2.

---

research/gaia/pegasus/pegasus/src/event/io/mod.rs

add encode for single event
Fixes #368

[GAIA] add encode for single event

---

python/jupyter/graphscope/package.json

1、修复 jupyter  暗色系下 body 样式问题；
2、修复 markdown cell 下标题样式问题。
Fixes

fix: body background style

---

.github/workflows/ci.yml
python/graphscope/deploy/tests/test_store_service.py

Release graphstore image in CI step.

Test release step

---

coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/template/CMakeLists.template
interactive_engine/src/data_load_tools/README.md
proto/message.proto
python/graphscope/client/rpc.py
python/graphscope/client/session.py

Check version compatibility during session connecting

---

interactive_engine/src/data_load_tools/README.md
interactive_engine/src/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/OfflineBuild.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/frontend/ClientService.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/sdk/Client.java
interactive_engine/src/v2/src/main/proto/client.proto

remove partition num config from data build
#412

refine bulk load

---

research/gaia/gremlin/gremlin_core/src/process/traversal/step/by_key.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/flat_map/mod.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/flat_map/values.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/map/get_property.rs
research/gaia/gremlin/gremlin_core/src/result_process.rs
research/gaia/gremlin/gremlin_core/src/storage.rs
research/gaia/gremlin/gremlin_core/src/structure/filter/codec.rs
research/gaia/gremlin/gremlin_core/src/structure/filter/element/by_property.rs
research/gaia/gremlin/gremlin_core/src/structure/filter/element/mod.rs
research/gaia/gremlin/gremlin_core/src/structure/mod.rs
research/gaia/gremlin/gremlin_core/src/structure/property.rs
research/gaia/gremlin/gremlin_core/tests/common/mod.rs
research/gaia/gremlin/gremlin_core/tests/map_test.rs
research/gaia/gremlin/gremlin_core/tests/property_opt_test.rs
research/gaia/gremlin/proto/gremlin.proto
research/gaia/gremlin/proto/gremlin_result.proto

Support prop_id in GAIA runtime

---

coordinator/gscoordinator/dag_manager.py
coordinator/gscoordinator/utils.py
python/graphscope/framework/app.py
python/graphscope/framework/dag.py
python/graphscope/framework/dag_utils.py
python/graphscope/framework/graph.py
python/graphscope/framework/operation.py
python/tests/test_lazy.py

Add unload graph/app test cases for lazy mode execution

---

research/gaia/gremlin/gremlin_core/benches/common/mod.rs
research/gaia/gremlin/gremlin_core/src/compiler.rs
research/gaia/gremlin/gremlin_core/src/lib.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/source.rs
research/gaia/gremlin/gremlin_core/tests/common/mod.rs

Refine gen source

---

research/gaia/pegasus/network/src/lib.rs
research/gaia/pegasus/network/src/manager.rs

add SimpleServerDetector for Gaia
#437

add SimpleServerDetector

---

blog/feed.xml
blog/index.html
blog/releasenotes/2021/06/15/release-notes-0.5.0.html
index.html

add release note 0.5

---

.github/workflows/ci.yml
interactive_engine/src/executor/Pegasus/Cargo.toml
interactive_engine/src/executor/jna/Cargo.toml
interactive_engine/src/executor/jna/src/executor/gaia/mod.rs
interactive_engine/src/executor/jna/src/lib.rs
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/common/discovery/RoleType.java
k8s/graphscope-store.Dockerfile

add interface for integration
#447

add interface

---

python/jupyter/graphscope/package.json
python/jupyter/graphscope/src/graph.ts

update @graphscope/graphscope-jupyter version and build config.
Fixes

Fix building config for graphscope-jupyter extensions

---

docs/getting_started.rst
docs/zh/getting_started.rst

Related to https://github.com/alibaba/GraphScope/discussions/456.

Add instructions for mount volume in mac

---

.github/workflows/local.yml
analytical_engine/core/fragment/dynamic_fragment.h
analytical_engine/core/loader/arrow_to_dynamic_converter.h
analytical_engine/core/loader/dynamic_to_arrow_converter.h
analytical_engine/frame/property_graph_frame.cc
coordinator/gscoordinator/builtin/app/.gs_conf.yaml
python/graphscope/deploy/tests/test_with_mars.py
python/graphscope/nx/tests/test_ctx_builtin.py
python/graphscope/nx/tests/test_nx.py
python/requirements.txt

Fix the convert bug with wrong edge number when convert between directed graphscope graph and network graph.
Fixes #436

Fix bug in directed graph transformation between graphscope and nx

---

.github/workflows/ci.yml
.github/workflows/local.yml
analytical_engine/CMakeLists.txt
coordinator/gscoordinator/template/CMakeLists.template
interactive_engine/src/executor/runtime/native/CMakeLists.txt
k8s/graphscope-store.Dockerfile
k8s/graphscope.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/ubuntu/gsruntime.Dockerfile
python/requirements.txt
scripts/build.sh
scripts/install_dependencies.sh

Upgrade vineyard to latest version.
N/A

Upgrade vineyard to v0.2.5

---

interactive_engine/src/executor/jna/src/executor/gaia/gaia_server.rs

fix gaia async rpc server lifecycle bug 
#473

fix gaia server lifecycle

---

interactive_engine/src/executor/runtime/src/store/v2/global_graph.rs

fix bug in graph_store impl
#476

fix store bug

---

coordinator/gscoordinator/coordinator.py

Set GRPC max message length options in coordinator server side

---

docs/deployment.rst
docs/developer_guide.rst
scripts/build.sh
scripts/install_dependencies.sh

Script support local deployment in MacOS
Fixes #429

Script support local deployment in MacOS

---

interactive_engine/src/executor/runtime/src/dataflow/manager/range.rs
interactive_engine/src/executor/store/src/db/api/error.rs
interactive_engine/src/executor/store/src/db/graph/store.rs

fix gremlin-test for mg on graphstore service
#488

fix gremlin-test for mg

---

.github/workflows/ci.yml
k8s/gsruntime.Dockerfile

The runtime image will be released later.

Use a higher version git

---

research/gaia/gremlin/gremlin_core/src/process/traversal/step/flat_map/explore.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/map/edge_v.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/map/identity.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/source.rs
research/gaia/gremlin/gremlin_core/src/structure/graph.rs
research/gaia/gremlin/proto/gremlin.proto

Add extra params for compatible with different storages

---

.github/workflows/ci.yml

Seperate the pytest in ci to avoid oom

---

interactive_engine/src/executor/jna/Cargo.toml
interactive_engine/src/executor/jna/src/executor/gaia/gaia_server.rs
interactive_engine/src/executor/jna/src/executor/gaia/mod.rs
research/gaia/gremlin/gs_gremlin/src/graph_proxy/mod.rs
research/gaia/gremlin/gs_gremlin/src/lib.rs

Initialize job compiler in adapter for starting engine service

---

research/gaia/gremlin/compiler/conf/gremlin-server.yaml
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/LogicPlanGlobalMap.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/PlanUtils.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/AbstractGraphOpProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/GaiaGraphOpProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/LogicPlanProcessor.java

use gremlin api in 3.4.2 to be compatible with maxgraph

---

scripts/prepare_env.sh

Revise the prepare_env.sh, more standard and user-friendly
Fixes #517

Revise the prepare_env.sh, more standard and user-friendly

---

interactive_engine/src/executor/store/src/lib.rs
interactive_engine/src/executor/store/src/v2/api/condition.rs
interactive_engine/src/executor/store/src/v2/api/mod.rs
interactive_engine/src/executor/store/src/v2/api/partition_snapshot.rs
interactive_engine/src/executor/store/src/v2/api/types.rs
interactive_engine/src/executor/store/src/v2/errors.rs
interactive_engine/src/executor/store/src/v2/mod.rs

add new local store interface with support for gnn
Fixes #542

checkin store v2 interface

---

interactive_engine/src/v2/pom.xml
proto/write_service.proto

add realtime_write proto

---

interactive_engine/src/common/java/src/main/java/com/alibaba/maxgraph/common/cluster/InstanceConfig.java
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/DirectChannelFetcher.java
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/MaxGraphConfig.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/broadcast/AbstractBroadcastProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/broadcast/RpcBroadcastProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/broadcast/channel/HostsChannelFetcher.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/broadcast/channel/RpcChannelFetcher.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/GaiaGraphOpProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/GaiaProcessorLoader.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/TraversalOpProcessor.java

Unify rpc api

---

research/gaia/gremlin/compiler/compiler-core/src/main/java/com/alibaba/graphscope/gaia/FilterHelper.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/PlanUtils.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/extractor/TagKeyExtractorFactory.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/predicate/HasContainerP.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/strategy/SchemaIdMakerStrategy.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/AbstractGraphOpProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/TraversalOpProcessor.java

Fix gss test bugs

---

research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/GaiaGraphOpProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/TraversalOpProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/result/DefaultResultParser.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/result/RemoteTraverserResultParser.java
research/gaia/gremlin/gremlin_core/src/result_process.rs
research/gaia/gremlin/gremlin_core/src/structure/element/edge.rs
research/gaia/gremlin/proto/gremlin_result.proto

Fix edge result

---

.github/workflows/local.yml
python/tests/test_run_locally.py

Fix session.close for local test

---

.github/workflows/minimum.yml
python/tests/test_minimum.py

Add minimum CI test

---

interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/MaxGraph.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/common/NodeBase.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/store/GaiaStore.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/store/executor/gaia/GaiaService.java

seperate gaia store
Fixes #578

divide store

---

coordinator/gscoordinator/object_manager.py
interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/parser/Generator.java
python/tests/test_minimum.py

Coordinator get source to source json successful from gae compiler

---

interactive_engine/src/assembly/pom.xml
interactive_engine/src/frontend/frontendservice/src/main/java/com/alibaba/maxgraph/frontendservice/Frontend.java
interactive_engine/src/gaia-adaptor/pom.xml
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/vineyard/store/AddressChannelFetcher.java
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/vineyard/store/AsyncRpcBroadcastProcessor.java
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/vineyard/store/Frontend.java
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/vineyard/store/FrontendServiceMain.java
interactive_engine/src/instance-manager/script/start_local_gaia_frontend.sh
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/AsyncRpcBroadcastProcessor.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/AsyncRpcChannelFetcher.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/CachedMaxGraphMeta.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/ChannelManagerFetcher.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/DirectChannelFetcher.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/Frontend.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/GaiaGraphServer.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/MaxGraphConfig.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/MaxGraphStore.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/MaxNode.java
interactive_engine/src/v2/src/main/resources/conf/server.gaia.yaml
research/gaia/gremlin/compiler/conf/graph.properties
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/GaiaGraphOpProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/GaiaProcessorLoader.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/processor/TraversalOpProcessor.java

add vineyard adaptor

---

.github/workflows/local.yml
Makefile
coordinator/gscoordinator/launcher.py
docs/deployment.rst
docs/developer_guide.rst
docs/zh/deployment.rst
scripts/deploy_local.sh

- support build and deploy on CentOS
- fix some errors run on ubuntu/centos/macOS
- check more dependencies
- check illegal options and output usage
- 
Fixes #566

Update deploy_local.sh:  add CentOS support and more robust

---

interactive_engine/src/executor/Cargo.toml
interactive_engine/src/executor/gaia_runtime/Cargo.toml
interactive_engine/src/executor/gaia_runtime/src/bin/gaia_executor.rs
interactive_engine/src/executor/gaia_runtime/src/lib.rs
interactive_engine/src/executor/gaia_runtime/src/server/manager.rs
interactive_engine/src/executor/gaia_runtime/src/server/mod.rs
interactive_engine/src/executor/runtime/src/rpc/rpc_pegasus/async_maxgraph_service.rs
interactive_engine/src/executor/runtime/src/store/task_partition_manager.rs
interactive_engine/src/executor/server/src/lib.rs
interactive_engine/src/instance-manager/script/start_local_gaia_executor.sh

[GAIA] Start GAIA executor with vineyard store

---

research/gaia/gremlin/gremlin_core/src/compiler.rs
research/gaia/gremlin/gremlin_core/src/graph_proxy/storage.rs
research/gaia/gremlin/gremlin_core/src/lib.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/source.rs
research/gaia/gremlin/gremlin_core/src/structure/graph.rs
research/gaia/gremlin/gremlin_core/tests/common/mod.rs
research/gaia/gremlin/gs_gremlin/src/graph_proxy/global_storage.rs
research/gaia/gremlin/gs_gremlin/src/graph_proxy/mod.rs
research/gaia/gremlin/gs_gremlin/src/graph_proxy/partitioner.rs

[GAIA & Store Adapter] Support parallel scan in GAIA,  and adapt to v2 and vineyard respectively

---

.gitignore
interactive_engine/src/common/java/src/main/java/com/alibaba/maxgraph/common/cluster/InstanceConfig.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/MaxGraphConfig.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/MaxGraph.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/config/ExperimentalGaiaConfig.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/config/GaiaConfig.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/PlanUtils.java

add additional pegasus config for benchmark

---

interactive_engine/src/executor/gaia_runtime/src/bin/gaia_executor.rs
interactive_engine/src/executor/gaia_runtime/src/server/manager.rs
research/gaia/gremlin/gs_gremlin/src/graph_proxy/mod.rs
research/gaia/gremlin/gs_gremlin/src/graph_proxy/partitioner.rs
research/gaia/gremlin/gs_gremlin/src/lib.rs

Fix starting GAIA executor with vineyard store by:
1. Pass worker_partition_list_mapping to GAIA adapter to enable parallel scan;
2. Set rpc port for gaia service with store_config.rpc_port, and allow random assignment if store_config.rpc_port is 0

[Bug Fix] GAIA executor with vineyard 

---

interactive_engine/src/executor/gaia_runtime/src/bin/gaia_executor.rs
interactive_engine/src/instance-manager/script/create_local_instance.sh
interactive_engine/src/instance-manager/script/start_local_gaia_executor.sh

(1) Add script for starting gaia executor
(2) Support passing different graph_name config to enable starting old pegasus and new gaia executor together on vineyard

 [script] Start GAIA executor on Vineyard

---

Makefile
interactive_engine/src/common/java/src/main/java/com/alibaba/maxgraph/common/util/CommonUtil.java
interactive_engine/src/instance-manager/script/create_local_instance.sh
interactive_engine/src/instance-manager/script/start_local_gaia_coordinator.sh
interactive_engine/src/instance-manager/script/start_local_gaia_frontend.sh

Starting GAIA on vineyard on condition that GAIA_ENABLE is true
Fixes

[script] Add scripts for starting GAIA on vineyard

---

.github/workflows/minimum.yml
analytical_engine/apps/GatherScatter/IVertexProgram.h
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/object_manager.py
coordinator/gscoordinator/utils.py
interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/parser/GAE.java
interactive_engine/src/gae/src/main/java/s2scompiler/GenerateCode.java
interactive_engine/src/gae/src/main/java/s2scompiler/Result.java
interactive_engine/src/gae/src/main/java/s2scompiler/S2SCompiler.java
interactive_engine/src/gae/src/main/java/s2scompiler/steps/TransProcess.java
interactive_engine/src/instance-manager/script/start_local_coordinator.sh
interactive_engine/src/instance-manager/script/start_local_executor.sh
interactive_engine/src/instance-manager/script/start_local_frontend.sh
python/tests/test_minimum.py

Make demo pagerank order by runnable

---

coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/object_manager.py
coordinator/gscoordinator/utils.py
python/graphscope/client/session.py
python/graphscope/framework/dag_utils.py
python/graphscope/interactive/graph_traversal.py
python/tests/test_minimum.py

Make pagerank orderby with traversal source mode runnable

---

interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/GAEOpProcessor.java
interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/QueryType.java
interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/parser/GAE.java
interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/parser/GIE.java
interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/parser/GLE.java
interactive_engine/src/gae/src/main/java/org/apache/tinkperpop/gremlin/groovy/custom/AddColumnStep.java
interactive_engine/src/gae/src/main/java/org/apache/tinkperpop/gremlin/groovy/custom/CustomGraphTraversal.java
interactive_engine/src/gae/src/main/java/org/apache/tinkperpop/gremlin/groovy/custom/SampleStep.java
interactive_engine/src/gae/src/main/java/org/apache/tinkperpop/gremlin/groovy/custom/TensorFlowStep.java
interactive_engine/src/gae/src/main/java/org/apache/tinkperpop/gremlin/groovy/custom/TraversalProcessStep.java
interactive_engine/src/gae/src/main/resources/gle.sample.json
interactive_engine/src/gae/src/main/resources/gle.tensorflow.json
interactive_engine/src/gae/src/main/resources/query/graph.learn.json
interactive_engine/src/gae/src/test/java/com/alibaba/graphscope/gae/SubmitGaeTest.java
python/graphscope/interactive/graph_traversal.py
python/tests/test_minimum.py

[GAE Compiler] Add new support for operations of graphlearn

---

interactive_engine/src/executor/Cargo.lock
interactive_engine/src/lgraph/CMakeLists.txt
interactive_engine/src/lgraph/build.sh
interactive_engine/src/lgraph/include/db/common/types.h
interactive_engine/src/lgraph/include/db/graph/snapshot.h
interactive_engine/src/lgraph/jna/native.h
interactive_engine/src/lgraph/jna/test.h
interactive_engine/src/lgraph/pom.xml
interactive_engine/src/lgraph/src/edge.cc
interactive_engine/src/lgraph/src/error.cc
interactive_engine/src/lgraph/src/jna/native.cc
interactive_engine/src/lgraph/src/jna/test.cc
interactive_engine/src/lgraph/src/property.cc
interactive_engine/src/lgraph/src/snapshot.cc
interactive_engine/src/lgraph/src/vertex.cc
interactive_engine/src/lgraph/store_ffi/store_ffi.h

Add store test in lgraph jna.

---

research/gaia/gremlin/gremlin_core/src/lib.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/traverser.rs

fix the bug in path().count(), e.g., g.V().path().count()
Fixes

[Bug Fix]: fix bug in path().count()

---

interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/GAEOpProcessor.java
interactive_engine/src/gae/src/main/java/com/alibaba/graphscope/gae/parser/GIE.java
interactive_engine/src/gae/src/test/java/com/alibaba/graphscope/gae/SubmitGaeTest.java

[fix bug] bugs in pattern of process(traversal) + sample

---

coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/dag_manager.py
coordinator/gscoordinator/utils.py
proto/types.proto
python/graphscope/client/session.py
python/graphscope/interactive/graph_traversal.py
python/graphscope/learning/extra.py
python/graphscope/learning/graph.py
python/tests/test_minimum.py

Make GraphLearn demo runnable.

---

.github/workflows/ci.yml
interactive_engine/src/data_load_tools/pom.xml
interactive_engine/src/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/DataBuildPartitioner.java
interactive_engine/src/v2/pom.xml
k8s/graphscope-store.Dockerfile

fix reverse edge index bug
Fixes #626

Fix data load

---

interactive_engine/src/lgraph/build.sh

fix ci test

---

.github/workflows/ci.yml
analytical_engine/CMakeLists.txt
coordinator/gscoordinator/template/CMakeLists.template
interactive_engine/src/executor/runtime/native/CMakeLists.txt
k8s/graphscope-store.Dockerfile
k8s/graphscope.Dockerfile
k8s/gsvineyard.Dockerfile
scripts/deploy_local.sh

For preparing the v0.6.0 release.

Upgrade to vineyard v0.2.6.

---

docs/analytics_engine.rst
docs/reference/cython_sdk.rst

Add glossory to analytics_engine.rst

---

index.html

Update index.html for graphscope.io

---

.github/workflows/ci.yml
interactive_engine/src/v2/src/test/resources/logback-test.xml

refine gremlin test
Fixes #662

refine gremlin test

---

interactive_engine/src/executor/Pegasus/src/allocate/mod.rs
interactive_engine/src/executor/Pegasus/src/execute.rs
interactive_engine/src/executor/Pegasus/src/graph/topology.rs
interactive_engine/src/executor/Pegasus/src/operator/mod.rs
interactive_engine/src/executor/Pegasus/src/operator/source.rs
interactive_engine/src/executor/Pegasus/src/strategy.rs
interactive_engine/src/executor/gaia_runtime/src/bin/gaia_executor.rs
interactive_engine/src/executor/runtime/src/dataflow/manager/lambda.rs
interactive_engine/src/executor/runtime/src/dataflow/manager/order.rs
interactive_engine/src/executor/runtime/src/dataflow/operator/unarystep/vertex.rs
interactive_engine/src/executor/runtime/src/dataflow/plan/tiny_builder.rs
interactive_engine/src/executor/runtime/src/rpc/rpc_pegasus/async_maxgraph_service.rs
interactive_engine/src/executor/server/src/processor/common.rs
research/gaia/gremlin/gremlin_core/src/result_process.rs

Fix warnings in pegasus and runtime in interactive engine 

---

.github/workflows/ci.yml
k8s/graphscope-store.Dockerfile
k8s/graphscope.Dockerfile
research/gaia/pegasus/clients/java/client/pom.xml
scripts/deploy_local.sh

support java16 && upgrade rust toolchain
Fixes #565

support java16 && upgrade rust toolchain

---

interactive_engine/src/instance-manager/src/main/java/com/alibaba/maxgraph/admin/controller/InstanceManagerController.java

fix sending unvalidated data to a web browser

---

interactive_engine/pom.xml
interactive_engine/tests/pom.xml
research/gaia/gremlin/compiler/pom.xml

Fixes #582
Fixes #585
Fixes #588

Upgrade dependency

---

interactive_engine/pom.xml

fix vintage version for junit
Fixes #682

fix vintage version for junit

---

python/graphscope/framework/dag_utils.py

Fix failure of launching learning engine by allowing pickle None value

---

.github/workflows/docker_nightly.yml

Fix docker nightly ci: schedule time and gstest clean

---

interactive_engine/bin/giectl

An ad-hoc solution to find frontend port from log file

---

analytical_engine/CMakeLists.txt
coordinator/gscoordinator/template/CMakeLists.template
interactive_engine/src/executor/runtime/native/CMakeLists.txt

discussion https://github.com/alibaba/GraphScope/discussions/611

Update cmake minimum version to 3.1 for gie

---

interactive_engine/src/frontend/compiler/src/main/java/com/alibaba/maxgraph/server/MaxGraphServer.java
interactive_engine/src/gaia-adaptor/gremlin_test.sh
interactive_engine/src/gaia-adaptor/pom.xml
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/vineyard/store/AddressChannelFetcher.java
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/vineyard/store/Frontend.java
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/vineyard/store/GaiaGraphServer.java
interactive_engine/src/gaia-adaptor/src/main/java/com/alibaba/graphscope/gaia/vineyard/store/VineyardGraphStore.java
interactive_engine/src/gaia-adaptor/src/main/resources/conf/server.gaia.yaml
interactive_engine/src/tree
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/ChannelManagerFetcher.java
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/Frontend.java
interactive_engine/src/v2/src/test/java/com/alibaba/maxgraph/tests/sdk/DataLoadingTest.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/broadcast/AsyncRpcBroadcastProcessor.java
research/gaia/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/broadcast/channel/AsyncRpcChannelFetcher.java

Remove dependency of v2 from gaia-adaptor

---

.github/workflows/docker_nightly.yml
k8s/ubuntu/gsvineyard.Dockerfile
python/graphscope/client/rpc.py

Missing close method in RPC client.

---

coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/dag_manager.py
coordinator/gscoordinator/launcher.py
coordinator/gscoordinator/utils.py
coordinator/requirements.txt
proto/types.proto
python/graphscope/framework/context.py
python/graphscope/framework/dag_utils.py
python/graphscope/framework/graph.py
python/graphscope/framework/graph_builder.py
python/graphscope/framework/graph_utils.py
python/graphscope/framework/loader.py
python/graphscope/framework/operation.py
python/tests/unittest/test_context.py

Make I/O a lazy DAGNode in the coordinator

---

coordinator/gscoordinator/template/pie.pxd.template
docs/developer_guide.rst
docs/installation.rst
docs/reference/cython_sdk.rst
docs/zh/developer_guide.rst
python/graphscope/analytical/udf/types.py
python/graphscope/client/session.py

Fixes #482 
Fixed #430 
This pr also enrich the developer guide by allowing building and testing GraphScope locally in docker container.

Improve Cython API doc by adding 'graphscope.declare' 'graphscope.Vertex' in cython_sdk.rst

---

.github/workflows/ci.yml
interactive_engine/src/v2/src/test/java/com/alibaba/maxgraph/tests/gremlin/MaxTestGraph.java

Fix gremlin hang

---

.github/workflows/ci.yml
interactive_engine/distribution/src/assembly/assembly.xml
interactive_engine/distribution/src/bin/max_node.sh
interactive_engine/distribution/src/bin/maxgraph-env
interactive_engine/src/v2/src/main/java/com/alibaba/graphscope/gaia/Frontend.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/frontend/ClientWriteService.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/frontend/SnapshotCache.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/frontend/write/GraphWriter.java
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/grafting/frontend/WrappedSchemaFetcher.java
python/graphscope/client/connection.py
python/graphscope/framework/record.py
python/requirements-dev.txt
python/tests/kubernetes/test_store_service.py

Realtime write in Python side, and add tests in CI.

---

.github/workflows/ci.yml
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/io_utils.py
coordinator/gscoordinator/launcher.py
python/tests/kubernetes/test_demo_script.py

Add a ci to test loading graph from HDFS

---

coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/launcher.py
interactive_engine/bin/giectl
interactive_engine/conf/executor.vineyard.properties
interactive_engine/src/executor/gaia_runtime/src/server/manager.rs
interactive_engine/src/executor/runtime/src/dataflow/test/mod.rs
interactive_engine/src/executor/store/src/config/store_config.rs
python/tests/kubernetes/test_with_gaia.py

Fix pegasus service

---

coordinator/gscoordinator/coordinator.py

Config coordinator logger to handle warning level to stderr

---

docs/index.rst
docs/persistent_graph_store.rst
interactive_engine/src/data_load_tools/pom.xml
interactive_engine/src/data_load_tools/src/assembly/assembly.xml
interactive_engine/src/data_load_tools/src/bin/load_tool.sh

add doc for persistent graph store
Fixes #391

add doc for persistent graph store

---

k8s/graphscope-store.Dockerfile

add copy to /tmp

---

python/graphscope/framework/graph.py
python/graphscope/framework/graph_builder.py
python/graphscope/framework/graph_utils.py
python/jupyter/graphscope/graphscope_jupyter/graphin.py
python/pyproject.toml
python/requirements.txt
python/tests/unittest/test_udf_app.py

Vineyard is no longer a hard dependency for the client package.

---

python/graphscope/framework/graph_utils.py

Follow-up patch for #780.
Fixes #779

Fixes the condition of whether vineyard exists.

---

.github/workflows/ci.yml
interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/frontend/SnapshotCache.java
python/graphscope/framework/graph_schema.py
python/tests/kubernetes/test_store_service.py

Fix graph store restart

---

.gitignore
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/object_manager.py
coordinator/gscoordinator/utils.py

Fixes CI exception of io loop event  by closing gremlin python client

---

coordinator/gscoordinator/template/CMakeLists.template

Otherwise we are working with "Debug" build actually.
N/A

Build app/graph frames: with "Release" profile by default.

---

python/graphscope/config.py

Increase the resource size of coordinator for running demo of README

---

.github/workflows/docker_nightly.yml

Enable manually trigger docker nightly ci

---

.github/workflows/ci.yml
.github/workflows/graphscope.Dockerfile
Makefile
interactive_engine/bin/giectl
interactive_engine/src/assembly/pom.xml
k8s/graphscope.Dockerfile

rename maxgraph package name

---

coordinator/setup.py
python/graphscope/client/rpc.py

It will raise errors like `error: [Errno 20] Not a directory: '/root/GraphScope/coordinator/gscoordinator/builtin/app/builtin_app.zip'`,
Since there is `ignore_errors=True` these errors have been ignored before.
Also make the code more cleaner.

`shutil.rmtree` cannot remove files

---

.github/workflows/ci.yml
analytical_engine/core/fragment/dynamic_fragment_reporter.h
analytical_engine/core/grape_instance.cc
analytical_engine/core/grape_instance.h
analytical_engine/core/object/app_entry.h
analytical_engine/frame/app_frame.cc
analytical_engine/frame/cython_app_frame.cc
analytical_engine/frame/cython_pie_app_frame.cc
coordinator/gscoordinator/utils.py
proto/op_def.proto
proto/types.proto
python/graphscope/client/rpc.py
python/graphscope/framework/context.py
python/graphscope/framework/dag_utils.py

And uniformed the naming of context key/name.

Add methods to unload contexts.

---

docs/persistent_graph_store.rst

Fix typo in graph store doc

---

charts/graphscope-store/README.md
docs/persistent_graph_store.rst

Add parameters section to Store docs

---

.github/workflows/docker_nightly.yml

Nightly: don't run on forks.

---

.github/workflows/local.yml
Makefile
interactive_engine/bin/giectl
interactive_engine/src/executor/runtime/src/store/ffi.rs
interactive_engine/src/gaia-adaptor/pom.xml
python/tests/local/test_run_locally.py
scripts/deploy_local.sh

- update the deploy script
- open the macOS ci
since the macOS vm of github runner has some issues to run demo of GraphScope, we add a partial demo test `test_on_macOS` for mac. Open the full demo test if macOS vm becomes normal.
#565 
#781

Update local deploy script: upgrade jdk toolchain and open macOS CI

---

python/graphscope/client/rpc.py

Fix an incorrect error initialization

---

coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/launcher.py
coordinator/gscoordinator/utils.py
python/graphscope/dataset/__init__.py
python/graphscope/dataset/io_utils.py
python/graphscope/dataset/ldbc.py
python/graphscope/dataset/modern_graph.py
python/graphscope/dataset/ogbn_mag.py
python/requirements.txt
python/tests/unittest/test_graph.py

Support download dataset from origin URL in standalone mode

---

research/gaia-x/gremlin/gremlin_core/src/process/traversal/step/map/edge_v.rs
research/gaia/gremlin/gremlin_core/src/process/traversal/step/map/edge_v.rs

Fix bug in EdgeVertex step, i.e., inV(), outV(), etc., that if we fail in query vertices from store, we generate id-only vertex directly.
Fixes

[Bug Fix] Fix bug in EdgeVertex step

---

interactive_engine/src/executor/ffi/src/executor/gaia/gaia_server.rs
interactive_engine/src/executor/gaia_runtime/src/server/manager.rs

Fix bug in starting gaia service, which should register gremlin types first
Fixes N/A

[Bug Fix] fix bug in starting GAIA service in v2 and vineyard

---

scripts/prepare_env.sh

Signed-off-by: acezen <weibin.zen@gmail.com>

Fix: update kind download URL

---

k8s/graphscope.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/manylinux2014.Dockerfile

Merging dockerfile changeset as seperate PRs to avoid potential conflicts between ongoing PRs.
Part of #60.

Install LLVM and fastFFI in runtime/gsvineyard docker image.

---

.github/workflows/ci.yml
analytical_engine/core/object/fragment_wrapper.h
analytical_engine/core/server/dispatcher.h
analytical_engine/core/server/graphscope_service.cc
k8s/Makefile
k8s/graphscope-store.Dockerfile
k8s/graphscope.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/ubuntu/gsvineyard.Dockerfile
proto/graph_def.proto
python/graphscope/framework/graph.py
python/graphscope/nx/classes/graph.py
python/graphscope/nx/tests/test_copy_on_write.py
scripts/deploy_local.sh

Add parallel edge check when init nx graph with  gs graph 
Fixes #810
Fixes #796 
vineyard check parallel edge issue: https://github.com/v6d-io/v6d/pull/563

[networkx] Riase `NetworkXError` when gs graph is multigraph

---

charts/graphscope/templates/coordinator.yaml
charts/graphscope/values.yaml
k8s/Makefile
k8s/jupyter.Dockerfile

Fixes helm charts jupyterlab container: use release version as image tag

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/local.yml
Makefile
coordinator/gscoordinator/utils.py
coordinator/requirements.txt
k8s/Makefile
python/graphscope/framework/utils.py
python/requirements.txt
scripts/deploy_local.sh

Fixes CI failure with `tensorflow>=2.6.0` 
Fixes #948

Fix CI failure of main branch by install tensorflow<=2.5.2

---

research/dyn_type/src/arith.rs
research/dyn_type/src/error.rs
research/dyn_type/src/lib.rs
research/dyn_type/src/object.rs
research/dyn_type/tests/object.rs

As titled.
None issue. This is a part of Gaia-x integration.

[gaia-x] update dyn_type to include some arithmetic and logical operations on Primitives and Object

---

.github/workflows/local.yml
interactive_engine/common/src/main/java/com/alibaba/maxgraph/common/config/BackupConfig.java
interactive_engine/distribution/src/conf/config.template
interactive_engine/gaia-adaptor/gremlin_test.sh
interactive_engine/groot/src/main/java/com/alibaba/graphscope/groot/store/BackupAgent.java
interactive_engine/groot/src/main/java/com/alibaba/graphscope/groot/store/jna/JnaGraphStore.java
interactive_engine/sdk/backup_test.sh
interactive_engine/sdk/pom.xml
interactive_engine/sdk/src/main/java/com/alibaba/graphscope/groot/sdk/Client.java
interactive_engine/sdk/src/test/java/com/alibaba/graphscope/groot/sdk/ClientBackupTest.java
interactive_engine/sdk/src/test/java/com/alibaba/graphscope/groot/sdk/ClientTest.java

Add backup e2e test

---

.github/workflows/ci.yml

add path filtering for steps, separate NetworkX python tests
related issue #918

[CI] Add path filtering for jobs or step, separate NetworkX python tests

---

docs/reference/networkx/graphs.rst
docs/reference/networkx/index.rst
docs/reference/networkx/transformation.rst
python/graphscope/nx/classes/digraph.py
python/graphscope/nx/classes/graph.py
python/graphscope/nx/tests/algorithms/builtin/test_hits.py
python/graphscope/nx/tests/algorithms/builtin/test_pagerank.py

update document of transformation
Fixes #786

[networkx] Improve the document of transformation

---

.github/workflows/ci.yml

Fix CI: No strategy for build-gae

---

coordinator/gscoordinator/template/CMakeLists.template
coordinator/gscoordinator/utils.py
python/graphscope/framework/utils.py

Fix the following warning:
```
CMake Warning:
Manually-specified variables were not used by the project:
PYTHON_EXECUTABLE
```

Remove unused cmake variable

---

python/graphscope/dataset/ogbl_collab.py
python/graphscope/dataset/ogbl_ddi.py
python/graphscope/dataset/ogbn_proteins.py
python/tests/unittest/test_download.py

Add proteins, ddi and collab datasets.
Fixes #776

Add proteins, ddi and collab datasets

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml

Schedule build_wheels CI as nightly run

---

coordinator/gscoordinator/launcher.py
interactive_engine/assembly/bin/giectl

Add GRPAHSCOPE_HOME/lib to DYLD_LIBRARY_PATH

---

README-zh.md
README.md
docs/getting_started.rst
docs/interactive_engine.rst
docs/zh/interactive_engine.rst
interactive_engine/gaia-adaptor/gaia_on_vineyard_test.sh
python/graphscope/dataset/__init__.py
python/graphscope/dataset/io_utils.py
python/graphscope/dataset/ldbc.py
python/graphscope/dataset/modern_graph.py
python/graphscope/dataset/ogbl_collab.py
python/graphscope/dataset/ogbl_ddi.py
python/graphscope/dataset/ogbn_arxiv.py
python/graphscope/dataset/ogbn_mag.py
python/graphscope/dataset/ogbn_proteins.py
python/tests/conftest.py
python/tests/kubernetes/test_demo_script.py
python/tests/kubernetes/test_with_gaia.py
python/tests/local/test_run_locally.py
python/tests/local/test_standalone.py
python/tests/unittest/test_download.py
python/tests/unittest/test_graph.py
python/tests/unittest/test_scalability.py
tutorials/10_node_classification_on_citation_network.ipynb
tutorials/zh/10_node_classification_on_citation_network.ipynb

Simplify import path of dataset

---

.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/local.yml
Makefile
README-zh.md
README.md
analytical_engine/CMakeLists.txt
coordinator/gscoordinator/launcher.py
coordinator/gscoordinator/template/CMakeLists.template
coordinator/setup.cfg
k8s/Makefile
python/graphscope/client/session.py
python/graphscope/learning/__init__.py
python/setup.cfg
python/setup.py
python/tests/local/test_run_locally.py
python/tests/local/test_standalone.py

Support  GraphScope learning engine on MacOS
Fixes #954

Support  GraphScope learning engine on MacOS

---

README.md

Update test code of README.md

---

scripts/install_deps.sh

Signed-off-by: acezen <weibin.zen@gmail.com>
Fixes #1005

[BugFix] Print the usage when install_deps.sh without any argument

---

.github/workflows/ci.yml

currently changes job triggered by push not correctly, add a checkout action to make it correctly.

[BugFix] Make path filtering triggered correctly by push 

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/ci.yml
.github/workflows/local.yml
.gitignore
Makefile
coordinator/gscoordinator/__init__.py
coordinator/gscoordinator/launcher.py
coordinator/requirements.txt
k8s/Makefile
k8s/graphscope.Dockerfile
k8s/gsvineyard.Dockerfile
python/graphscope/deploy/hosts/cluster.py
python/graphscope/deploy/kubernetes/cluster.py
python/graphscope/learning/examples
python/graphscope/learning/graphlearn
python/requirements.txt
python/setup.cfg
python/setup.py

Support run GraphLearn in current(repo) directory

---

charts/graphscope-store/templates/serviceaccount.yaml
charts/graphscope/templates/coordinator.yaml
charts/graphscope/templates/service.yaml

Add namespace param to the Helm charts yaml files.

Add namespace param to the Helm charts

---

coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/io_utils.py
coordinator/gscoordinator/launcher.py
coordinator/gscoordinator/utils.py
python/graphscope/dataset/__init__.py
python/graphscope/dataset/cora.py
python/graphscope/dataset/p2p_network.py
python/graphscope/dataset/ppi.py
python/graphscope/dataset/user2item.py
python/graphscope/deploy/hosts/cluster.py
python/graphscope/framework/utils.py
python/tests/unittest/test_download.py

Fix subprocess streaming logs in jupyter notebook by watching PIPE

---

charts/graphscope/README.md
charts/graphscope/templates/NOTES.txt
charts/graphscope/templates/_helpers.tpl
charts/graphscope/templates/coordinator.yaml
charts/graphscope/templates/role_and_binding.yaml
charts/graphscope/templates/service.yaml
coordinator/gscoordinator/cluster.py
interactive_engine/compiler/src/main/resources/conf/server.yaml

- Change gremlin server timeout to 86400s
- Update GraphLearn submodule
Fixes #992

Fixes failure of expose gremlin service deployed with Helm Charts

---

README-zh.md
README.md
coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/coordinator.py
docs/deployment.rst
docs/loading_graph.rst
docs/zh/deployment.rst
docs/zh/loading_graph.rst
k8s/dataset.Dockerfile
python/graphscope/client/session.py
python/graphscope/config.py
python/graphscope/deploy/kubernetes/cluster.py

This PR will allow user to mount the demo dataset bucket into engine container in k8s mode.
`sess = graphscope.session(with_demo_dataset=True)` will mount the `graphscope/dataset` directory to `/dataset` path in container.

Extra option to mount demo datasets into engine container.

---

python/graphscope/dataset/README.md

update dataset readme

---

tutorials/2_graph_manipulations_with_networkx_compatible_apis.ipynb
tutorials/zh/2_graph_manipulations_with_networkx_compatible_apis.ipynb

Update tutorial of networkx manipulations

---

.github/workflows/ci.yml
charts/graphscope-store/templates/test/test-rpc.yaml

1. Give an initial delay period to helm test
2. Also test for gremlin port
3. Use python statement `socket.create_connection()` to detect port instead of curl
Fixes #998

Give an initial delay period to helm test

---

scripts/install_deps.sh

Update required vineyard version of local deploy to 0.3.10

---

coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/launcher.py
coordinator/gscoordinator/utils.py
python/graphscope/analytical/app/java_app.py
python/graphscope/deploy/hosts/cluster.py
python/graphscope/framework/utils.py

Fixes the logging lag problem.

---

blog/index.html
blog/releasenotes/2021/08/08/release-notes-0.6.0.html
blog/releasenotes/2021/09/08/release-notes-0.7.0.html
blog/releasenotes/2021/11/06/release-notes-0.8.0.html
index.html

add baidu analytics

---

research/engine/pegasus/network/src/config.rs
research/engine/pegasus/network/src/lib.rs
research/engine/pegasus/network/src/manager.rs
research/engine/pegasus/network/tests/ipc_test.rs
research/engine/pegasus/pegasus/src/lib.rs

Add some functions for starting Pegasus in GraphScope

---

interactive_engine/distribution/src/assembly/assembly.xml
interactive_engine/distribution/src/bin/maxgraph-env
interactive_engine/distribution/src/bin/store_ctl.sh
interactive_engine/lgraph/CMakeLists.txt
interactive_engine/lgraph/build.sh
interactive_engine/lgraph/cmake/LgraphConfig.cmake.in
interactive_engine/lgraph/include/lgraph/log_subscription/message.h
interactive_engine/lgraph/include/lgraph/log_subscription/subscriber.h
interactive_engine/lgraph/src/log_subscription/subscriber.cc

Add make install module for lgraph repo.

Add make install support for lgraph

---

blog/index.html
blog/releasenotes/2021/02/01/release-notes-0.2.0.html
blog/releasenotes/2021/04/11/release-notes-0.3.0.html
blog/releasenotes/2021/05/10/release-notes-0.4.0.html
blog/releasenotes/2021/06/15/release-notes-0.5.0.html
blog/releasenotes/2021/08/08/release-notes-0.6.0.html
blog/releasenotes/2021/09/08/release-notes-0.7.0.html
blog/releasenotes/2021/11/06/release-notes-0.8.0.html
blog/tech/2021/03/25/a-review-of-programming-models-for-parallel-graph-processing.html
blog/tech/2021/04/29/Introducing-gaia-a-scalable-engine-for-gremlin-the-sql-for-graphs.html
blog/tech/2021/05/29/Towards-a-Swiss-Army-Knife-for-a-Continuous-Life-Cycle-of-Big-Graph-Analytics.html
blog/tech/2021/08/05/GAIA-Deep-Dive-Bounded-Memory-Execution-and-Early-Stop-Optimization-for-Efficient-Graph-Traversal-at-Scale.html

Fix Baidu analytics

---

analytical_engine/core/loader/arrow_fragment_loader.h
python/graphscope/framework/loader.py
python/tests/unittest/test_create_graph.py
python/tests/unittest/test_lazy.py

check no duplicate property name

---

docs/_templates/layout.html

Add baidu analytics for sphinx docs.

---

.github/workflows/ci.yml
.github/workflows/networkx-forward-algo-nightly.yml
Makefile
interactive_engine/assembly/bin/giectl
interactive_engine/distribution/src/bin/store_ctl.sh
interactive_engine/distribution/src/conf/log4rs.yml
interactive_engine/distribution/src/conf/logback.xml
interactive_engine/distribution/src/conf/logback_debug.xml
k8s/graphscope-store.Dockerfile
k8s/graphscope.Dockerfile

unify the logging output file location to `/var/log/graphscope` if `/var/log` is writable. otherwise output to `$HOME/.local/log/graphscope`
Fixes #815 
related issue #1069

Unify the logging output file location to `/var/log/graphscope` or `$HOME/.local/log/graphscope`

---

coordinator/gscoordinator/object_manager.py

Fix close interactive client

---

coordinator/gscoordinator/cluster.py
python/graphscope/deploy/kubernetes/cluster.py
python/graphscope/deploy/kubernetes/resource_builder.py

Give appropriate labels to GraphScope in Kubernetes

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/ci.yml
.github/workflows/gaia.yml
.github/workflows/nightly.yml
Makefile
k8s/Makefile
k8s/graphscope-dev.Dockerfile
python/graphscope/tests/unittest/test_app.py
python/graphscope/tests/unittest/test_context.py
python/graphscope/tests/unittest/test_download.py
python/graphscope/tests/unittest/test_session.py
python/graphscope/tests/unittest/test_udf_app.py
python/setup.py

Fixes failure of nightly CI

---

python/graphscope/deploy/hosts/cluster.py

Disable pipe watch when 'show_log' is False

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/ci.yml
.github/workflows/gae.yml
.github/workflows/gss.yml
Makefile
k8s/Makefile

mount cache folder when building wheels

---

docs/tutorials.rst
docs/zh/tutorials.rst

The tutorials have been updated.
N/A

Fixes the tutorial links in the docs.

---

coordinator/gscoordinator/utils.py

Proposed by @siyuan0322 
Fixes #1086.

Fixes context processing on graphs generated by `add_column`.

---

docs/analytics_engine.rst
docs/zh/analytics_engine.rst

Update UDF document

---

analytical_engine/core/flags.cc
analytical_engine/core/flags.h
analytical_engine/core/launcher.cc
coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/launcher.py
python/graphscope/deploy/kubernetes/cluster.py

Pass vineyard_shared_mem to grape_engine for launching vineyard

---

analytical_engine/core/fragment/fragment_reporter.h
analytical_engine/core/loader/arrow_to_dynamic_converter.h
analytical_engine/core/utils/convert_utils.h
scripts/install_deps.sh

use template function to replace the extract property functions of converter and reporter.
Fixes #879

Revise the extract property functions of converter and reporter

---

Makefile

[BugFix] Fix the create log directory command

---

analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/parallel/DefaultMessageManager.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/parallel/ParallelMessageManager.java
coordinator/gscoordinator/hook/prestop/__main__.py
coordinator/gscoordinator/utils.py
coordinator/setup.py
python/graphscope/dataset/io_utils.py
python/graphscope/nx/algorithms/tests/forward/shortest_paths/test_generic.py
python/graphscope/tests/kubernetes/test_demo_script.py
python/graphscope/tests/kubernetes/test_store_service.py
python/graphscope/tests/kubernetes/test_with_mars.py
python/graphscope/tests/unittest/test_context.py
python/graphscope/tests/unittest/test_create_graph.py
python/graphscope/tests/unittest/test_graph.py
python/graphscope/tests/unittest/test_udf_app.py
research/engine/pegasus/clients/java/client/src/main/java/com/alibaba/pegasus/RpcClient.java
research/query_service/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/PlanUtils.java
research/query_service/gremlin/gremlin_core/benches/prepare_plan.sh
research/query_service/gremlin/gremlin_core/tests/prepare_test_plan.sh

Fix some problems detected by codefactor

---

interactive_engine/pom.xml
interactive_engine/tests/function_test.sh
interactive_engine/tests/pom.xml

Ignore integration tests && turn on unit tests in ci

---

research/engine/pegasus/clients/java/client/pom.xml
research/query_service/gremlin/compiler/compiler-core/pom.xml
research/query_service/gremlin/compiler/pom.xml

upgrade gaia proto to be compatible with Apple M1

---

coordinator/gscoordinator/cluster.py

Add resource limit in dataset container for QoS

---

.github/workflows/gae.yml
.github/workflows/gss.yml
.github/workflows/networkx-forward-algo-nightly.yml
analytical_engine/CMakeLists.txt
analytical_engine/core/grape_instance.cc
analytical_engine/core/object/fragment_wrapper.h
coordinator/gscoordinator/template/CMakeLists.template
coordinator/gscoordinator/utils.py
k8s/Makefile
k8s/graphscope-dev.Dockerfile
k8s/graphscope-store.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/ubuntu/gsvineyard.Dockerfile
python/graphscope/framework/dag_utils.py
python/graphscope/framework/graph.py
python/graphscope/nx/classes/graph.py
python/graphscope/tests/unittest/test_graph.py
scripts/install_deps.sh

Fixes #730
Related PR v6d-io/v6d#603

Support transformation of directed/undirected graph

---

.github/workflows/gss.yml
research/engine/pegasus/clients/java/client/pom.xml
research/query_service/gremlin/compiler/compiler-core/pom.xml
research/query_service/gremlin/compiler/pom.xml

Revert "upgrade proto to be compatible with Apple M1 (#1105)"

---

analytical_engine/apps/apsp/all_pairs_shortest_path_length.h
analytical_engine/apps/assortativity/attribute_assortativity.h
analytical_engine/apps/assortativity/average_degree_connectivity.h
analytical_engine/apps/assortativity/degree_assortativity_coefficient.h
analytical_engine/apps/centrality/betweenness/betweenness_centrality.h
analytical_engine/apps/centrality/betweenness/betweenness_centrality_generic.h
analytical_engine/apps/centrality/closeness/closeness_centrality.h
analytical_engine/apps/centrality/eigenvector/eigenvector_centrality.h
analytical_engine/apps/centrality/katz/katz_centrality.h
analytical_engine/apps/projected/sssp_projected.h
analytical_engine/apps/sssp/sssp_average_length.h
analytical_engine/apps/sssp/sssp_path.h
analytical_engine/core/context/selector.h
analytical_engine/core/context/vertex_data_context.h
analytical_engine/core/utils/trait_utils.h
analytical_engine/core/utils/transform_utils.h
coordinator/gscoordinator/utils.py
python/graphscope/framework/context.py
python/graphscope/nx/algorithms/builtin.py
python/graphscope/nx/classes/graph.py
python/graphscope/nx/tests/test_ctx_builtin.py
python/graphscope/tests/unittest/test_lazy.py

Add a selector `v.label_id` for vertex label id to support tuple node layout in result
Fixes #1093

[networkx] Add a selector `v.label_id` for vertex label id to support tuple node layout in result

---

README-zh.md
README.md

Add the "Open in Colab" badge.

---

analytical_engine/apps/simple_path/all_simple_paths.h
analytical_engine/apps/simple_path/all_simple_paths_context.h
analytical_engine/apps/simple_path/is_simple_path.h
analytical_engine/apps/simple_path/is_simple_path_context.h
python/graphscope/nx/algorithms/tests/builtin/test_simple_paths.py
python/graphscope/nx/classes/digraph.py
python/graphscope/nx/classes/graph.py
python/graphscope/nx/tests/test_ctx_builtin.py

Fix all_simple_path's bug in standalone and fix nightly forward ci

---

analytical_engine/core/utils/transform_utils.h
python/graphscope/nx/classes/digraph.py
python/graphscope/nx/classes/graph.py
python/graphscope/nx/utils/misc.py

Fix `Input op must be an Operation` error when to_directed/undirected

---

python/graphscope/tests/conftest.py
python/graphscope/tests/unittest/test_create_graph.py
python/graphscope/tests/unittest/test_udf_app.py

Fix exceptions in nightly ci

---

tutorials/1_node_classification_on_citation.ipynb
tutorials/7_unsupervised_learning_with_graphsage.ipynb
tutorials/8_supervised_learning_with_gcn.ipynb
tutorials/9_unsupervised_learning_with_bipartite_graphsage.ipynb
tutorials/zh/1_node_classification_on_citation_network.ipynb
tutorials/zh/7_unsupervised_learning_with_graphsage.ipynb
tutorials/zh/8_supervised_learning_with_gcn.ipynb
tutorials/zh/9_unsupervised_learning_with_bipartite_graphsage.ipynb

Address an module conflict issue on google colab

---

charts/graphscope/templates/NOTES.txt

Fix errors in chart helper message

---

.github/workflows/ci.yml
python/graphscope/nx/__init__.py
python/graphscope/nx/drawing/nx_pylab.py
python/graphscope/nx/generators/small.py
python/graphscope/nx/utils/compat.py

Fix import graphscope.nx failed on python3.6

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/ci.yml
python/graphscope/tests/minitest/test_min.py

Add python version matrix to nightly CI

---

docs/frequently_asked_questions.rst
docs/loading_graph.rst
docs/zh/frequently_asked_questions.rst

Give explanations of memory settings

---

charts/graphscope-store/README.md
docs/persistent_graph_store.rst

Update link of graphscope-store charts in README and rst.

Update graphscope-store chart link

---

python/graphscope/framework/app.py
python/graphscope/framework/dag.py

Fix failure of dag.add_op during running app_assets twice

---

coordinator/gscoordinator/launcher.py
coordinator/gscoordinator/utils.py
docs/analytics_engine.rst
docs/zh/analytics_engine.rst
python/graphscope/analytical/udf/wrapper.py
python/graphscope/framework/app.py
python/graphscope/framework/utils.py
python/graphscope/tests/unittest/test_udf_app.py
tutorials/5_writing_your_own_algorithms.ipynb
tutorials/zh/5_writing_your_own_algorithms.ipynb

Blocking by [Github Runner](https://github.com/actions/runner/issues/1546)
Fixes #1140 
Fixes #1136

Fixes engine crash by suffix timestamp to cython module name

---

interactive_engine/coordinator/pom.xml
interactive_engine/data_load_tools/pom.xml
interactive_engine/pom.xml

upgrade dep jars

---

analytical_engine/core/loader/arrow_fragment_loader.h
charts/graphscope/templates/NOTES.txt
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/io_utils.py
python/graphscope/analytical/app/java_app.py
python/graphscope/deploy/hosts/cluster.py
python/graphscope/framework/utils.py

- Prefix each loading bar with the current label, e.g. 'Loading vertex labels 'Person''
- Fix a bug when in k8s mode the progress bar is not streamed to client.
- Fix a typo in NOTES.txt in graphscope charts.
Fixes #1014

More information for loading progress bar

---

interactive_engine/groot/src/main/java/com/alibaba/graphscope/groot/coordinator/SnapshotManager.java
interactive_engine/groot/src/main/java/com/alibaba/graphscope/groot/wal/kafka/KafkaLogService.java

Fix kafka data retention

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/release.yml

Test release workflow

---

.github/config.yml

Use [Github Welcome Bot](https://github.com/apps/welcome)
Fixes

Add behavior bot for new issue and new pr

---

.github/workflows/build-graphscope-wheels-linux.yml
python/graphscope/nx/utils/compat.py

property can't not be copied through `copy_function`, add a `copy_property` to compat.py
Fixes

Add a `copy_property` to compat.py to copy properties of class

---

python/graphscope/deploy/kubernetes/cluster.py

Sometimes, support to open multiple ports coordinator pod is needed, such as launching an `sshd` service, or creating GIE gremlin frontend service with `HostNetwork=true`.
Fixes

Support setting ports of coordinator pod from GSCOORDINATOR_PORTS env

---

charts/graphscope/README.md
charts/graphscope/values.yaml

Increase the default resource in helm deployment

---

.github/workflows/ci.yml

Update codecov/codecov-action to v2.

---

.github/workflows/gae.yml
.github/workflows/networkx-forward-algo-nightly.yml
.github/workflows/nightly.yml
Makefile

Report codecover of nightly CI

---

python/graphscope/analytical/app/bfs.py
python/graphscope/analytical/app/sssp.py

Make the definition of src in sssp and bfs accurate

---

README.md
docs/conf.py

add edit_on_github button on docs.

---

docs/persistent_graph_store.rst

Fix a typo in persistent graph documentation.
Thanks wuyue for reporting that.

Typo of conn

---

.github/workflows/ci.yml
python/.coveragerc

Fix codecover

---

.github/workflows/networkx-forward-algo-nightly.yml
analytical_engine/apps/boundary/edge_boundary.h
analytical_engine/apps/boundary/node_boundary.h
analytical_engine/core/context/tensor_context.h
python/graphscope/framework/utils.py
python/graphscope/nx/algorithms/builtin.py
python/graphscope/nx/algorithms/tests/builtin/test_boundary.py
python/graphscope/nx/algorithms/tests/builtin/test_closeness_centrality.py
python/graphscope/nx/algorithms/tests/forward/centrality/test_betweenness_centrality.py
python/graphscope/nx/algorithms/tests/forward/centrality/test_degree_centrality.py
python/graphscope/nx/algorithms/tests/forward/shortest_paths/test_generic.py
python/graphscope/nx/algorithms/tests/forward/test_boundary.py
python/graphscope/nx/tests/classes/test_graph.py
python/graphscope/nx/tests/test_copy_on_write.py

Make forward nightly ci pass

---

charts/graphscope-store/templates/frontend/svc.yaml
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/io_utils.py

Fix log not fetched to client

---

interactive_engine/pom.xml

Upgrade log4j2 to 2.17.1
Fixes #1234

Upgrade log4j2

---

docs/frequently_asked_questions.rst

add a doc item in `frequently_asked_questions.rst` to solve Issue-1225 
Fixes #1225

Add documents about potential permission error when allocating PV in NFS.

---

.github/workflows/docs.yml

rm unrelated file from gh-pages

---

python/graphscope/framework/context.py

consistent label checking in client side

---

.github/workflows/docs.yml

Print diffs when failed to format java source code.

---

python/graphscope/client/connection.py
python/graphscope/interactive/query.py

The `DriverRemoteConnection` is leaked.
The failure can be reproduced when `traverse_source` involved.
N/A

Fixes the long-standing "Event loop is closed" issue.

---

python/graphscope/tests/kubernetes/test_with_mars.py

Quickfix: a syntax error.

---

k8s/Makefile
k8s/manylinux2014.Dockerfile

Fixed the auditwheel version to 5.0.0

---

coordinator/gscoordinator/builtin/app/.gs_conf.yaml
python/graphscope/analytical/app/clustering.py
python/graphscope/nx/algorithms/__init__.py
python/graphscope/nx/algorithms/builtin.py
python/graphscope/nx/algorithms/tests/builtin/test_cluster.py

Revise built-in clustering and replace forward with built-in
Fixes #1256

Revise built-in clustering and replace forward with built-in

---

analytical_engine/apps/centrality/eigenvector/eigenvector_centrality.h
analytical_engine/apps/centrality/eigenvector/eigenvector_centrality_context.h
analytical_engine/apps/centrality/katz/katz_centrality.h
analytical_engine/apps/centrality/katz/katz_centrality_context.h
analytical_engine/apps/hits/hits.h

Parallelize eigenvector_centrality and katz_centrality
Fixes #1257

Parallelize eigenvector_centrality and katz_centrality

---

.github/workflows/ci.yml
python/graphscope/nx/tests/test_copy_on_write.py

Fix the broken networkx ci

---

coordinator/setup.py
python/setup.py

Raise an meaningful error message when users are trying to install graphscope on Windows.
Fixes #1284.

Raise an error and tell users what to do on Windows.

---

.github/workflows/nightly.yml
python/graphscope/tests/unittest/test_app.py
python/graphscope/tests/unittest/test_context.py
python/graphscope/tests/unittest/test_download.py
python/graphscope/tests/unittest/test_session.py
python/graphscope/tests/unittest/test_udf_app.py

Only ASCII letters (of either case), '_' and digits are supported, and the first character must not be a digit.
Fixes

Fix the invalid identifier 'FULL-TEST-SUITE' in the environment variable

---

python/graphscope/tests/unittest/test_context.py

Fix: nightly CI was broken on test_error_on_selector case

---

python/graphscope/framework/graph_schema.py

Enhancement of the graph schema representation.

Print data type in graph schema

---

index.html
publications.html

Add publications

---

index.html
publications.html

Fix publication page

---

python/graphscope/framework/utils.py
python/graphscope/nx/classes/digraph.py
python/graphscope/nx/classes/graph.py
python/graphscope/nx/tests/test_transformation.py

[networkx] binding session from graphscope graph and fix bug

---

analytical_engine/core/io/property_parser.h
analytical_engine/core/server/command_detail.cc
analytical_engine/core/server/graphscope_service.cc
analytical_engine/core/server/graphscope_service.h
analytical_engine/core/server/rpc_utils.h
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/dag_manager.py
k8s/Makefile
proto/graphscope/proto/attr_value.proto
proto/graphscope/proto/coordinator_service.proto
proto/graphscope/proto/engine_service.proto
proto/graphscope/proto/message.proto
proto/graphscope/proto/types.proto
python/graphscope/client/rpc.py
python/graphscope/client/session.py
python/graphscope/client/utils.py
python/graphscope/framework/loader.py
python/graphscope/tests/conftest.py
python/graphscope/tests/unittest/test_app.py

Stream RunStepRequest of grpc to support loading graph from numpy/pandas more than 2GB

---

analytical_engine/core/grape_instance.cc
analytical_engine/core/server/dispatcher.cc
analytical_engine/core/server/dispatcher.h
analytical_engine/core/server/graphscope_service.cc
analytical_engine/core/server/graphscope_service.h
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/dag_manager.py
coordinator/gscoordinator/launcher.py
proto/graphscope/proto/coordinator_service.proto
proto/graphscope/proto/engine_service.proto
proto/graphscope/proto/message.proto
proto/graphscope/proto/op_def.proto
python/graphscope/client/rpc.py
python/graphscope/client/session.py
python/graphscope/client/utils.py

Stream RunStepResponse of grpc to support fetching result more than 2GB

---

.github/workflows/build-graphscope-wheels-linux.yml

Enable download metadata for repo 'appstream' of centos-8

---

analytical_engine/core/grape_instance.cc
python/graphscope/framework/dag_utils.py
python/graphscope/framework/utils.py
python/graphscope/nx/classes/dicts.py
python/graphscope/nx/classes/digraph.py
python/graphscope/nx/classes/graph.py
python/graphscope/nx/classes/reportviews.py
python/graphscope/nx/utils/misc.py
python/requirements.txt

- Use `LargeAttrValue` in modify operation and remove cache capacity
- include `orjson` to dumps json in python
- revise `reportview`
Fixes

Use `LargeAttrValue` in modify operation and dumps json with orjson

---

python/graphscope/tests/minitest/test_min.py

Support checkpoint related argument on trainer.
N/A

Bump up graph-learn package for checkpoint.

---

analytical_engine/core/fragment/arrow_projected_fragment.h
analytical_engine/core/launcher.cc

And a little enhancement to error messages.

Add timeout after launch vineyard to ensure we catched the error code corrected

---

research/engine/pegasus/benchmark/src/bin/service.rs
research/engine/pegasus/pegasus/src/operator/concise/any.rs

1. fix bug in any.rs caused by notify_end
2. fix compile error in benchmark
Fixes

fix notify_end bug in operator any

---

scripts/install_deps.sh

Revert #1338, and try to remove `binutils` installed by brew.

Revert "Make sure the $PATH could search /usr/bin first.

---

scripts/install_deps.sh

Fixes the CI failure on Mac (during build wheels).

Fixes PATH to not include $LLVM/bin to make sure the correct ranlib be found

---

python/graphscope/deploy/hosts/cluster.py
python/graphscope/framework/utils.py
scripts/install_deps.sh

Stop coordinator gracefully by accepting the signal from notebook restarted/stopped event

---

.github/workflows/build-graphscope-wheels-macos.yml
coordinator/setup.py
k8s/Makefile

Fixes CI failure on macOS

---

interactive_engine/assembly/bin/giectl

as titled.
This is a internal option that only for testing and benchmarking propose.

Add an env `USE_GAIA_ENGINE` to allow testing gaia from Python client.

---

blog/feed.xml
blog/index.html
blog/releasenotes/2022/03/06/release-notes-0.11.0.html
index.html

Add release note 0.11.0

---

.github/workflows/gaia.yml

The GAIA ci should be disabled months ago.

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/release.yml

Also tag latest when release new version

---

coordinator/gscoordinator/coordinator.py

as titled.
to prevent errors like

Catch unknown exceptions in gRPC handlers.

---

.github/workflows/ci.yml
.github/workflows/docs.yml
python/graphscope/analytical/udf/patch.py
python/graphscope/analytical/udf/utils.py
python/graphscope/dataset/io_utils.py
python/graphscope/nx/readwrite/tests/test_gml.py
tutorials/10_revisit_classification_on_citation_network_on_k8s.ipynb
tutorials/2_graph_manipulations_with_networkx_compatible_apis.ipynb
tutorials/3_loading_graphs.ipynb
tutorials/5_writing_your_own_algorithms.ipynb
tutorials/Welcome.ipynb
tutorials/zh/10_revisit_classification_on_citation_network_on_k8s.ipynb
tutorials/zh/2_graph_manipulations_with_networkx_compatible_apis.ipynb
tutorials/zh/3_loading_graphs.ipynb
tutorials/zh/5_writing_your_own_algorithms.ipynb
tutorials/zh/Welcome.ipynb

This PR upgrades the version of black, flake8 and isort, and updated the files accordingly.

Upgrade version of black/isort/flake8 formatter

---

coordinator/gscoordinator/coordinator.py
python/graphscope/client/utils.py
python/graphscope/learning/__init__.py

Disable noisy log inside gremlin-python, and fixes the hard-coded DEBUG.

---

interactive_engine/pom.xml
research/engine/pegasus/clients/java/client/pom.xml
research/query_service/gremlin/compiler/compiler-core/pom.xml
research/query_service/gremlin/compiler/pom.xml

upgrade proto to 3.18.0 && grpc to 1.42.1 of java-end under gaia and gie
Fixes #907

upgrade proto to 3.18.0 && grpc to 1.42.1

---

.github/workflows/ci.yml
.github/workflows/gae.yml
.github/workflows/gss.yml
.github/workflows/networkx-forward-algo-nightly.yml
analytical_engine/CMakeLists.txt
analytical_engine/core/context/tensor_context.h
analytical_engine/core/fragment/dynamic_fragment.h
analytical_engine/core/object/dynamic.cc
coordinator/gscoordinator/template/CMakeLists.template
coordinator/requirements.txt
interactive_engine/executor/runtime/native/CMakeLists.txt
k8s/Makefile
k8s/graphscope-dev.Dockerfile
k8s/graphscope-store.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/ubuntu/gsvineyard.Dockerfile
python/requirements.txt
scripts/install_deps.sh

The latest vineyardd is not compatible with the older client, as the support for reference counting.

Upgrade vineyard to v0.3.21.

---

.github/workflows/ci-dummy.yml
.github/workflows/ci.yml
.github/workflows/gae-dummy.yml
.github/workflows/gss-dummy.yml

Make sure all status are checkable in pull requests by following the guide from https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

Add dummy CI worflows to allow all status checkable.

---

.github/workflows/ci.yml
analytical_engine/core/fragment/dynamic_fragment.h
analytical_engine/core/fragment/dynamic_projected_fragment.h
analytical_engine/core/loader/arrow_to_dynamic_converter.h
analytical_engine/core/object/fragment_wrapper.h
python/graphscope/nx/algorithms/builtin.py
python/graphscope/nx/algorithms/tests/forward/test_cuts.py
python/graphscope/nx/algorithms/tests/forward/test_cycles.py
python/graphscope/nx/algorithms/tests/forward/test_lowest_common_ancestors.py
python/graphscope/nx/algorithms/tests/forward/test_threshold.py
python/graphscope/nx/algorithms/tests/forward/tree/test_mst.py

Fix networkx forward nightly ci

---

analytical_engine/java/giraph-on-grape/pom.xml

Remove unused but included dependencies in gae java
Fixes #1398

remove unused dependencies

---

.github/workflows/ci-dummy.yml
.github/workflows/ci.yml

Follow-up work for https://github.com/alibaba/GraphScope/pull/1402

Push if condition down to steps to allow it be checkable.

---

coordinator/setup.py

Try to fix nightly CI on macOS by packaging 'string_view' into wheel package

---

coordinator/gscoordinator/coordinator.py
coordinator/setup.py

Retry 3 times and then report failure during HeartBeat process

---

analytical_engine/apps/bfs/bfs_generic_context.h
analytical_engine/core/context/tensor_context.h
analytical_engine/core/utils/trivial_tensor.h
python/graphscope/framework/utils.py
python/graphscope/nx/algorithms/builtin.py

Support string tensor for tensor context

---

charts/graphscope/README.md

Add offline deployment doc for Helm

---

coordinator/gscoordinator/cluster.py
python/graphscope/client/session.py
python/graphscope/deploy/kubernetes/utils.py

Support launch GraphScope on K8s from inner-pod environment

---

coordinator/setup.py

Shrink gs-lib package to less than 100MB

---

analytical_engine/core/utils/msgpack_utils.h
scripts/install_deps.sh

[BugFix] Fix build wheel fail on mac

---

.github/workflows/build-graphscope-wheels-linux.yml
Makefile
charts/graphscope/templates/NOTES.txt
k8s/Makefile
k8s/jupyter.Dockerfile

Release the jupyter image in CI workflow

---

interactive_engine/executor/build.sh

delete intermediate files

---

Makefile

Add clean target to MakeFile to clean temporary files create from building

---

interactive_engine/common/src/main/java/com/alibaba/maxgraph/common/util/PkHashUtils.java
interactive_engine/executor/runtime/src/store/ffi.rs
interactive_engine/executor/runtime/src/store/groot/global_graph.rs
interactive_engine/executor/store/src/api/graph_partition.rs
interactive_engine/executor/store/src/db/graph/mod.rs
interactive_engine/groot-server/src/test/java/com/alibaba/maxgraph/tests/frontend/PkHashUtilsTest.java

groot support pk index

---

coordinator/setup.py

Move maxgraph*.jar into gs-jython package

---

analytical_engine/core/grape_instance.cc
coordinator/gscoordinator/utils.py
python/graphscope/client/rpc.py
python/graphscope/client/session.py
python/graphscope/framework/dag_utils.py
python/graphscope/nx/classes/graph.py

Add __del__ to nx.Graph to handle graph delete

---

.github/workflows/ci.yml
python/graphscope/nx/classes/graph.py
python/graphscope/nx/tests/test_transformation.py

Init the op of nx.Graph with incoming graphscope graph's op

---

analytical_engine/core/fragment/dynamic_fragment.h
analytical_engine/core/fragment/dynamic_projected_fragment.h

Fix remove nodes logic in `DynamicFragment`

---

k8s/actions-runner-controller/manylinux-ci.yaml
k8s/actions-runner-controller/ubuntu.yaml

Add a workflowJobs event to scaleUp triggers.
Ref actions-runner-controller/actions-runner-controller#922

Update ScaleUp trigger in HorizontalRunnerAutoscaler

---

k8s/Makefile

Upgrade vineyard to 0.4.1 in Makefile

---

coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/io_utils.py

This PR can stream progress bar contents from coordinator to client in k8s deployment.
Ref #1370

Display progress bar in k8s mode

---

.github/workflows/ci.yml
python/graphscope/nx/algorithms/tests/builtin/test_degree_connectivity.py
python/graphscope/nx/classes/digraph.py
python/graphscope/nx/classes/graph.py
python/graphscope/nx/convert.py
python/graphscope/nx/convert_matrix.py
python/requirements.txt

Upgrade NetworkX version from 2.6 to 2.8

---

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrGremlinServer.java

Listen to 0.0.0.0 in GAIA frontend

---

research/engine/pegasus/pegasus/src/lib.rs
research/engine/pegasus/server/examples/echo_service.rs
research/engine/pegasus/server/src/cluster/standalone.rs
research/engine/pegasus/server/src/rpc.rs

Add method startup to start rpc server without pegasus server. 
https://github.com/alibaba/GraphScope/issues/1590
https://github.com/alibaba/GraphScope/issues/1521

[GAIA/engine] fix empty SERVER when use method startup_with

---

k8s/graphscope.Dockerfile

Add ipython to the distributed docker image.

---

research/engine/pegasus/pegasus/src/lib.rs
research/engine/pegasus/server/examples/echo_service.rs
research/engine/pegasus/server/src/cluster/standalone.rs
research/engine/pegasus/server/src/rpc.rs

Merge latest version pegasus engine from gaia-x
https://github.com/alibaba/GraphScope/tree/gaia-x

[GAIA/engine] Merge latest version pegasus engine

---

scripts/install_deps.sh

[BugFix] Fix install `zetcd` error with `GO111MODULE="auto"` and remove the limitation of go version

---

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultParserFactory.java

return empty map if no properties in valueMap()

---

.github/workflows/ci.yml
.github/workflows/gae.yml
.github/workflows/networkx-forward-algo-nightly.yml
analytical_engine/CMakeLists.txt
coordinator/gscoordinator/template/CMakeLists.template
coordinator/requirements.txt
interactive_engine/executor/runtime/native/CMakeLists.txt
k8s/Makefile
k8s/actions-runner-controller/manylinux/Dockerfile
k8s/graphscope-dev.Dockerfile
k8s/graphscope-store.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/ubuntu/gsvineyard.Dockerfile
python/requirements.txt
scripts/install_deps.sh

Upgrade to v0.5.0 and re-enable the HDFS test.
N/A

Upgrade required vineyard version

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/ci.yml
coordinator/foo/__init__.py
coordinator/setup.py
k8s/Makefile
k8s/graphscope.Dockerfile

The size(100MB) of `gs-lib` package is not enough with the GAIA engine, so merge `gs-lib` and `gs-jython` into `graphscope` package(300MB limit).

Merge gs-jython and gs-lib into graphscope package

---

coordinator/gscoordinator/launcher.py
coordinator/gscoordinator/utils.py
interactive_engine/assembly/bin/giectl

as titled, to make debugging process easier.
N/A

Enhance the script finding process when launching GIE from locally build without installation

---

.github/workflows/ci.yml

Make CI filtering consistent between main and pull requests

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml

Disable publish the wheel package to the 'Test.Pypi'

---

interactive_engine/common/pom.xml
interactive_engine/coordinator/pom.xml
interactive_engine/data_load_tools/pom.xml
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/CommitDataCommand.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/DataCommand.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/IngestDataCommand.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/LoadTool.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/OSSFileObj.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/BytesRef.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/DataBuildMapperOdps.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/DataBuildPartitionerOdps.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/DataBuildReducerOdps.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/OfflineBuildOdps.java
interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/SstRecordWriter.java
interactive_engine/data_load_tools/src/main/scala/com/alibaba/maxgraph/dataload/LoadToolSpark.scala
interactive_engine/groot-server/pom.xml
interactive_engine/pom.xml
interactive_engine/sdk-common/pom.xml

GIE data build supports reading data from ODPS table, writing result to OSS file system, and data load supports reading data from OSS file system.
#1573

GIE bulk load supports ODPS table and OSS (#1573)

---

interactive_engine/groot-server/src/main/java/com/alibaba/maxgraph/servers/ir/IrServiceProducer.java
interactive_engine/sdk/pom.xml
interactive_engine/sdk/src/main/java/com/alibaba/graphscope/groot/sdk/MaxGraphClient.java
interactive_engine/sdk/src/main/java/org/apache/tinkerpop/gremlin/driver/CloseableGremlinClient.java
interactive_engine/sdk/src/main/resources/conf/sdk.yaml
interactive_engine/sdk/src/test/java/com/alibaba/graphscope/groot/sdk/GremlinClientTest.java
research/query_service/ir/compiler/conf/ir.compiler.properties
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/config/AuthConfig.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/auth/AuthManager.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/auth/AuthManagerReference.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/auth/DefaultAuthManager.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/auth/DefaultAuthenticator.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/auth/IrAuthenticationHandler.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/graph/RemoteGremlinConnection.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrGremlinServer.java
research/query_service/ir/compiler/src/main/resources/conf/gremlin-server.yaml

integrate gremlin query api into groot sdk and add authentication when querying 

---

research/query_service/ir/core/src/plan/ffi.rs
research/query_service/ir/core/src/plan/physical.rs
research/query_service/ir/integrated/tests/expand_test.rs
research/query_service/ir/proto/algebra.proto
research/query_service/ir/runtime/src/process/operator/flatmap/get_v.rs
research/query_service/ir/runtime/src/process/operator/flatmap/mod.rs
research/query_service/ir/runtime/src/process/operator/map/get_v.rs

[GAIA-IR] support bothV() in GAIA-IR

---

interactive_engine/groot/src/main/java/com/alibaba/graphscope/groot/coordinator/FileMetaStore.java

add crc to file meta store

---

.github/workflows/build-graphscope-wheels-linux.yml
Makefile
k8s/Makefile

Publish dataset image during release process

---

analytical_engine/CMakeLists.txt
analytical_engine/core/grape_engine.cc

Compatible with the latest API of GLOG

---

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/InterOpCollection.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/QueryParams.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/SubGraphAsUnionOp.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/SubGraphType.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/UnionOp.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkArg.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkByColumns.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkGraph.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkOutputProcessor.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SubGraphProjectProcessor.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/type/FfiVOpt.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultParserFactory.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/common/intermediate/operator/GetVOpTest.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/common/intermediate/operator/SubGraphAsUnionOpTest.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/EdgeVertexStep.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/SubGraphStepTest.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/NegativeEvalTest.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
research/query_service/ir/compiler/src/test/resources/get_bothV.json
research/query_service/ir/compiler/src/test/resources/subgraph.json

[GAIA-IR] support subgraph in ir compiler

---

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/AsNoneOp.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkOutputProcessor.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/SubGraphStepTest.java

[IR Compiler] represent identity() as As(None) to support subgraph

---

interactive_engine/ir-adaptor/src/test/java/com/alibaba/graphscope/ir/maxgraph/RemoteTestGraph.java
research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalPredicateVisitor.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/graph/RemoteTestGraph.java
research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/PredicateExprTransform.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/HasStepTest.java
research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java

…thout in ir_core
as titled.
Fixes #1650

[IR Compiler] support TextP.containing/TextP.notContaing as within/without in ir_core

---

interactive_engine/executor/runtime/build.rs
research/query_service/ir/v6d_ffi/build.rs
research/query_service/ir/v6d_ffi/src/read_ffi.rs
research/query_service/ir/v6d_ffi/src/write_ffi.rs

[GAIA-IR] Fix compiling warnings in v6d_ffi

---

interactive_engine/executor/store/src/api/mod.rs
interactive_engine/executor/store/src/api/property.rs
interactive_engine/executor/store/src/api/unwrap_or.rs

The derived `PartialOrd` of enum is not suitable, impl PartialOrd and some methods for Property, then format it.
None

impl PartialOrd and some methods for Property

---

.gitignore

add and item in .gitignore
None

ignore a Cargo.lock

---

research/query_service/ir/runtime/src/process/operator/accum/accum.rs
research/query_service/ir/runtime/src/process/operator/accum/accumulator.rs
research/query_service/ir/runtime/src/process/operator/sink/sink.rs
research/query_service/ir/runtime/src/process/record.rs

[GAIA-IR] Support sum() in GAIA-Runtime

---

coordinator/setup.py
interactive_engine/frontend/kill.sh
k8s/graphscope-dev.Dockerfile
k8s/manylinux2014.Dockerfile
k8s/ubuntu/gsruntime.Dockerfile
python/graphscope/client/session.py
scripts/install_deps.sh

Remove Zookeeper and zetcd related stuffs

---

interactive_engine/pom.xml
interactive_engine/sdk-common/pom.xml

Upgrade protoc version and use variable to replace hardcoded value

---

README.md

Add a TOC to the README.

---

research/engine/pegasus/pegasus/examples/logistic_regression_distributed.rs
research/engine/pegasus/pegasus/src/api/concise/map.rs
research/engine/pegasus/pegasus/src/data_plane/mod.rs
research/engine/pegasus/pegasus/src/operator/concise/map.rs
research/engine/pegasus/pegasus/src/operator/iteration/mod.rs
research/engine/pegasus/pegasus/tests/join_test.rs
research/query_service/ir/common/src/utils.rs
research/query_service/ir/integrated/tests/auxilia_test.rs
research/query_service/ir/integrated/tests/expand_test.rs
research/query_service/ir/integrated/tests/scan_test.rs
research/query_service/ir/runtime/src/assembly.rs
research/query_service/ir/runtime/src/process/operator/filter/mod.rs
research/query_service/ir/runtime/src/process/operator/flatmap/mod.rs
research/query_service/ir/runtime/src/process/operator/group/mod.rs
research/query_service/ir/runtime/src/process/operator/join/mod.rs
research/query_service/ir/runtime/src/process/operator/keyed/mod.rs
research/query_service/ir/runtime/src/process/operator/map/mod.rs
research/query_service/ir/runtime/src/process/operator/sink/mod.rs
research/query_service/ir/runtime/src/process/operator/sort/mod.rs
research/query_service/ir/runtime/src/process/operator/source.rs
research/query_service/ir/runtime/src/process/operator/subtask/mod.rs

[GIE-GAIA] Add Pegasus named apis, and add names for IR Operators

---

interactive_engine/executor/gaia_runtime/src/bin/gaia_executor.rs
python/graphscope/tests/kubernetes/test_demo_script.py
python/graphscope/tests/minitest/test_min.py
research/engine/pegasus/pegasus/tests/fold_test.rs

[GIE/TEST] Add back CI Test for subgraph()

---

research/dyn_type/src/object.rs
research/query_service/ir/runtime/src/process/operator/accum/accum.rs

[IR Runtime] support mean() in runtime

---

.github/workflows/build-graphscope-wheels-linux.yml
scripts/install_deps.sh

avoid mvn install fastffi twice

---

research/query_service/ir/v6d_ffi/src/native/CMakeLists.txt
research/query_service/ir/v6d_ffi/src/native/htap_loader.cc

Add a standalone graph loader to vineyard.

---

scripts/launch_cluster.py

Adapt the launch cluster script to latest AWS API

---

research/query_service/ir/v6d_ffi/src/native/htap_loader.cc

The CommSpec needs to be destructed first before `grape::FinalizeMPIComm()`.

Fixes the dtor error in the htap_loader.

---

research/engine/pegasus/clients/rust/client/src/builder.rs
research/engine/pegasus/server/proto/job_plan.proto
research/query_service/ir/core/src/plan/physical.rs
research/query_service/ir/integrated/tests/pathxd_test.rs
research/query_service/ir/runtime/src/assembly.rs

[GAIA-IR] Support `PathExpand` ranging from 0

---

k8s/manylinux2014-arm.Dockerfile

This PR add arm Dockerfile for graphscope-runtime.
Fixes #1811

add arm runtime dockerfile

---

docs/installation.rst

* Fix installation install word missing.

Fix docs words error

---

research/query_service/ir/v6d_ffi/src/native/README.md
research/query_service/ir/v6d_ffi/src/native/htap_loader.cc
research/query_service/ir/v6d_ffi/src/native/modern_graph.json

As titled.
Adding a readme for the usage as well.
Fixes #1895

Supporting reading from a config file in htap loader.

---

interactive_engine/executor/engine/pegasus/common/Cargo.toml
interactive_engine/executor/engine/pegasus/common/src/buffer.rs
interactive_engine/executor/engine/pegasus/common/src/queue/mod.rs
interactive_engine/executor/engine/pegasus/executor/Cargo.toml
interactive_engine/executor/engine/pegasus/executor/src/pending.rs
interactive_engine/executor/engine/pegasus/network/Cargo.toml
interactive_engine/executor/engine/pegasus/network/src/receive/net_rx.rs
interactive_engine/executor/engine/pegasus/pegasus/Cargo.toml

https://github.com/alibaba/GraphScope/security/dependabot/68

Resolve issues reported by dependent bot

---

analytical_engine/core/grape_instance.cc
analytical_engine/core/worker/default_property_worker.h
analytical_engine/core/worker/default_worker.h
analytical_engine/core/worker/parallel_property_worker.h
analytical_engine/core/worker/property_auto_worker.h
analytical_engine/frame/cython_app_frame.cc
analytical_engine/frame/cython_pie_app_frame.cc

Print the running time of each round of analytical engine

---

interactive_engine/pom.xml

Fix missing dependency of ir-compiler

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
coordinator/setup.py

**release version**: 0.15.0
**pre-release version**: 0.15.0a20220808
Fixes #1872

Support to pre-release GraphScope(image + wheel package) nightly with version like 'major.minor.alpha_patch'

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/release.yml
coordinator/gscoordinator/version.py
python/graphscope/config.py
python/graphscope/version.py

Change nightly image tag to 'nightly'

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml

Fixes nightly CI by overwrite the VERSION

---

interactive_engine/pom.xml
interactive_engine/sdk-common/pom.xml

upgrade protoc-gen-grpc-java version

---

interactive_engine/executor/ir/graph_proxy/Cargo.toml
interactive_engine/executor/ir/graph_proxy/src/adapters/exp_store/read_graph.rs
interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/read_graph.rs
interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/property.rs
interactive_engine/executor/ir/graph_proxy/src/utils/expr/eval.rs
interactive_engine/executor/ir/graph_proxy/src/utils/expr/eval_pred.rs
interactive_engine/executor/ir/runtime/Cargo.toml
interactive_engine/executor/ir/runtime/src/process/operator/group/group.rs
interactive_engine/executor/ir/runtime/src/process/operator/keyed/keyed.rs
interactive_engine/executor/ir/runtime/src/process/operator/map/project.rs
interactive_engine/executor/ir/runtime/src/process/operator/mod.rs
interactive_engine/executor/ir/runtime/src/process/operator/sink/sink_vineyard.rs
interactive_engine/executor/ir/runtime/src/process/operator/sort/sort.rs
interactive_engine/executor/store/global_query/src/apis/graph_partition.rs

As titled. `hashbrown::HashMap` brings about 10% acceleration in BI benchmark.
#1923

[GAIA Runtime] Use `hashbrown` for optimization

---

interactive_engine/compiler/src/test/java/com/alibaba/graphscope/integration/IrGremlinQueryTest.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/integration/IrGremlinTestSuite.java
interactive_engine/executor/ir/runtime/src/process/operator/accum/accumulator.rs

[Bug Fix] fix a bug in encode/decode in group

---

interactive_engine/assembly/src/conf/graphscope/log4j2.xml
interactive_engine/assembly/src/conf/groot/logback.xml
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/RpcBroadcastProcessor.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/processor/IrTestOpProcessor.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/intermediate/operator/DedupOpTest.java

[GAIA-IR] collect metrics from compiler to report query status, i.e. qps/rt/success

---

interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/read_graph.rs

fix a typo in ir

---

python/graphscope/framework/graph_schema.py
python/graphscope/tests/unittest/test_graph.py

Return primaryKey for vertex/edge property

---

publications.html

Add two ICDE papers on website

Add ICDE papers

---

.github/workflows/ci.yml
.github/workflows/gae.yml
.github/workflows/gaia.yml
.github/workflows/gss.yml
.github/workflows/networkx-forward-algo-nightly.yml
Makefile
analytical_engine/CMakeLists.txt
analytical_engine/frame/app_frame.cc
analytical_engine/frame/cython_app_frame.cc
analytical_engine/frame/cython_pie_app_frame.cc
coordinator/gscoordinator/template/CMakeLists.template
coordinator/requirements.txt
coordinator/setup.py
interactive_engine/assembly/src/bin/graphscope/giectl
k8s/Makefile
k8s/actions-runner-controller/manylinux/Dockerfile
k8s/graphscope-dev.Dockerfile
k8s/graphscope-store.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/manylinux2014-arm.Dockerfile
k8s/manylinux2014.Dockerfile
k8s/ubuntu/gsruntime.Dockerfile
k8s/ubuntu/gsvineyard.Dockerfile
python/pyproject.toml
python/requirements.txt
python/setup.py
scripts/install_deps.sh

upgrade vineyard to 0.8.2

---

.github/workflows/ci.yml
.github/workflows/gae.yml
.github/workflows/gaia.yml
.github/workflows/networkx-forward-algo-nightly.yml
analytical_engine/CMakeLists.txt
analytical_engine/core/grape_instance.cc
analytical_engine/core/loader/arrow_fragment_loader.h
analytical_engine/core/loader/arrow_to_dynamic_converter.h
analytical_engine/core/object/dynamic.h
analytical_engine/core/object/fragment_wrapper.h
analytical_engine/core/server/dispatcher.cc
analytical_engine/frame/property_graph_frame.cc
interactive_engine/executor/store/global_query/src/store_impl/v6d/native/graph_schema.cc
k8s/Makefile
k8s/actions-runner-controller/manylinux/Dockerfile
k8s/graphscope-dev.Dockerfile
k8s/graphscope-store.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/ubuntu/gsvineyard.Dockerfile
python/graphscope/nx/conftest.py
python/graphscope/tests/conftest.py
scripts/install_deps.sh

Upgrade required vineyard to v0.8.4.

---

scripts/install_deps.sh

Fixes CI on macOS

---

pre-commit/README.md

[Pre-commit Hook] Update README.md

---

coordinator/gscoordinator/template/CMakeLists.template

[Emergency Fix]Compile Property Graph with `ENABLE_JAVA_SDK` on needs `jni.h`

---

interactive_engine/compiler/src/main/antlr4/GremlinGS.g4
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/PredicateExprTransform.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/ConstantTest.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/IdLabelTest.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java

[GIE-IR] support more patterns of project, i.e. id(), label(), constant()

---

analytical_engine/java/README.md
docs/analytics_engine.rst
docs/zh/analytics_engine.rst

Update GAE Java Doc

---

.github/workflows/gae.yml
.github/workflows/networkx-forward-algo-nightly.yml
analytical_engine/CMakeLists.txt
coordinator/gscoordinator/builtin/app/.gs_conf.yaml
k8s/Makefile
k8s/actions-runner-controller/manylinux/Dockerfile
k8s/graphscope-dev.Dockerfile
k8s/graphscope-store.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/ubuntu/gsvineyard.Dockerfile
python/graphscope/tests/conftest.py
python/graphscope/tests/unittest/test_app.py
python/graphscope/tests/unittest/test_graph.py
scripts/install_deps.sh

Change builtin apps(bfs,sssp,pagerank) to parallel version

---

analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/parallel/MessageInBuffer.java

Fix Bug in GAE Java SDK `GetMessage`.

[GAE-Java] Fix GetMessage bug

---

analytical_engine/java/grape-demo/pom.xml
analytical_engine/java/pom.xml

Upgrade `log4j` to a safe version.

[GAE-Java] Upgrade log4j

---

coordinator/gscoordinator/cluster.py
coordinator/gscoordinator/coordinator.py
python/graphscope/client/session.py
python/graphscope/config.py
python/graphscope/deploy/kubernetes/cluster.py
python/graphscope/deploy/kubernetes/resource_builder.py

Add nodeselector for coordinator, etcd, and engine pods.
Fixes #1839

Add nodeselector arguments to control where the pod will be launched

---

analytical_engine/CMakeLists.txt
analytical_engine/core/error.h
analytical_engine/core/fragment/arrow_projected_fragment_mapper.h
analytical_engine/core/server/dispatcher.cc
analytical_engine/frame/app_frame.cc
analytical_engine/frame/cython_app_frame.cc
analytical_engine/frame/cython_pie_app_frame.cc
analytical_engine/frame/project_frame.cc
analytical_engine/frame/property_graph_frame.cc
analytical_engine/graphscope-analytical-config.in.cmake
coordinator/gscoordinator/template/CMakeLists.template
coordinator/gscoordinator/utils.py
k8s/graphscope.Dockerfile

Add a macro to catch possible exceptions in graph frames and app frames, and introduce a `GRAPHSCOPE_ANALYTICAL_DEBUG={"0","1"}` for easing the debugging process.
N/A

Enhance the error handling in frames

---

.github/workflows/ci.yml
.github/workflows/gae.yml
.github/workflows/networkx-forward-algo-nightly.yml
analytical_engine/CMakeLists.txt
k8s/Makefile
k8s/actions-runner-controller/manylinux/Dockerfile
k8s/graphscope-dev.Dockerfile
k8s/graphscope-store.Dockerfile
k8s/gsvineyard.Dockerfile
k8s/ubuntu/gsvineyard.Dockerfile
scripts/install_deps.sh

as titled, prepare for upgrade vineyard to latest release.
N/A

Test against the latest libgrape-lite and vineyard

---

interactive_engine/executor/store/groot/Cargo.toml

upgrade rocksdb-rust to 0.19.0

---

interactive_engine/executor/assembly/v6d/src/bin/gaia_executor.rs

[Bug Fix] Ensure all servers ready when starting gaia_executor on Vineyard

---

.github/workflows/ci.yml
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/op_executor.py
k8s/graphscope.Dockerfile

Fixes #2170
Fixes #2173
Fixes #2176

Enable HDFS tests in CI.

---

.github/workflows/ci.yml
Makefile
k8s/graphscope-store.Dockerfile
scripts/install_deps.sh

See failures in
- https://github.com/alibaba/GraphScope/actions/runs/3388527191/jobs/5630615603
- https://github.com/alibaba/GraphScope/actions/runs/3388527133/jobs/5630615204
- https://github.com/alibaba/GraphScope/actions/runs/3388531938/jobs/5630625688
N/A

Fixes failures in nightly CI

---

docs/frequently_asked_questions.rst
docs/zh/frequently_asked_questions.rst

add a new FAQ related to network proxy setting
Fixes #2203

[new FAQ] add network proxy related FAQ

---

.github/workflows/build-graphscope-wheels-macos.yml
Makefile
analytical_engine/CMakeLists.txt
k8s/Makefile

Fixes nightly CI on macOS

---

.github/workflows/ci.yml

It is quiet strange that cpplint is not deployed in our CI ...
N/A

Enable cpplint in CI

---

.github/workflows/docs.yml

For PRs changing docs, generate a preview URL for checking.
credit to surge.sh
Fixes N/A

add docs revision preview in CI

---

.github/workflows/release.yml

Fix release graphscope-store image in CI

---

interactive_engine/executor/store/exp_store/data/ldbc_metadata.json
interactive_engine/executor/store/exp_store/src/graph_db/csr_topo.rs

[GIE/Exp-Store] Optimize memory usage in loading graph data into `MutTopo`.

---

interactive_engine/executor/engine/pegasus/executor/src/reactor.rs
interactive_engine/executor/engine/pegasus/pegasus/src/communication/decorator/exchange.rs

[GIE/engine] Bug fix: fix bug in flow control;

---

.github/workflows/ci.yml
.github/workflows/gae.yml
.github/workflows/networkx-forward-algo-nightly.yml
analytical_engine/CMakeLists.txt
coordinator/setup.py
docs/developer_guide.rst
docs/zh/developer_guide.rst
k8s/Makefile
k8s/actions-runner-controller/manylinux/Dockerfile
k8s/actions-runner-controller/manylinux/Makefile
k8s/build_scripts/build_patchelf.sh
k8s/build_scripts/build_vineyard.sh
k8s/dockerfiles/analytical.Dockerfile
k8s/dockerfiles/coordinator.Dockerfile
k8s/dockerfiles/graphscope-dev.Dockerfile
k8s/dockerfiles/graphscope-store.Dockerfile
k8s/dockerfiles/interactive-experimental.Dockerfile
k8s/dockerfiles/interactive.Dockerfile
k8s/dockerfiles/learning.Dockerfile
k8s/dockerfiles/vineyard-dev.Dockerfile
k8s/dockerfiles/vineyard-runtime.Dockerfile
k8s/internal/Makefile
k8s/internal/graphscope.Dockerfile
scripts/install_deps.sh

as titled.
This pull request also tweak the `k8s/Makefile` a bit to make the hard-coded vineyard verison lesser and let the upgrade progress easier.
n/a

Upgrade vineyard to v0.11.0

---

.github/workflows/docs.yml

[docs CI] Choose stable/latest tag correctly by fixing the missing `$` in bash script

---

.dockerignore
.gitignore
coordinator/gscoordinator/op_executor.py
coordinator/requirements.txt
python/graphscope/framework/dag_utils.py
python/graphscope/proto/types.proto

Add a write options to enable adding header row to OSS output

---

analytical_engine/java/grape-demo/pom.xml
analytical_engine/java/grape-graphx/pom.xml
analytical_engine/java/grape-graphx/src/main/scala/com/alibaba/graphscope/graphx/GSClientWrapper.scala
analytical_engine/java/grape-jdk/pom.xml
analytical_engine/java/pom.xml

Fix `grape-demo` shaded dependencies issue

---

.github/workflows/build-graphscope-images-linux.yml
.github/workflows/build-graphscope-wheels-linux.yml

See https://github.com/alibaba/GraphScope/actions/runs/3752077410

fix nightly CI and remove redundant comments

---

.github/workflows/k8s-ci-dummy.yml
.github/workflows/k8s-ci.yml
.github/workflows/local-ci-dummy.yml
.github/workflows/local-ci.yml

[WIP] Fixes CI

---

charts/graphscope/templates/coordinator.yaml
coordinator/gscoordinator/kubernetes_launcher.py

The previous method was too tricky via https://github.com/alibaba/GraphScope/pull/2350, and I think the recommended way is adding ownerreferences to add subresources created by the coordinator.

Add ownerreferences to all subresources created by coordinator

---

coordinator/gscoordinator/coordinator.py
coordinator/requirements.txt

See also: https://github.com/alibaba/GraphScope/security/dependabot/90

Fixes the dependentbot warnings in coordinator

---

interactive_engine/executor/engine/pegasus/pegasus/src/communication/decorator/exchange.rs

Fix bug that operators can't finish correctly and cause blocking sometimes

[pegasus] fix operator blocking

---

analytical_engine/java/pom.xml

[GAE-Java] Remove some dummy java dep in gae java

---

docs/performance_and_benchmark.md

[Benchmark Doc] add gae benchmark results in doc

---

docs/graphscope_for_graph_analytics.md
docs/graphscope_for_learning.md

Fix images not shown in docs.

---

python/requirements.txt
python/setup.py

- Find header under GRAPHSCOPE_HOME for learning
- Add minimum requirement for Kubernetes

Find header under GRAPHSCOPE_HOME for learning

---

docs/index.rst

Fix bugs in docs

---

charts/graphscope/templates/coordinator.yaml

fix helm installation with default configurations

---

docs/frag_intro.md

Add intro for fragment

---

analytical_engine/java/pom.xml
charts/graphscope-store/Chart.yaml
charts/graphscope/Chart.yaml

See also: https://github.com/alibaba/GraphScope/pull/2453

Prerelease v0.20.0: POMs and helm charts.

---

docs/analytical_engine/builtin_algorithms.md
docs/analytical_engine/customized_algorithms.md
docs/analytical_engine/design_of_gae.md
docs/analytical_engine/faqs.md
docs/analytical_engine/flash.md
docs/analytical_engine/getting_started.md
docs/analytical_engine/guide_and_examples.md
docs/analytical_engine/ingress.md
docs/analytical_engine/networkx_compatibility.md
docs/analytical_engine/overview_and_architecture.md
docs/analytical_engine/performance_tuning.md
docs/analytical_engine/programming_model_pie.md
docs/analytical_engine/tutorial_dev_algo_cpp_flash.md
docs/analytical_engine/tutorial_dev_algo_cpp_pie.md
docs/analytical_engine/tutorial_dev_algo_java.md
docs/analytical_engine/tutorial_dev_algo_python.md
docs/analytical_engine/tutorial_networkx_algorithms.md
docs/analytical_engine/tutorial_networkx_operations.md
docs/analytical_engine/tutorial_run_builtin_algo.md
docs/analytical_engine/tutorial_run_giraph_apps.md
docs/analytical_engine/tutorial_run_graphx_apps.md
docs/analytical_engine/vertex_centric_models.md
docs/index.rst

reorg docs for analytical engine.

---

python/graphscope/analytical/app/wcc.py
python/graphscope/framework/app.py
python/graphscope/tests/conftest.py
python/graphscope/tests/unittest/test_app.py
python/graphscope/tests/unittest/test_create_graph.py
python/graphscope/tests/unittest/test_graph.py

Improve the error message as well.
Fixes #2484

Reject directed graphs in WCC algorithms

---

README-zh.md
README.md
docs/zh/deployment.rst
docs/zh/developer_guide.rst

Install dependencies functionality has been moved to gs from install_deps.sh.

use gs to install dependencies

---

python/graphscope/client/utils.py
python/requirements-dev.txt
python/requirements.txt

Be nice in traceback and errors

---

.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/networkx-forward-algo-nightly.yml
.github/workflows/nightly.yml
coordinator/setup.py
k8s/dockerfiles/graphscope-dev.Dockerfile
k8s/internal/Makefile
python/graphscope/tests/minitest/test_min.py

And try to fix network forward algo test.
And try to fix openmpi on brew has released a new version, which caused version incompatibility with v6d v0.12.2

fix mac python test

---

docs/overview/design_of_graphscope.md

Fix docs images not shown 

---

docs/analytical_engine/guide_and_examples.md

Fix GAE catalog

---

docs/overview/design_of_graphscope.md
docs/overview/getting_started.md
docs/overview/graph_analytics_workloads.md
docs/overview/intro.md

proofread and enhanced by cursor.so/chatgpt.

---

interactive_engine/groot-server/pom.xml

To address security issue in https://github.com/alibaba/GraphScope/security/dependabot/91

bump up scala version

---

docs/overview/graph_learning_workloads.md

As titled, partially commit for #2522

Add GLE workload doc

---

docs/analytical_engine/dev_and_test.md
docs/deployment/deploy_graphscope_on_self_managed_k8s.md
docs/storage_engine/groot.md

Add document for groot

---

docs/how_to_load_graphs.md

tips for reduce memory consumption

---

docs/storage_engine/grin.md

Add grin documents under storage engine section
#2522

[Doc] add grin docs under storage engine

---

charts/gie-standalone/templates/store/statefulset.yaml
k8s/.dockerignore
k8s/dockerfiles/interactive.Dockerfile
k8s/dockerfiles/vineyard-runtime.Dockerfile
k8s/utils/graphctl.py

Support reading HDFS files for GIE standalone deployment

---

docs/index.rst
docs/learning_engine/guide_and_examples.md
docs/learning_engine/tutorial_node_classification_k8s.md
docs/learning_engine/tuttorial_node_classification_local.md

1. Add guide and examples for GLE
2. Fix the GLE doc index
3. Update getting started 
#2522

[Doc] Add guide and examples for GLE

---

docs/analytical_engine/deployment.md

doc: add deployment with gae only

---

gs

1. install patchelf from source to avoid the version difference across distributions
2. add export CMAKE_PREFIX_PATH to correctly find libgrape-lite and gar

add export CMAKE_PREFIX_PATH

---

docs/frequently_asked_questions.rst

Fixes https://github.com/alibaba/GraphScope/discussions/2620#discussioncomment-5658927

Document how to install scipy on M1 MacOS.

---

python/graphscope/analytical/app/java_app.py
python/graphscope/client/session.py
python/graphscope/client/utils.py
python/graphscope/config.py
python/graphscope/dataset/io_utils.py
python/graphscope/deploy/kubernetes/utils.py
python/graphscope/framework/graph.py
python/setup.cfg

as titled, for better user experiences.
This pull request fixes some flake8 logging warnings as well.
Fixes #2672

Use different default value for vineyard_shared_memory on k8s and local

---

.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/gae.yml
.github/workflows/networkx-forward-algo-nightly.yml
.github/workflows/nightly.yml
analytical_engine/java/grape-runtime/CMakeLists.txt
coordinator/requirements.txt
k8s/Makefile
k8s/actions-runner-controller/manylinux/Makefile
k8s/internal/Makefile
scripts/install_deps.sh

Bump up vineyard to v0.14.5

---

coordinator/gscoordinator/coordinator.py

Display stderr logs as expected on K8s

---

python/graphscope/deploy/kubernetes/resource_builder.py
python/graphscope/framework/graph_builder.py
python/pyproject.toml
python/setup.cfg

Fixes the initialization of paramters in load_from()

---

.github/workflows/build-graphscope-wheels-linux.yml

See also:
- https://github.com/alibaba/GraphScope/pull/2676
- https://github.com/alibaba/GraphScope/actions/runs/4918614416/jobs/8785174492

Fixes the linux wheel install prefix

---

.github/workflows/gss.yml
.github/workflows/k8s-ci.yml

As titled.
An optimization for https://github.com/alibaba/GraphScope/pull/2683

Introduce the new version of kubernetes log exporter for dumping logs during a period of time such as pytest

---

publications.html

Add PDF links for ICDE 2023 in Publication pages.

---

.github/workflows/build-graphscope-wheels-linux.yml

Rework https://github.com/alibaba/GraphScope/commit/e447cd5cda416c5c7384b153360f9e2952dc0daf

Fixes the installation prefix for nightly linux CI

---

coordinator/gscoordinator/op_executor.py

refine retry logic to exponential backoff

---

coordinator/gscoordinator/local_launcher.py
coordinator/gscoordinator/op_executor.py
coordinator/gscoordinator/utils.py
python/graphscope/framework/utils.py

use javac to find the version of java

---

analytical_engine/core/grape_engine.cc

Related to the help message part of #2749

Make grape_engine help message more friendly

---

.github/workflows/build-graphscope-images-linux.yml
.github/workflows/k8s-ci.yml
Makefile

Cleanup space in CI

---

gs

Support to install deps for Alibaba Cloud Linux in the gs bash utility

---

docs/learning_engine/dev_and_test.md

Complete the build and install details of learning engine

[GLE Doc] complete the build and install details of learning engine

---

analytical_engine/core/grape_engine.cc

Fixes the GAE fork issue with openmpi

---

docs/overview/getting_started.md
docs/overview/glossary.md

[GIE/docs] Add gie glossary and quick start

---

coordinator/gscoordinator/kubernetes_launcher.py

Add coordinator as the Ownerreferces of frontend deployment.

---

analytical_engine/java/pom.xml

[GAE-Java] Use maven-flatten-plugin to replace revision property for locally build&install

---

blog/feed.xml
blog/index.html
blog/page2/index.html

Pages update auto built from graphscope/web, commit graphscope/web@1b2f390

Fixes the paginator display of blogs 

---

.github/workflows/docs.yml
.github/workflows/gae.yml
.github/workflows/gaia.yml
.github/workflows/gss.yml
.github/workflows/k8s-ci.yml
.github/workflows/local-ci.yml
.github/workflows/pegasus.yml

Allow triggering CIs manually  to update code Coverage
Fixes #1710

Allow triggering workflow dispatch event for CIs

---

blog/feed.xml
blog/index.html
blog/tech/2023/06/11/How-to-Deploy-GraphScope-by-Helm-on-Kubernetes.html
sitemap.txt

Pages update auto built from graphscope/web, commit c74b0bf

---

docs/interactive_engine/supported_gremlin_steps.md

[GIE Doc] Update Doc for `PathExpand` Step Usage in GIE

---

analytical_engine/core/launcher.cc
coordinator/gscoordinator/local_launcher.py
python/graphscope/nx/classes/graph.py

Use local metadata backend to avoid the requirements of etcd for local sessions

---

.github/workflows/gae.yml
.github/workflows/k8s-ci.yml
.github/workflows/local-ci.yml
.github/workflows/networkx-forward-algo-nightly.yml
.github/workflows/nightly.yml
python/setup.py

See also commit 612bd7f090f537b4d3efc37a896263421cffb5f1.

Fixes the misuse of "continue-on-error" and "fail_ci_if_error".

---

analytical_engine/java/grape-demo/src/main/java/com/alibaba/graphscope/example/wcc/WCC.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/ds/Bitset.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/ds/VertexSet.java
analytical_engine/java/grape-runtime/src/main/java/com/alibaba/graphscope/annotation/AnnotationInvoker.java

[GAE-Java] Use `FFI-bitset` rather than java BitSet for VertexSet backend

---

coordinator/requirements.txt
python/requirements.txt

fix vineyard version to 0.15.0

---

.github/workflows/docs.yml

hotfix: pull_request_target issue.

---

docs/overview/getting_started.md

Add GLE quick start example in the overview getting started page

---

.github/workflows/gss.yml
charts/graphscope-store/values.yaml
python/graphscope/tests/kubernetes/test_demo_script.py

1. Drop unnecessary artifact uploading
2. Drop unnecessary tests to avoid timeout

Refine CI process

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/GraphServer.java

[GIE Compiler] Set Cypher Query Timeout from System Configurations

---

interactive_engine/executor/ir/proto/physical.proto
interactive_engine/executor/ir/runtime/src/process/operator/accum/accum.rs

Introduce Aggregate function `First` in to GroupBy operator.
Related issue: #2992

[GIE] Introduce Aggregate.First proto definition

---

interactive_engine/executor/ir/runtime/src/router.rs

As titled.
After refine the `DefaultRouter` implementation, we can see that all workers are doing the computation, which also brings about 20% acceleration in total time cost. 
```
job:  1
worker: 0
computation cost is 417248.23 ms, and the ratio of computation cost to total cost is 0.85
worker: 1
computation cost is 434071.14 ms, and the ratio of computation cost to total cost is 0.88
worker: 2
computation cost is 430534.29 ms, and the ratio of computation cost to total cost is 0.88
worker: 3
computation cost is 434731.57 ms, and the ratio of computation cost to total cost is 0.88
...
```
Fixes #2993

[GIE] Fix unbalanced data routing in DefaultRouter in GIE

---

blog/feed.xml
blog/index.html
blog/page2/index.html
blog/page3/index.html
blog/releasenotes/2023/07/07/release-notes-0.23.0.html
index.html
sitemap.txt

Add Release note 0.23.0

---

.github/workflows/flex.yml
flex/Dockerfile

update libgrape-lite's commit id in Flex dockerfile

---

flex/Dockerfile

Use a specific tag for `Hiactor` and `libgrape-lite` for flex' Dockerfile build.
Fixes #3018

[Flex] Update flex dockerfile

---

k8s/internal/Makefile

See: https://github.com/alibaba/GraphScope/actions/runs/5579551962

Fixes the Python version detection in MacOS CI

---

interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/OfflineBuild.java
interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/OfflineBuildOdps.java
interactive_engine/pom.xml

Fixed jdk_1.8 version for data-loading-tool

---

README.md

Update README.md to reflect GraphScope Flex

---

README.md

doc: Update README.md by adding latest news section

---

analytical_engine/core/fragment/arrow_flattened_fragment.h
analytical_engine/test/app_tests.sh
analytical_engine/test/run_app.h
coordinator/gscoordinator/builtin/app/.gs_conf.yaml
python/graphscope/analytical/app/__init__.py
python/graphscope/analytical/app/voterank.py
python/graphscope/analytical/app/wcc.py
python/graphscope/nx/algorithms/builtin.py
python/graphscope/tests/unittest/test_app.py

Fixes the implementation of adjlist in flatten fragment

---

.github/workflows/build-graphscope-wheels-macos.yml

Fixes: https://github.com/alibaba/GraphScope/actions/runs/5718580144

ci: address the failure of packaging graphscope wheels on MacOS

---

charts/graphscope-store/templates/configmap.yaml

Add config to enable multiple frontend support in groot deployment

---

.github/workflows/build-graphscope-dev-images.yml

ci: fixes workflow of building GraphScope wheel image

---

.github/workflows/pr-check.yml

Add `flex` in pr-check' scope list.

ci(flex): Add flex in pr-check's scopes

---

analytical_engine/apps/python_pie/export.h
analytical_engine/core/app/pregel/export.h
docs/analytical_engine/customized_algorithms.md
python/graphscope/analytical/udf/compile.py
python/graphscope/nx/classes/graph.py
python/graphscope/tests/unittest/test_udf_app.py

feat(analytical): Enable cython app on local vertex map graph

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/suite/standard/IrGremlinQueryTest.java
interactive_engine/executor/ir/runtime/src/process/operator/accum/accum.rs

fix(interactive): fix unexpected results for some group().by() queries

---

interactive_engine/executor/engine/pegasus/pegasus/src/communication/decorator/exchange.rs
interactive_engine/executor/engine/pegasus/pegasus/src/operator/concise/count.rs
interactive_engine/executor/engine/pegasus/pegasus/src/progress.rs
interactive_engine/executor/engine/pegasus/pegasus/tests/fold_test.rs

Fix communication bug in `count` operator. Add corresponding unit test.
Fixes
https://github.com/alibaba/GraphScope/issues/3058

fix(interactive): fix a bug of count operator

---

docs/interactive_engine/getting_started.md

fix(interactive): Fix Examples in GIE Doc

---

interactive_engine/executor/engine/pegasus/pegasus/src/operator/concise/keyed/join.rs
interactive_engine/executor/engine/pegasus/pegasus/tests/join_test.rs
interactive_engine/executor/ir/runtime/src/assembly.rs

Fixes
https://github.com/alibaba/GraphScope/issues/3117

refactor(interactive): Join operator in pegasus will repartition stream before join 

---

.github/workflows/flex.yml
flex/storages/rt_mutable_graph/modern_graph/modern_graph.yaml
flex/storages/rt_mutable_graph/schema.cc

Some small modifications on graph schema definition to fix the GIE compiler.

refactor(flex): Small modifications to the graph schema to fit the GIE compiler.

---

.gitmodules
Makefile
python/graphscope/learning/graphlearn_torch
python/setup.py

Related Issue: https://github.com/alibaba/GraphScope/issues/3097

[build(learning)] integrate graphlearn-for-pytorch in graphscope library

---

.github/workflows/build-graphscope-wheels-macos.yml
python/setup.py

ci: fixes failure in building GraphScope wheel package

---

.github/workflows/build-graphscope-wheels-linux.yml

Differentiating between arm64 and x86 wheel's name

---

.github/workflows/build-graphscope-images-linux.yml
.github/workflows/release.yml

Added arm support for engines
issue #2644

ci: Support to build GraphScope Images(both x86 and arm64) in CI workflow

---

.github/workflows/build-graphscope-images-linux.yml
.github/workflows/release.yml

ci: fixes failure of building images by adding actions/checkout step

---

blog/feed.xml
blog/index.html
blog/page2/index.html
blog/page3/index.html
blog/releasenotes/2023/09/05/release-notes-0.24.0.html
index.html
sitemap.txt

doc(blog): Add release note 0.24.0

---

python/graphscope/config.py

Fixes https://github.com/alibaba/GraphScope/actions/runs/6076867483/job/16485596230

fix(python): fix default field in py311

---

.github/workflows/pr-check.yml

add doc requirement for refactor.

ci: Update pr-check.yml

---

coordinator/gscoordinator/launch_graphlearn_torch.py
examples/local_glt.py

The dynamic world size feature in server-client mode has been implemented in GLT, and this PR is used to update and use this feature.

Update GLT using dynamic world size feature

---

docs/learning_engine/guide_and_examples.md
docs/learning_engine/tutorial_node_classification_pyg_local.md

Add a tutorial for training PyG model.

Add a tutorial for training PyG model

---

docs/learning_engine/guide_and_examples.md
docs/learning_engine/tutorial_node_classification_pyg_local.md
python/setup.cfg

Skip GLTorch link check

---

.github/workflows/k8s-ci.yml
coordinator/setup.py
python/pyproject.toml
python/setup.py

See CI failures in:
- https://github.com/alibaba/GraphScope/actions/runs/6248880943/job/16964523349

ci: fixes the Python dependency error in CI

---

.github/workflows/k8s-ci.yml
charts/graphscope/values.yaml
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/SnapshotCache.java
interactive_engine/tests/function_test.sh
python/graphscope/config.py
python/graphscope/tests/kubernetes/test_demo_script.py
python/setup.py

chore: Increase the disk size of minikube cluster

---

charts/graphscope-store/values.yaml
interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/IngestorConfig.java
interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/StoreConfig.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/ingestor/BatchSender.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/SnapshotSortQueue.java

To cope with cases where there are too many ddl batches.

fix(interactive): Increase ingestor queue buffer size

---

k8s/internal/Makefile

Fixes https://github.com/alibaba/GraphScope/actions/runs/6505103462/job/17668168357

ci: increasing the default timeout setting for pip install

---

.github/free-disk-space.sh
.github/workflows/build-graphscope-images-linux.yml
.github/workflows/build-graphscope-wheels-linux.yml
Makefile

Fixes https://github.com/alibaba/GraphScope/actions/runs/6538086753/job/17753285181

ci: free disk spaces and install correct torch without download many from pypi

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java

Support using `''` to check connections in gremlin.
Fixes

fix(interactive): Ad-hoc Handling for Connection Validation in Gremlin

---

interactive_engine/executor/ir/runtime/src/assembly.rs

fix(interactive): fix parallel scan in GIE

---

interactive_engine/assembly/src/conf/groot/logback.xml
interactive_engine/executor/check_format.sh
interactive_engine/executor/store/groot/src/db/graph/entity.rs
interactive_engine/executor/store/groot/src/db/graph/iter.rs
interactive_engine/executor/store/groot/src/db/graph/store.rs
interactive_engine/executor/store/groot/src/db/storage/mod.rs

Part of https://github.com/alibaba/GraphScope/issues/1854

fix(interactive): implement count with efficiency

---

interactive_engine/executor/ir/core/src/plan/ffi.rs

fix(interactive): fix a memory leak bug in IR Core

---

flex/utils/id_indexer.h
flex/utils/mmap_array.h

support resize in LFIndexer
Fixes

feat(flex): support LFIndexer resize

---

flex/storages/rt_mutable_graph/loader/csv_fragment_loader.cc
flex/storages/rt_mutable_graph/loader/csv_fragment_loader.h

Remove/merge some redundant/duplicated code.

refactor(interactive): Refactor CSVFragmentLoader to remove redundant code

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/ArgVariable.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/PredicateExprTransformFactory.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransform.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransformFactory.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/alias/AliasManager.java

fix(interactive): Remove Unnecessary JNA Structure Creation to Save Memory Consumption

---

flex/resources/queries/examples/store_procedure/Q1.1.cypher
flex/resources/queries/examples/store_procedure/Q1.2.cypher
flex/resources/queries/examples/store_procedure/Q1.3.cypher
flex/resources/queries/examples/store_procedure/Q1.4.cypher
flex/resources/queries/examples/store_procedure/Q2.1.cypher
flex/resources/queries/examples/store_procedure/Q2.2.cypher
flex/resources/queries/examples/store_procedure/Q2.3.cypher
flex/resources/queries/examples/store_procedure/Q2.4.cypher
flex/resources/queries/examples/store_procedure/Q3.1.cypher
flex/resources/queries/examples/store_procedure/Q3.2.cypher
flex/resources/queries/examples/store_procedure/Q3.3.cypher
flex/resources/queries/examples/store_procedure/Q3.4.cypher

fix(interactive): add some optimizer microbenchmark queries

---

docs/flex/interactive/configuration.md
docs/flex/interactive/custom_graph_data.md
docs/flex/interactive/data_model.md
docs/flex/interactive/development/admin_service.md

Fix the documentation to the latest interactive.

fix(interactive): Fix documentation for interactive.

---

.github/workflows/flex.yml
flex/CMakeLists.txt
flex/engines/graph_db/database/graph_db.cc
flex/engines/graph_db/database/graph_db.h
flex/engines/graph_db/database/update_transaction.cc
flex/storages/rt_mutable_graph/dual_csr.h
flex/storages/rt_mutable_graph/file_names.h
flex/storages/rt_mutable_graph/mutable_csr.h
flex/storages/rt_mutable_graph/mutable_property_fragment.cc
flex/tests/rt_mutable_graph/test_acid.cc
flex/tests/rt_mutable_graph/test_empty_graph.cc
flex/utils/id_indexer.h
flex/utils/mmap_array.h

fix(interactive): Pass acid

---

python/graphscope/client/session.py
python/graphscope/tests/minitest/test_min.py

Seems there are some changes about the eid generation.
Fixes errors in https://github.com/alibaba/GraphScope/actions/runs/7044062862/job/19176259486?pr=3392

fix(python): fixes the result validation for edge sets

---

coordinator/gscoordinator/coordinator.py

fix(coordinator): Fix coordinator monitor bug

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/graph/RemoteTestGraph.java
python/requirements-dev.txt

See also: https://github.com/alibaba/GraphScope/actions/runs/7183076024/job/19582182622

ci: skip some GIE test cases due to the upgrade of vineyard

---

docs/flex/interactive/data_model.md
flex/interactive/examples/modern_graph/modern_graph.yaml
flex/storages/rt_mutable_graph/README.md
flex/storages/rt_mutable_graph/schema.cc
flex/storages/rt_mutable_graph/types.h
flex/tests/rt_mutable_graph/modern_graph_string_edge.yaml
interactive_engine/compiler/src/test/resources/config/modern/graph.yaml

refactor(interactive): Remove dummy config `incoming/outgoing_edge_strategy`

---

coordinator/gscoordinator/op_executor.py

The warning is a bit misleading for end users. These lines shouldn't be printed when `show_logs=True` and `log_level='INFO'` (default).

chore: probing analytical engine in coordinator shouldn't be warnings

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/processor/IrTestOpProcessor.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/result/GremlinTestResultProcessor.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/QueryStatusCallback.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/processor/AbstractResultProcessor.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/processor/GremlinResultProcessor.java
interactive_engine/executor/engine/pegasus/network/src/receive/net_rx.rs
interactive_engine/executor/engine/pegasus/pegasus/src/errors/mod.rs
interactive_engine/executor/engine/pegasus/pegasus/src/result.rs
interactive_engine/executor/engine/pegasus/server/src/rpc.rs

Fixes
https://github.com/alibaba/GraphScope/issues/3426

feat(interactive): Pegasus return status codes of rpc

---

flex/storages/rt_mutable_graph/loader/odps_fragment_loader.cc

fix(interactive): Fix bug in `ODPSFragmentLoader`

---

interactive_engine/executor/engine/pegasus/pegasus/src/lib.rs

Fixes
https://github.com/alibaba/GraphScope/issues/3450

fix(interactive): fix dead lock caused by write lock

---

interactive_engine/executor/store/groot/src/db/api/property.rs
interactive_engine/executor/store/groot/src/db/common/bytes/util.rs

refactor(interactive): revert encoding of groot

---

.github/workflows/build-graphscope-wheels-macos.yml

See also failure from https://github.com/alibaba/GraphScope/actions/runs/7616065975/job/20741994726

Try fixes macos nightly CI

---

interactive_engine/executor/ir/integrated/tests/auxilia_test.rs
interactive_engine/executor/ir/runtime/src/process/operator/map/get_v.rs

fix(interactive): fix a bug in runtime for edge filtering

---

.github/workflows/flex.yml
.github/workflows/hqps-db-ci.yml
flex/.devcontainer.json
flex/Dockerfile
flex/engines/graph_db/app/app_base.h
flex/engines/hqps_db/core/utils/hqps_type.h
flex/engines/http_server/codegen_proxy.h
flex/interactive/docker/interactive-runtime.Dockerfile
flex/scripts/install_dependencies.sh
flex/utils/arrow_utils.h

Fix the script `install_dependency.sh`, which install the necessary dependencies to build `Flex`.
Add flex building test on ubuntu 20.04/22.04, platform x86_64/arm64.

fix(interactive): Fix install_dependency.sh

---

docs/flex/interactive/custom_graph_data.md
docs/flex/interactive/data_import.md

docs(interactive): Update doc

---

.github/workflows/hqps-db-ci.yml
.github/workflows/local-ci.yml
Makefile
k8s/internal/Makefile

See also: https://github.com/alibaba/GraphScope/actions/runs/7709297882

ci: fixes a syntax error in CI

---

flex/engines/graph_db/app/hqps_app.cc

Correctly parsing request payload.

fix(interactive): Fix argument passing in hqps_app

---

.github/workflows/gaia.yml
.github/workflows/gss.yml
.github/workflows/k8s-ci.yml

chore: change manylinux2014-ci to manylinux2014

---

README.md

Update README.md for SIGMOD 2024 paper

---

flex/Dockerfile
flex/scripts/install_dependencies.sh

fix(interactive): fix install_dependencies

---

analytical_engine/apps/flash/flash_context.h
python/graphscope/tests/unittest/test_flash.py

fix(analytical): fix bug that flash app can not run on string oid graph

---

flex/CMakeLists.txt
flex/bin/load_plan_and_gen.sh
flex/coordinator/gs_flex_coordinator/controllers/procedure_controller.py
flex/coordinator/gs_flex_coordinator/core/alert/builtin_rules.py
flex/coordinator/gs_flex_coordinator/core/stoppable_thread.py
flex/engines/http_server/workdir_manipulator.cc
flex/interactive/bin/gs_interactive
flex/storages/rt_mutable_graph/csr/csr_base.h
flex/storages/rt_mutable_graph/csr/mutable_csr.h
python/graphscope/flex/rest/api/procedure_api.py

Fixes spelling errors in comments per https://github.com/alibaba/GraphScope/pull/3547#issuecomment-1950933992

ci: fixes typos in flex coordinator

---

flex/codegen/gen_code_from_plan.cc
flex/codegen/src/hqps/hqps_edge_expand_builder.h
flex/codegen/src/hqps/hqps_expr_builder.h
flex/codegen/src/hqps/hqps_get_v_builder.h
flex/codegen/src/hqps/hqps_path_expand_builder.h
flex/codegen/src/hqps/hqps_scan_builder.h
flex/codegen/src/hqps_generator.h
flex/codegen/src/pegasus/pegasus_expr_builder.h
flex/codegen/src/pegasus/pegasus_intersect_builder.h
flex/codegen/src/pegasus/pegasus_join_builder.h
flex/codegen/src/pegasus/pegasus_path_expand_builder.h
flex/codegen/src/pegasus/pegasus_repartition_builder.h
flex/codegen/src/pegasus/pegasus_union_builder.h

Fixes spelling errors in comments per https://github.com/alibaba/GraphScope/pull/3547#issuecomment-1950933992

fix: fixes typos/spelling in flex codegen

---

interactive_engine/executor/store/groot/src/db/common/concurrency/volatile.rs

fix: fixes the compiler error under rust >= 1.76.0

---

flex/interactive/docker/interactive-runtime.Dockerfile

Fix the graph_name inconsistency.
Fix #3613

fix(interactive): Fix `interactive-runtime.Dockerfile`

---

docs/analytical_engine/tutorial_dev_algo_java.md

fix(analytical): Fix documentation for GRAPE-JDK

---

interactive_engine/executor/ir/integrated/tests/pathxd_test.rs
interactive_engine/executor/ir/runtime/src/process/operator/map/get_v.rs

fix(interactive): fix a bug in PathExpand with 'PATH_OPT' as 'SIMPLE'

---

interactive_engine/pom.xml

fix(interactive): Minor typo fix

---

interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/ZkConfig.java
interactive_engine/executor/engine/pegasus/network/src/transport/block/mod.rs
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/discovery/ZkDiscovery.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/jna/JnaGraphStore.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/wal/kafka/KafkaLogService.java
interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/ir/GaiaEngine.java

Fixes the `updatePeerView` may not be trigger at the proper time.

fix(interactive): Fix the occasionally incorrect pegasus server routing configuration 

---

.github/workflows/local-ci.yml
Makefile
k8s/internal/Makefile

Fix torch version at 1.13.1 to be compatible with gcc8 and python3.7

fix(learning): Fix torch version  to be compatible with gcc8 and python3.7

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/rules/ExpandGetVFusionRule.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rel/graph/GraphPhysicalExpand.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rel/graph/GraphPhysicalGetV.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/plan/ExpandGetVFusionTest.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/runtime/GraphRelToProtoTest.java
interactive_engine/compiler/src/test/resources/proto/edge_expand_vertex_filter_test.json
interactive_engine/compiler/src/test/resources/proto/edge_expand_vertex_test.json
interactive_engine/compiler/src/test/resources/proto/edge_expand_vertex_with_filters_test.json
interactive_engine/compiler/src/test/resources/proto/partitioned_edge_expand_vertex_filter_test.json
interactive_engine/compiler/src/test/resources/proto/partitioned_edge_expand_vertex_test.json

fix(interactive): Fix unexpected alias when fusion `Expand` + `GetV`

---

interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/StoreConfig.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/StoreService.java

support concurrent compact to make large graph compact faster
Fixes

fix(interactive): Concurrent compact

---

flex/coordinator/gs_flex_coordinator/controllers/alert_controller.py
flex/coordinator/gs_flex_coordinator/controllers/procedure_controller.py
flex/coordinator/gs_flex_coordinator/core/client_wrapper.py
flex/coordinator/gs_flex_coordinator/core/insight/graph.py
flex/coordinator/gs_flex_coordinator/core/insight/groot.py
flex/coordinator/gs_flex_coordinator/core/interactive/hqps.py
flex/coordinator/gs_flex_coordinator/models/groot_property.py
flex/coordinator/gs_flex_coordinator/openapi/openapi.yaml
flex/coordinator/setup.py
flex/openapi/openapi_coordinator.yaml
python/graphscope/flex/rest/api/alert_api.py
python/graphscope/flex/rest/api/procedure_api.py
python/graphscope/flex/rest/models/groot_property.py
python/graphscope/gsctl/utils.py
python/setup.py

- Fixed OpenAPI generator version to 7.3.0
- Add mocking examples for Portal CI test
- Fixes some interface problems in FLEX Coordinator service

fix: Add mocking examples for Portal CI test

---

.github/workflows/gss.yml
.github/workflows/hadoop_scripts/offline_load.sh
.github/workflows/k8s-ci.yml
k8s/Makefile
k8s/actions-runner-controller/manylinux-ci.yaml
k8s/actions-runner-controller/manylinux.yaml
k8s/actions-runner-controller/ubuntu.yaml
k8s/actions-runner-controller/ubuntu/Dockerfile
k8s/internal/Makefile

Some changed according to dependency upgrades.

chore: fix CI problems

---

flex/engines/hqps_db/core/operator/edge_expand.h
flex/engines/hqps_db/core/operator/path_expand.h
flex/engines/hqps_db/core/sync_engine.h
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/integration/suite/simple/SimpleMatchQueries.java

fix(interactive): Fix Interactive CI test

---

flex/bin/interactive_server.cc
flex/engines/http_server/actor/admin_actor.act.cc
flex/engines/http_server/workdir_manipulator.cc
flex/storages/metadata/default_graph_meta_store.cc
flex/storages/metadata/graph_meta_store.cc
flex/storages/metadata/graph_meta_store.h
flex/storages/metadata/local_file_metadata_store.cc
flex/utils/property/types.h
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/reader/LocalMetaDataReader.java

fix(interactive): Fix some implementation of MetaService

---

flex/engines/graph_db/database/wal.cc
flex/utils/mmap_array.h

fix(interactive): add error handling during file operations

---

analytical_engine/apps/java_pie/java_pie_projected_parallel_app.h
analytical_engine/apps/java_pie/java_pie_property_parallel_app.h

The previous implementation didn't set the correct message strategy.

fix(analytical): Fix `MessageStrategy` customization for java apps

---

flex/engines/http_server/service/hqps_service.cc
flex/engines/http_server/service/hqps_service.h

fix(interactive): Fix waiting compiler ready

---

docs/Makefile
docs/flex/interactive/deployment.md
docs/flex/interactive/development/restful_api.md
docs/flex/interactive/getting_started.md
docs/flex/interactive_intro.md
flex/interactive/docker/entrypoint.sh
flex/interactive/docker/interactive-runtime.Dockerfile
flex/interactive/sdk/generate_sdk_doc.sh

fix(interactive): Fix interactive doc and image building

---

docs/flex/interactive/development/restful_api.md
flex/engines/http_server/actor/admin_actor.act.cc
flex/engines/http_server/actor/admin_actor.act.h
flex/engines/http_server/handler/admin_http_handler.cc
flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/GraphInterface.java
flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/impl/DefaultSession.java
flex/interactive/sdk/python/interactive_sdk/client/session.py

feat(interactive): Implement  API get_graph_schema for AdminService

---

flex/storages/metadata/default_graph_meta_store.cc

fix(interactive): Fix the bug of plugin not being deleted when deleting graph

---

charts/graphscope-store/templates/configmap.yaml
charts/graphscope-store/values.yaml
interactive_engine/executor/engine/pegasus/pegasus/Cargo.toml
interactive_engine/executor/engine/pegasus/server/Cargo.toml
k8s/dockerfiles/graphscope-store.Dockerfile

Configure it like
```yaml
otel:
enabled: true
uptrace:
enabled: true
service: "up2-uptrace.uptrace2"
token: "project2_secret_token"
```

chore: Support connecting to uptrace in kubernetes cluster.

---

flex/engines/http_server/service/hqps_service.cc

fix(interactive): Minor fix for interactive service

---

.github/workflows/hqps-db-ci.yml
flex/interactive/sdk/python/interactive_sdk/client/session.py
flex/openapi/openapi_interactive.yaml
flex/storages/rt_mutable_graph/schema.cc
flex/tests/interactive/modern_graph_schema_v0_0.yaml
flex/tests/interactive/modern_graph_schema_v0_1.yaml
flex/tests/interactive/plus_one.cc
flex/tests/interactive/test_call_proc.py
flex/tests/interactive/test_plugin_loading.sh

- Fix the problem of procedure loading with schema of version v0.0.
- Fix the related CI test. Two cpp procedures are added
```cpp
class ExampleQuery : public CypherReadAppBase<int32_t>;
class ReadExample : public ReadAppBase;
```
The first use `CypherJson` InputFormat, and the latter use `CppEncoder` format.

fix(interactive): Fix `stored_procedure` parsing in old-version schema and refactor CI

---

flex/engines/http_server/handler/hqps_http_handler.cc

Minor fix for hqps_http_handler

fix(interactive): Minor fix: service status is stopped after initialized.

---

blog/feed.xml
publications.html

Update recent papers on web 

---

README.md

Update Latest News on README.md

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/GraphIOProcessor.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/planner/cbo/CBOTest.java

Type inference of path expand is bound to the user-given query order, which may be reversed after optimization. Re-infer the type of path expand after optimization if changes occur.
Fixes #3730

fix(interactive): Fix Type Inference Bugs in Path Expand After Optimization

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rex/operator/SqlMapValueConstructor.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/type/GraphTypeFactoryImpl.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4x/GraphBuilderTest.java

fix(interactive): Fix Result Parser Issue of Gremlin `select('a', 'b').by(valueMap())`

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphBuilder.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4x/GraphBuilderTest.java

fix(interactive): Fix Gremlin Alias Issue in GraphBuilder

---

charts/graphscope-store/values.yaml

fix(interactive): Fix a bug in Groot `values.yaml`

---

.github/config.yml

chore: update the invitation link of dingtalk

---

.github/workflows/build-graphscope-manylinux-ext-images.yml
coordinator/gscoordinator/flex/core/interactive/hqps.py
python/graphscope/gsctl/commands/common.py
python/graphscope/gsctl/commands/dev.py

fix: support deploy, destroy instance by gsctl

---

.github/workflows/release.yml

ci: find the gsctl wheel package correctly

---

flex/engines/hqps_db/database/mutable_csr_interface.h
flex/utils/property/column.cc
flex/utils/property/column.h

Add more data type support when creating a reference column in the HQPS engine.

fix(interactive): Fix ref column creation issues

---

interactive_engine/executor/common/dyn_type/src/object.rs
interactive_engine/executor/ir/graph_proxy/src/utils/expr/eval.rs
interactive_engine/executor/ir/graph_proxy/src/utils/expr/eval_pred.rs
interactive_engine/executor/ir/runtime/src/process/operator/accum/accum.rs
interactive_engine/executor/ir/runtime/src/process/operator/group/group.rs
interactive_engine/executor/ir/runtime/src/process/operator/sort/sort.rs

fix(interactive): Support NULL Value in expression in GIE Runtime

---

charts/graphscope-store/templates/configmap.yaml
interactive_engine/executor/engine/pegasus/network/src/send/mod.rs
interactive_engine/executor/engine/pegasus/network/src/transport/block/mod.rs

fix(interactive): add tcp write time & fix block mode

---

.gitmodules

fix(learning): fix graph-learn CI

---

.github/workflows/interactive.yml
docs/flex/interactive/dev_guide.md
docs/flex/interactive/development/dev_and_test.md
flex/interactive/docker/interactive-runtime.Dockerfile
flex/tests/hqps/engine_config_test.yaml

Add a tutorial for `dev_and_test` flex interactive.

refactor(interactive): Add dev_and_test tutorial for Interactive

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/proto/GraphRelProtoPhysicalBuilder.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/proto/GraphRelToProtoConverter.java

fix(interactive): Give extra params such as snapshot id in the physical plan

---

blog/feed.xml
publications.html

Add DGS poster

---

flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.cc

fix(interactive): Fix bug of loading edges with `long_text` property

---

flex/engines/http_server/handler/http_utils.cc
flex/interactive/sdk/python/gs_interactive/client/result.py
flex/interactive/sdk/python/gs_interactive/client/status.py
flex/interactive/sdk/python/test/test_driver.py

Fixing the issue of receiving error messages in Python SDK.

fix(interactive): Fixing error messages receiving  in Python SDK.

---

flex/interactive/sdk/python/gs_interactive/client/session.py
flex/interactive/sdk/python/test/test_driver.py

fix(interactive): Add graph_id/proc_id type check for python sdk

---

flex/storages/rt_mutable_graph/loading_config.cc

fix(interactive): Enhance input file path parsing in loadingConfig

---

flex/engines/hqps_db/database/mutable_csr_interface.h
flex/storages/rt_mutable_graph/csr/csr_base.h
flex/storages/rt_mutable_graph/csr/immutable_csr.h
flex/storages/rt_mutable_graph/csr/mutable_csr.h
flex/storages/rt_mutable_graph/dual_csr.h
flex/storages/rt_mutable_graph/mutable_property_fragment.cc
flex/storages/rt_mutable_graph/mutable_property_fragment.h
flex/storages/rt_mutable_graph/schema.cc
flex/storages/rt_mutable_graph/schema.h
flex/utils/property/column.cc
flex/utils/property/column.h

refactor(interactive): Add method to get `edge_num` and some code refactor

---

.github/workflows/interactive.yml
flex/bin/load_plan_and_gen.sh
flex/interactive/examples/graph_algo/0_count_paper.cypher
flex/interactive/examples/graph_algo/1_challenge_strategy.cypher
flex/interactive/examples/graph_algo/1_count_topics.cypher
flex/interactive/examples/graph_algo/2_get_edge_type.cypher
flex/interactive/examples/graph_algo/2_get_topic_papers_hist.cypher
flex/interactive/examples/graph_algo/3_get_challenges.cypher
flex/interactive/examples/graph_algo/3_get_distinct_edge_type.cypher
flex/interactive/examples/graph_algo/4_filter_edge.cypher
flex/interactive/examples/graph_algo/4_get_solutions_of_challenges.cypher
flex/interactive/examples/graph_algo/5.cypher
flex/interactive/examples/graph_algo/5_get_challenge_paper_hist_of_topic.cypher
flex/interactive/examples/graph_algo/6.cypher
flex/interactive/examples/graph_algo/7.cypher
flex/interactive/examples/graph_algo/8.cypher
flex/interactive/examples/graph_algo/9.cypher
flex/interactive/examples/graph_algo/graph.yaml
flex/interactive/examples/graph_algo/topic_challenge_hist.cypher
flex/interactive/examples/graph_algo/topic_paper_hist.cypher
flex/tests/interactive/graph_algo_test.yaml
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphPlanner.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/integration/suite/graphAlgo/GraphAlgoQueries.java
interactive_engine/compiler/src/main/java/org/apache/calcite/sql/type/GraphFamilyOperandTypeChecker.java

- Refine the example cypher stored procedures.
- Providing extra configuration via an `.yaml` file to guide the stored procedure generation(producing the procedure meta yaml)
- Some renaming issue for graph_algo dataset.
- Report the error of operand mismatching in compiler.
Fix #4047

refactor(interactive): Refine the example cypher stored procedures

---

python/graphscope/analytical/app/triangles.py

fix(analytical): add check direction for triangles

---

flex/engines/http_server/actor/admin_actor.act.cc
flex/engines/http_server/handler/admin_http_handler.cc
flex/storages/metadata/default_graph_meta_store.cc
flex/storages/metadata/local_file_metadata_store.cc

refactor(interactive): Remove some unnecessary logging

---

flex/engines/http_server/workdir_manipulator.cc
flex/storages/metadata/default_graph_meta_store.cc

Order procedures by default based on creation time.

refactor(interactive): Order procedures by default based on creation time.

---

flex/engines/http_server/actor/admin_actor.act.cc

As titled.
Compiling with aocc compiler fails.

fix(interactive): Interactive CI hot fix

---

journey/cn/index.html
journey/index.html
journey/index.js

- Fix the start point of the journey path

Fix the start point of the journey path

---

blog/feed.xml
journey/index.js
sitemap.txt

update sitemap for graphscope.io

---

CITATION.cff
README.md

docs: Update CITATION to latest GraphScope Flex paper.

---

flex/bin/bulk_loader.cc
flex/engines/graph_db/grin/CMakeLists.txt
flex/engines/graph_db/grin/src/property/property.cc
flex/engines/graph_db/grin/src/property/propertylist.cc
flex/storages/rt_mutable_graph/csr/mutable_csr.cc
flex/storages/rt_mutable_graph/csr/mutable_csr.h
flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.cc
flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.h
flex/storages/rt_mutable_graph/loader/csv_fragment_loader.cc
flex/storages/rt_mutable_graph/loader/csv_fragment_loader.h
flex/storages/rt_mutable_graph/loader/i_fragment_loader.h
flex/storages/rt_mutable_graph/loader/odps_fragment_loader.cc
flex/storages/rt_mutable_graph/loader/odps_fragment_loader.h
flex/storages/rt_mutable_graph/mutable_property_fragment.cc
flex/utils/mmap_array.h

fix(interactive): add error message for file operations

---

flex/engines/http_server/actor/admin_actor.act.cc
flex/openapi/openapi_interactive.yaml
interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/api/SchemaFetcher.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/reader/HttpIrMetaReader.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/reader/IrMetaReader.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/reader/LocalIrMetaReader.java
interactive_engine/frontend/src/main/java/com/alibaba/graphscope/frontend/VineyardIrMetaReader.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/WrappedSchemaFetcher.java
interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/Frontend.java
interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/ir/GrootIrMetaReader.java

fix(interactive): Make Statistics Configurable by Interface in Compiler

---

flex/engines/graph_db/runtime/common/rt_any.cc

Fixes
https://github.com/alibaba/GraphScope/issues/4134

fix(interactive): fix sinking edge without properties.

---

.github/workflows/codeql.yml
.github/workflows/pr-check.yml

ci: make codeql run less frequent

---

flex/engines/graph_db/runtime/adhoc/operators/group_by.cc
flex/engines/graph_db/runtime/adhoc/utils.cc
flex/engines/graph_db/runtime/common/rt_any.cc
flex/engines/graph_db/runtime/common/rt_any.h

https://github.com/alibaba/GraphScope/issues/4162

fix(interactive): fix some bug with GroupBy

---

flex/engines/graph_db/runtime/common/context.cc
flex/engines/graph_db/runtime/common/operators/intersect.cc

fix(interactive): fix some bug with Intersect

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java

fix(interactive): Fix Bugs in Dynamic Schema Fetching

---

docs/interactive_engine/tinkerpop/supported_gremlin_steps.md
interactive_engine/compiler/ir_experimental_ci.sh
interactive_engine/compiler/pom.xml
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/ffi/Utils.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/proto/Utils.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/config/GraphOpt.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/jna/type/PathOpt.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/suite/standard/IrGremlinQueryTest.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/step/PathExpandStep.java
interactive_engine/executor/ir/core/src/plan/ffi.rs
interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/path.rs
interactive_engine/executor/ir/proto/algebra.proto
interactive_engine/executor/ir/proto/physical.proto
interactive_engine/executor/ir/runtime/src/assembly.rs
interactive_engine/executor/ir/runtime/src/process/operator/sink/sink.rs
interactive_engine/pom.xml

Reverts alibaba/GraphScope#4101

Revert "feat(interactive): Support `PathExpand` with `PATH_OPT=TRAIL` in GIE"

---

analytical_engine/core/context/java_context_base.h
analytical_engine/java/grape-giraph/src/main/java/com/alibaba/graphscope/parallel/mm/impl/GiraphMpiMessageManager.java
analytical_engine/java/grape-giraph/src/main/java/com/alibaba/graphscope/parallel/utils/Utils.java
analytical_engine/java/grape-graphx/src/main/java/com/alibaba/graphscope/graphx/GraphXParallelPIE.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/parallel/MessageInBuffer.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/parallel/ParallelMessageManager.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/parallel/ParallelPropertyMessageManager.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/serialization/FFIByteVectorInputStream.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/serialization/FFIByteVectorOutputStream.java

fix(analytical): Fix memory leak for FFI Objects

---

flex/engines/graph_db/database/graph_db_session.h
flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/utils/Encoder.java
flex/interactive/sdk/python/gs_interactive/client/session.py
flex/interactive/sdk/python/gs_interactive/client/utils.py
flex/interactive/sdk/python/gs_interactive/tests/test_utils.py
flex/tests/interactive/test_call_proc.py

Implement the Encoder/Decoder for the Interactive Python SDK, enabling users to customize query parameters and deserialize the output.

refactor(interactive): Add Encoder/Decoder for Python SDK

---

flex/interactive/sdk/python/gs_interactive/client/session.py
flex/interactive/sdk/python/gs_interactive/tests/conftest.py
flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py

Fix the bug in robust test. Related issue: https://github.com/alibaba/GraphScope/issues/4192

fix(interactive): Fix robust test

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/glogue/calcite/handler/GraphRowCountHandler.java

… unavailable
as titled.
Fixes

fix(interactive): Fix Bugs of Count Estimation When Feasible Plan Is Unavailable in Equivalent Set

---

.github/workflows/interactive.yml
charts/graphscope-interactive/templates/_helpers.tpl
charts/graphscope-interactive/templates/configmap.yaml
charts/graphscope-interactive/templates/engine/statefulset.yaml
charts/graphscope-interactive/templates/frontend/statefulset.yaml
docs/flex/interactive/configuration.md
docs/flex/interactive/development/dev_and_test.md
flex/bin/interactive_server.cc
flex/engines/http_server/graph_db_service.cc
flex/engines/http_server/graph_db_service.h
flex/engines/http_server/workdir_manipulator.cc
flex/tests/hqps/hqps_codegen_test.sh
flex/tests/hqps/interactive_config_test.yaml
flex/tests/hqps/interactive_config_test_cbo.yaml
flex/utils/service_utils.h
interactive_engine/compiler/src/test/resources/config/gs_interactive_hiactor.yaml
interactive_engine/compiler/src/test/resources/config/gs_interactive_pegasus.yaml
k8s/dockerfiles/flex-interactive.Dockerfile
k8s/dockerfiles/interactive-entrypoint.sh

refactor(interactive): Rename the configuration file for Interactive, and remove some unused configuration

---

.github/workflows/flex-interactive.yml
docs/flex/interactive/configuration.md
python/graphscope/gsctl/commands/dev.py

The customized engine configuration can be specified during the deployment of the interactive instance.

feat(interactive): Support customizing service configuration via `gsctl`

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/GraphIOProcessor.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4x/GraphBuilderTest.java

fix(interactive): Fix Bugs of Type Inference in `both()`

---

flex/engines/graph_db/database/graph_db_session.cc
flex/engines/graph_db/runtime/adhoc/operators/scan.cc
flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/common/Result.java
flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/common/Status.java
proto/error/interactive.proto

Add type check in scan operator, and ensure the error message can be sent back to client.

fix(interactive): Fix bug in scan operator

---

NOTICE.txt
analytical_engine/apps/assortativity/attribute_assortativity.h
analytical_engine/apps/assortativity/degree_assortativity_coefficient.h
analytical_engine/apps/flash/clustering/clustering-coeff.h
flex/codegen/src/pegasus/pegasus_project_builder.h
flex/codegen/src/pegasus/pegasus_select_builder.h

fix(interactive): Fix typos

---

flex/engines/graph_db/runtime/adhoc/var.cc
flex/engines/graph_db/runtime/common/accessors.cc
flex/engines/graph_db/runtime/common/accessors.h
flex/engines/graph_db/runtime/common/leaf_utils.h
flex/engines/graph_db/runtime/common/operators/scan.h

fix(interactive): Support more cases for var in expression

---

flex/Dockerfile

Update the `flex/Dockerfile` to install the required dependencies for building and running Interactive.

fix(interactive): Update flex/Dockerfile

---

docs/flex/interactive/development/stored_procedure/cpp_procedure.md
docs/flex/interactive/getting_started.md
docs/flex/interactive/stored_procedures.md

docs(interactive): Add doc for creating cpp procedure with gsctl

---

.github/workflows/release.yml
python/setup_flex.py
python/setup_gsctl.py

ci: fix ci problem during release gsctl

---

.github/workflows/gaia.yml
docs/interactive_engine/neo4j/supported_cypher.md
interactive_engine/compiler/src/main/antlr4/CypherGS.g4
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rel/GraphLogicalUnfold.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rel/GraphShuttle.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/proto/GraphRelToProtoConverter.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphBuilder.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphRexBuilder.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphStdOperatorTable.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/GraphBuilderVisitor.java
interactive_engine/compiler/src/main/java/org/apache/calcite/sql/type/GraphOperandTypes.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/planner/cbo/BITest.java

refactor(interactive): Support `Unfold` Operation in Cypher Queries

---

interactive_engine/groot-module/pom.xml
interactive_engine/groot-server/pom.xml

chore: exlude simple and log4j jar from groot assembly

---

.github/workflows/flex-interactive.yml
.github/workflows/gae.yml
.github/workflows/k8s-ci.yml
.github/workflows/local-ci.yml
.github/workflows/nightly.yml
python/graphscope/config.py
python/graphscope/gsctl/commands/dev.py

fix: codecov uploading problem

---

.github/workflows/release.yml

ci: release interactive image nightly

---

.github/workflows/release.yml

fix: hot fix for building interactive image

---

docs/Makefile
docs/flex/interactive/development/java/EdgeApi.md
docs/flex/interactive/development/java/GraphManagementApi.md
docs/flex/interactive/development/java/JobManagementApi.md
docs/flex/interactive/development/java/ProcedureManagementApi.md
docs/flex/interactive/development/java/QueryServiceApi.md
docs/flex/interactive/development/java/ServiceManagementApi.md
docs/flex/interactive/development/java/VertexApi.md
docs/flex/interactive/development/java/java_sdk.md
docs/flex/interactive/development/python/EdgeApi.md
docs/flex/interactive/development/python/GraphManagementApi.md
docs/flex/interactive/development/python/JobManagementApi.md
docs/flex/interactive/development/python/ProcedureManagementApi.md
docs/flex/interactive/development/python/QueryServiceApi.md
docs/flex/interactive/development/python/ServiceManagementApi.md
docs/flex/interactive/development/python/VertexApi.md
docs/flex/interactive/development/python/driver.rst
docs/flex/interactive/development/python/encoder.rst
docs/flex/interactive/development/python/python_sdk.md
docs/flex/interactive/development/python/result.rst
docs/flex/interactive/development/python/session.rst
docs/flex/interactive/development/python/status.rst
docs/flex/interactive/development/stored_procedure/cpp_procedure.md
flex/interactive/sdk/generate_sdk_doc.sh
flex/interactive/sdk/java/pom.xml
flex/interactive/sdk/python/gs_interactive/client/driver.py
flex/interactive/sdk/python/gs_interactive/client/result.py
flex/interactive/sdk/python/gs_interactive/client/session.py
flex/interactive/sdk/python/gs_interactive/client/status.py
flex/interactive/sdk/python/gs_interactive/client/utils.py

The current Interactive SDK documentation only includes the Service APIs and code generated by openapi-generator. This PR adds auto-generated documentation for the hand-written wrapper and utility classes for SDKs.
Also add comments to python/java sdk code.
Fix #4263

refactor(interactive): Refine the documentation of Interactive SDK

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rel/metadata/glogue/Glogue.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rel/metadata/schema/GlogueSchema.java
interactive_engine/executor/store/groot/src/db/graph/store.rs
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/coordinator/SchemaManager.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/SnapshotCache.java

fix(interactive): refine the logs when fetching statistics from groot

---

.github/workflows/pr-check.yml

Curious why the error didn't show up in PR https://github.com/alibaba/GraphScope/pull/4272?

fix(interactive): Fix cpp format check

---

.github/workflows/pr-check.yml
docs/flex/interactive/development/python/VertexApi.md
flex/engines/graph_db/grin/src/property/property.cc
flex/engines/graph_db/runtime/common/columns/value_columns.h
flex/engines/hqps_db/core/base_engine.h
flex/engines/hqps_db/core/operator/edge_expand.h
flex/engines/hqps_db/core/operator/group_by.h
flex/engines/hqps_db/core/operator/project.h
flex/engines/hqps_db/core/utils/hqps_utils.h
flex/interactive/sdk/examples/python/basic_example.py
flex/interactive/sdk/python/gs_interactive/client/__init__.py
flex/interactive/sdk/python/gs_interactive/client/driver.py
flex/interactive/sdk/python/gs_interactive/client/result.py
flex/interactive/sdk/python/gs_interactive/client/session.py
flex/interactive/sdk/python/gs_interactive/client/status.py
flex/interactive/sdk/python/gs_interactive/models/long_text.py
flex/interactive/sdk/python/gs_interactive/tests/conftest.py
flex/interactive/sdk/python/gs_interactive/tests/test_driver.py
flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py
flex/interactive/sdk/python/gs_interactive/tests/test_utils.py
flex/interactive/sdk/python/setup.cfg
flex/interactive/sdk/python/setup.py
flex/tests/hqps/context_test.cc

- Field  `type` is not needed.
- Fix python/c++ code format. Somehow the PRhttps://github.com/alibaba/GraphScope/pull/4272 didn't reveal these problems

fix(interactive): Correct the improper use of ModelProperty

---

flex/engines/http_server/actor/executor.act.cc
flex/engines/http_server/actor/executor.act.h
flex/engines/http_server/handler/graph_db_http_handler.cc
flex/engines/http_server/types.h

As titled. Check the `graph_id` params in http_handler.

refactor(interactive): Remove some dummy code

---

.github/workflows/interactive.yml
flex/engines/graph_db/grin/CMakeLists.txt
flex/engines/http_server/CMakeLists.txt
flex/utils/CMakeLists.txt
flex/utils/service_utils.h

Reuse compiled libraries and binaries across CI jobs for Interactive CI.

ci: Reuse the compiled libraries/binaries between jobs for interactive CI

---

flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py

Wait a while for compiler to get the latest graph schema.
See https://github.com/alibaba/GraphScope/actions/runs/11812000683/job/32907096373

ci: Fix interactive ci

---

coordinator/gscoordinator/coordinator.py
coordinator/requirements.txt
python/requirements.txt

refactor(coordinator): Support cross origin

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/type/GraphTypeFactoryImpl.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4x/GraphBuilderTest.java
interactive_engine/compiler/src/test/resources/logback-test.xml

fix(interactive): Fix Bugs of Mismatch Label in `elementMap`

---

interactive_engine/executor/engine/pegasus/server/src/rpc.rs

fix(interactive): add logs when return result in GRPC

---

docs/interactive_engine/tinkerpop/faq.md

docs: add faq about parallelism settings for GIE queries

---

k8s/dockerfiles/graphscope-store.Dockerfile
k8s/dockerfiles/interactive.Dockerfile
k8s/internal/Makefile
python/graphscope/client/rpc.py

also bump up rustup toolchain version to 1.76.0 to avoid some rust packages compilation failure.

fix(python): refresh channel incase the service becomes available after initial heart beat

---

docs/interactive_engine/tinkerpop/faq.md

Commit c1007cff5c9d6274eacd8ec6cc37ecce44d17e3a moved the `supported_gremlin_steps.md` file. This PR adjusts sources to changes.

fix: update `supported_gremlin_steps.md` reference

---

interactive_engine/assembly/src/conf/graphscope/frontend.vineyard.properties

fix(interactive): Enable Graph Optimizer in Python GS

---

python/graphscope/analytical/udf/patch.py
python/graphscope/client/utils.py
python/graphscope/deploy/hosts/cluster.py
python/graphscope/framework/app.py
python/graphscope/framework/context.py
python/graphscope/framework/dag.py
python/graphscope/framework/graph_builder.py
python/graphscope/framework/loader.py
python/graphscope/gsctl/scripts/install_deps.sh
python/graphscope/nx/algorithms/builtin.py
python/graphscope/nx/algorithms/tests/forward/test_isomorphism.py
python/graphscope/nx/algorithms/tests/forward/test_simple_paths.py
python/graphscope/nx/classes/graph.py
scripts/launch_cluster.py
tutorials/02_graph_manipulations_with_networkx_compatible_apis.ipynb
tutorials/zh/02_graph_manipulations_with_networkx_compatible_apis.ipynb
tutorials/zh/07_interactive_query_with_gremlin.ipynb

fix(interactive): Fix typo

---

k8s/dockerfiles/coordinator.Dockerfile

fix(coordinator): Add timezone info in Dockerfile

---

.github/workflows/interactive.yml
flex/interactive/sdk/python/gs_interactive/client/result.py
flex/interactive/sdk/python/gs_interactive/client/session.py
flex/interactive/sdk/python/gs_interactive/client/status.py
flex/tests/hqps/interactive_config_test.yaml
flex/utils/yaml_utils.cc
interactive_engine/compiler/conf/ir.compiler.properties
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/GraphConfig.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/YamlConfigs.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/reader/HttpIrMetaReader.java

fix(interactive): Fix yaml node parsing

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/exception/FrontendException.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/type/GraphTypeFactoryImpl.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4x/GraphBuilderTest.java

fix(interactive): Fix Bugs of Alias Id in `Union`

---

.github/workflows/interactive.yml
flex/tests/hqps/hqps_codegen_test.sh

Paralleling Interactive codegen tests.
Codegen test time: 10m ->5~6min
Fix #4403

refactor(interactive): Speedup Interactive CI

---

flex/interactive/sdk/python/test-requirements.txt
python/graphscope/gsctl/scripts/install_deps.sh

- Resolve the CI issue: https://github.com/alibaba/GraphScope/actions/runs/12862048341/job/35856903879
- Use an elder version of mimalloc.

fix(interactive): Add requests in test-requirements

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphPlanner.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/QueryCache.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/executor/GraphQueryExecutor.java

fix(interactive): Log Query Cache Hit

---

docs/flex/interactive/data_model.md
flex/engines/graph_db/runtime/common/columns/edge_columns.cc
flex/engines/graph_db/runtime/common/columns/edge_columns.h
flex/engines/graph_db/runtime/common/operators/retrieve/edge_expand.cc
flex/engines/graph_db/runtime/common/operators/retrieve/edge_expand.h
flex/engines/graph_db/runtime/common/rt_any.cc
flex/engines/graph_db/runtime/common/rt_any.h
flex/interactive/sdk/python/gs_interactive/tests/conftest.py
flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py
flex/utils/property/column.cc
flex/utils/property/column.h
flex/utils/property/types.cc
flex/utils/property/types.h

fix(interactive): Support multiple edge properties and some minor fix

---

flex/engines/http_server/actor/admin_actor.act.cc

fix(interactive): Minor fix for Interactive Metadata store

---

docs/sphinx_ext.py

Keep documents for latest 3 tags.

docs: Fix docs generation

---

.github/workflows/codeql.yml
python/graphscope/gsctl/scripts/install_deps.sh

ci: Fixing codeql test

---

interactive_engine/groot-client/src/test/java/com/alibaba/graphscope/groot/sdk/ClientTest.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/write/GraphWriter.java

fix(interactive): Correct Error Handling for Nonexistent Edge Kind in Groot When Writing Edges

---

analytical_engine/apps/flash/core/degeneracy-ordering.h
analytical_engine/core/fragment/arrow_flattened_fragment.h
analytical_engine/java/grape-demo/src/main/java/com/alibaba/graphscope/example/stringApp/StringApp.java
analytical_engine/java/grape-demo/src/main/java/com/alibaba/graphscope/example/stringApp/StringAppContext.java
analytical_engine/java/grape-giraph/src/main/java/com/alibaba/graphscope/app/GiraphComputationAdaptor.java
analytical_engine/java/grape-giraph/src/main/java/com/alibaba/graphscope/factory/GiraphComputationFactory.java
analytical_engine/java/grape-graphx/src/main/java/com/alibaba/graphscope/context/GraphXParallelAdaptorContext.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/app/DefaultAppBase.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/app/ParallelAppBase.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/context/ContextDataType.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/context/DefaultContextBase.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/context/ParallelContextBase.java
analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/utils/AppContextGetter.java
analytical_engine/java/grape-runtime/src/test/java/com/alibaba/graphscope/utils/ContextUtilsTest.java
analytical_engine/java/run_graphx.sh
analytical_engine/test/giraph_runner.h
coordinator/gscoordinator/flex/core/insight/groot.py
coordinator/gscoordinator/flex/core/insight/job.py

fix: Fix typos

---

.github/workflows/flex-interactive.yml
coordinator/gscoordinator/__init__.py
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/flex/core/client_wrapper.py
coordinator/gscoordinator/flex/core/deployment.py
coordinator/gscoordinator/flex/core/utils.py
k8s/dockerfiles/flex-interactive.Dockerfile
k8s/dockerfiles/interactive-entrypoint.sh
python/.openapi-generator-ignore
python/graphscope/config.py

Try to introduce some conditional import to avoid introducing large python packages.
Previous interactive image size: 3.2GB
Now: 1.46GB

refactor(interactive): Reduce image size

---

.github/workflows/flex-interactive.yml
coordinator/gscoordinator/coordinator.py
coordinator/gscoordinator/utils.py
docs/flex/interactive/configuration.md
flex/engines/http_server/actor/admin_actor.act.cc
flex/engines/http_server/actor/admin_actor.act.h
flex/engines/http_server/graph_db_service.cc
flex/engines/http_server/graph_db_service.h
flex/engines/http_server/handler/admin_http_handler.cc
flex/engines/http_server/handler/admin_http_handler.h
flex/engines/http_server/workdir_manipulator.cc
flex/engines/http_server/workdir_manipulator.h
flex/tests/hqps/interactive_config_test.yaml
flex/utils/service_utils.cc
flex/utils/service_utils.h
k8s/dockerfiles/flex-interactive.Dockerfile
k8s/dockerfiles/interactive-entrypoint.sh
python/.openapi-generator-ignore
python/graphscope/config.py
python/graphscope/gsctl/commands/dev.py

feat(interactive): Introduce max_content_size for admin_service

---

interactive_engine/executor/store/groot/src/db/graph/store.rs
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/coordinator/GarbageCollectManager.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/StoreService.java
interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/ir/FrontendQueryManager.java

Garbage collect may not be triggered after coordinator is restarted.

fix(interactive): fix gc not triggered error

---

docs/Makefile
python/setup.py

As titled.
Fix https://github.com/alibaba/GraphScope/actions/runs/13361784842/job/37312567363

docs: Fix doc generation for flex coordinator

---

interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/wrapper/DataType.java
interactive_engine/executor/store/groot/src/db/api/property.rs
interactive_engine/executor/store/groot/src/db/api/schema.rs
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/GrootDdlService.java

fix(interactive): fix type transformation errors caused by inconsistent enum type values

---

flex/engines/graph_db/runtime/common/operators/retrieve/edge_expand.h
flex/engines/graph_db/runtime/common/operators/retrieve/edge_expand_impl.h
flex/engines/graph_db/runtime/common/rt_any.cc
flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py
flex/tests/hqps/interactive_config_test.yaml
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/integration/suite/simple/SimpleMatchQueries.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/integration/ldbc/SimpleMatchTest.java

fix(interactive): Fix some edge_expand queries

---

.github/workflows/flex-interactive.yml
.github/workflows/release.yml
docs/flex/interactive/configuration.md
docs/flex/interactive/installation.md
flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.cc
flex/storages/rt_mutable_graph/loader/basic_fragment_loader.h
flex/storages/rt_mutable_graph/mutable_property_fragment.cc
flex/storages/rt_mutable_graph/schema.h
flex/utils/id_indexer.h
flex/utils/property/column.cc
flex/utils/property/column.h
flex/utils/property/types.cc
flex/utils/property/types.h
flex/utils/pt_indexer.h
flex/utils/service_utils.h
python/graphscope/gsctl/commands/dev.py

- Let `gsctl` use the latest interactive image.
- Allow overriding configuration in config via command line argument: `--set a=b`

feat(interactive): Update document and build latest Interactive image.

---

.github/workflows/release.yml

As titled.
see https://github.com/alibaba/GraphScope/actions/runs/13448712200

ci: fix typo in release.yml

---

.github/workflows/release.yml

ci: Fix release

---

.github/workflows/build-graphscope-images-linux.yml
k8s/dockerfiles/coordinator.Dockerfile
k8s/dockerfiles/learning.Dockerfile

fix(interactive): disable repair wheel in coordinator dockerfile

---

flex/interactive/sdk/python/gs_interactive/tests/conftest.py
flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py
flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.cc
flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.h
flex/utils/property/column.cc
flex/utils/property/column.h

feat(interactive): support `long_text` in interactive

---

flex/engines/graph_db/runtime/common/columns/edge_columns.h

fix(interactive): enable more than 256 labels in edge column

---

coordinator/gscoordinator/flex/core/insight/graph.py
coordinator/gscoordinator/flex/core/utils.py

ci: Fix helm test for graphscope store

---

flex/engines/graph_db/database/wal/local_wal_parser.cc
flex/engines/graph_db/database/wal/local_wal_parser.h

fix(interactive): `LocalWalParser` not work currently

---

flex/engines/graph_db/runtime/common/operators/retrieve/path_expand.cc
flex/engines/graph_db/runtime/common/operators/retrieve/path_expand_impl.h
flex/engines/graph_db/runtime/common/rt_any.cc
flex/engines/graph_db/runtime/common/rt_any.h
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/integration/suite/simple/SimpleMatchQueries.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/integration/ldbc/SimpleMatchTest.java

fix(interactive): Support sinking paths in Interactive

---

charts/graphscope-store/templates/configmap.yaml
charts/graphscope-store/templates/onepod/statefulset.yaml
charts/graphscope-store/templates/portal/statefulset.yaml
charts/graphscope-store/values.yaml
coordinator/gscoordinator/flex/core/config.py
coordinator/gscoordinator/flex/core/insight/graph.py

feat(interactive): Upgrade graphscope-store imageto 0.30.0 and enable portal in onepod mode

---

flex/engines/graph_db/app/builtin/shortest_path_among_three.cc
flex/engines/graph_db/app/builtin/shortest_path_among_three.h
flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py
flex/storages/metadata/graph_meta_store.cc
flex/utils/property/types.cc

fix(interactive): Fix builtin procedure shortest_path_among_three, accept any type pk values

---

flex/bin/interactive_server.cc
flex/bin/rt_server.cc
flex/engines/graph_db/app/cypher_app_utils.cc
flex/engines/graph_db/database/graph_db.cc
flex/engines/graph_db/database/wal/wal.cc
flex/engines/graph_db/runtime/utils/cypher_runner_impl.cc
flex/engines/graph_db/runtime/utils/cypher_runner_impl.h
flex/storages/rt_mutable_graph/mutable_property_fragment.cc
flex/utils/service_utils.h

fix(interactive): make the server exit cleanly

---

flex/engines/graph_db/database/graph_db.cc

fix(interactive): fix hqps ci

---

docs/overview/positioning.md

refactor(flex): Refer to KuzuDb as one of the graph databases in docs of graphscope positioning

---

flex/engines/graph_db/runtime/common/operators/retrieve/edge_expand.cc
flex/engines/graph_db/runtime/common/operators/retrieve/path_expand.cc

fix(interactive): Optimize the `edge expand` and `path expand` operator when there are many vertex labels 

---

charts/graphscope-store/templates/portal/statefulset.yaml
charts/graphscope-store/templates/store/statefulset.yaml
charts/graphscope-store/values.yaml
coordinator/gscoordinator/flex/core/config.py
coordinator/gscoordinator/flex/core/insight/groot.py
coordinator/gscoordinator/flex/core/utils.py
interactive_engine/assembly/src/bin/groot/store_ctl.sh
interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/GrootGraphDaemon.java

For restarting groot service, we need to send request to groot store pod.

feat(interactive): Implement restart for insight

---

flex/engines/graph_db/database/wal/local_wal_parser.cc
flex/engines/graph_db/database/wal/local_wal_parser.h
flex/engines/graph_db/database/wal/wal.h

fix(interactive): Cannot assume the number of WALs has an upper limit

---

flex/engines/http_server/handler/graph_db_http_handler.cc
flex/engines/http_server/handler/http_utils.cc
flex/engines/http_server/handler/http_utils.h
flex/utils/remote/oss_storage.cc
flex/utils/remote/oss_storage.h

For the queries service, add an HTTP API to detect whether it is OK.

feat(interactive): Add readiness probe for graph_db_service

---

flex/openapi/openapi_interactive.yaml

Reformat the openapi-interactive.yaml and add some field, struct.

refactor(interactive): Refine openapi-interactive.yaml

---

flex/bin/interactive_server.cc
flex/openapi/openapi_interactive.yaml
flex/storages/rt_mutable_graph/schema.cc
flex/storages/rt_mutable_graph/schema.h
k8s/dockerfiles/interactive-entrypoint.sh

feat(interactive): Support open graph from oss

---

flex/utils/result.h
flex/utils/service_utils.h
python/graphscope/gsctl/scripts/install_deps.sh

Fix building interactive in manylinux image.

fix(interactive): Fix building interactive on Manylinux2014

---

.github/workflows/build-graphscope-dev-images.yml
.github/workflows/build-graphscope-images-linux.yml
.github/workflows/build-graphscope-manylinux-images.yml
.github/workflows/build-graphscope-wheels-linux.yml
.github/workflows/build-graphscope-wheels-macos.yml
.github/workflows/docs.yml
.github/workflows/interactive.yml
.github/workflows/k8s-ci.yml
.github/workflows/local-ci.yml
.github/workflows/networkx-forward-algo-nightly.yml
.github/workflows/nightly.yml
.github/workflows/pegasus.yml
.github/workflows/pr-check.yml
.github/workflows/release.yml
flex/engines/graph_db/database/graph_db.cc
k8s/dockerfiles/coordinator.Dockerfile
k8s/dockerfiles/learning.Dockerfile
python/requirements.txt

- Check nullptr for `SesionLocalContext` destruction
- Use ubuntu-22.04 since [ubuntu-20.04 is deprecated](https://github.com/actions/runner-images/issues/11101)
- Use neo4j 5.21.0, it is the oldest version of neo4j which could be successfully installed on ubuntu22, python 3.10

fix(interactive): Check nullptr for `SesionLocalContext` destruction

---

.github/workflows/pr-check.yml

Incompatible error on ubuntu-latest runner.

fix: Use python3.10 to run pr-check

---

charts/graphscope-store/templates/portal/statefulset.yaml

Use the correct environment variable.

fix(coordinator): Fix coordinator persistence in k8s deployment

---

README.md

docs: GraphScope breaking LDBC record!

---

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/utils/ClassUtils.java
interactive_engine/compiler/src/main/java/com/alibaba/graphscope/sdk/PlanUtils.java
interactive_engine/compiler/src/test/java/com/alibaba/graphscope/sdk/JNICompilePlanTest.java

fix(interactive): Add JNI Logging

---

.devcontainer/devcontainer.json
interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/CommonConfig.java
interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/KafkaConfig.java
interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/ZkConfig.java
interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/meta/ServerDiscoverMode.java
interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/GrootClient.java
interactive_engine/groot-http/src/test/java/com/alibaba/graphscope/groot/OpenApiGeneratorApplicationTests.java
interactive_engine/groot-module/README-zh.md
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/CuratorUtils.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/ClientService.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/FrontendStoreClient.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/meta/DefaultMetaService.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/FrontendStoreService.java
interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/StoreService.java
interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/MaxNode.java
proto/groot/frontend_store_service.proto
proto/groot/sdk/client_service.proto
proto/groot/sdk/model.proto

support zk kafka discovery by local file
support control secondary catch up
support compact specific partition
Fixes -> new feature

fix(interactive): file mode discovery ; support control secondary catch up ； support compact specific partition
