scripts/prepare_dev.sh, scripts/prepare_env.sh
Make `prepare_env.sh` more verbose.
This pr could help #3, but doesn't fix it.
=> Show commands when running `prepare_env.sh`, to help users diagnose the errors. 

.github/workflows/ci.yml, .github/workflows/docs.yml, k8s/graphscope.Dockerfile, k8s/manager.Dockerfile
Removes the needs of permission push to registry from PR workflow.
1. Use artifact instead of registry push-and-pull to transfer image between jobs.
2. Remove unused environment variables
3. Reduce the time in Build Image stage by not build unnecessary executables.
4. Reduce logs that are too verbose.
5. Add cache for pip packages.
=> Enable workflow from pr

python/graphscope/deploy/kubernetes/resource_builder.py
Wait etcd endpoint ready for curl before launching vineyardd, to resolve the "failed to connect to vineyardd" issue.
None
=> Wait etcd ready before launching vineyard container.

python/graphscope/client/session.py
Provide configurable parameters for connecting to remote k8s, which strongly relies on the `kube_config.new_client_from_config` function.
eg:
```python
import graphscope
k8s_client_config = {"config_file": "./kube_config", "context": None, "persist_config": True}
sess = graphscope.session(k8s_client_config=k8s_client_config)
```
Fixes #37
=> Add: provide configurable parameters for connecting to remote k8s.(#37)

python/graphscope/deploy/tests/test_demo_script.py, python/graphscope/interactive/query.py
Support bytecode-based requests for interactive engine.
User can get a `GraphTraversalSource` to traversal a remote graph by using `interactive.traversal_source()` where `interactive` is created by `sess.gremlin(graph)`.
Examples:
```
>>> sess = graphscope.session()
>>> graph = load_modern_graph(sess, modern_graph_data_dir)
>>> interactive = sess.gremlin(graph)
>>> g = interactive.traversal_source()
>>> g.V().both()[1:3].toList()
[v[0.1], v[0.2]]
>>> g.V().both().name.toList()
['vadas', 'peter', 'lop', 'josh', 'marko', 'ripple']
```
Fixes #35
=> Support bytecode-based requests for interactive engine

analytical_engine/CMakeLists.txt, coordinator/gscoordinator/template/CMakeLists.template, interactive_engine/src/executor/runtime/native/CMakeLists.txt
Currently graphscope requires vineyard>=0.1.3. Otherwise there would be compliation error. This PR enforce the version constraint.
Fixes alibaba/libvineyard#106
=> Enforce vineyard version to find_package.

coordinator/gscoordinator/cluster.py, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/io_utils.py, coordinator/gscoordinator/utils.py, docs/reference/session.rst, k8s/kube_ssh, python/graphscope/__init__.py, python/graphscope/client/rpc.py, python/graphscope/client/session.py, python/graphscope/client/utils.py, python/graphscope/config.py, python/graphscope/deploy/kubernetes/cluster.py, python/graphscope/deploy/kubernetes/resource_builder.py, python/graphscope/deploy/kubernetes/utils.py, python/graphscope/deploy/tests/test_demo_script.py, python/graphscope/experimental/nx/tests/algorithms/forward/conftest.py, python/graphscope/experimental/nx/tests/classes/conftest.py, python/graphscope/experimental/nx/tests/conftest.py, python/graphscope/experimental/nx/tests/test_nx.py
- Print the process information when launching session
- Dump session status when launch failed even show_log is False
- Move `show_log` and `log_level` as a global configuration.
- Add graphscope.set_option and graphscope.get_option API
Fixes #7 
Fixes #27
=> Move session params show_log and log_level as a global configuration.

coordinator/gscoordinator/cluster.py, interactive_engine/deploy/docker/dockerfile/create_maxgraph_instance.sh
=> Extend gremlin pod expose to load-balancer

analytical_engine/CMakeLists.txt
When GraphScope is used as a submodule, and directories outside GraphScope is symbolic link, cmake install directory will simply copy that link to destination instead of its content.
This PR will resolve real path for those links and the install will works as expected.
=> Fix errors when install symbolic linked directory

README-zh.md, README.md, analytical_engine/README-zh.md, analytical_engine/README.md, interactive_engine/README-zh.md, interactive_engine/README.md, learning_engine/README-zh.md, learning_engine/README.md
=> Update badges for en/zh docs.

analytical_engine/core/loader/arrow_fragment_loader.h
Along with alibaba/libvineyard#159, but shouldn't break anything.
=> Fix loading from streams when there's worker that receives no chunks

README-zh.md, README.md, coordinator/gscoordinator/cluster.py, coordinator/gscoordinator/coordinator.py, demo/node_classification_on_citation.ipynb, interactive_engine/tests/function_test.sh, python/graphscope/client/session.py, python/graphscope/config.py, python/graphscope/deploy/kubernetes/cluster.py, python/graphscope/deploy/kubernetes/resource_builder.py, python/graphscope/deploy/tests/test_demo_script.py, scripts/test.sh
=> Parameterized k8s volume mount in session config

README.md, docs/installation.rst, docs/zh/installation.rst, scripts/prepare_env.sh
check os compatibility and dependencies_version in prepare_env.sh to improve "Getting Started" experience
Fixes #93
=> check os compatibility and dependencies_version in prepare_env.sh

k8s/gsvineyard.Dockerfile, python/graphscope/client/session.py, python/graphscope/config.py, python/graphscope/deploy/kubernetes/resource_builder.py
=> Fix passing zookeeper memory to etcd

.github/workflows/ci.yml, python/requirements.txt
That is introduced in https://github.com/alibaba/GraphScope/pull/103.
=> Requires vineyard-io, and drop the copy hack.

analytical_engine/core/loader/arrow_fragment_loader.h, analytical_engine/core/object/fragment_wrapper.h, analytical_engine/frame/property_graph_frame.cc, interactive_engine/src/executor/runtime/native/property_graph_stream.cc, interactive_engine/src/executor/runtime/native/property_graph_stream.h, k8s/gsvineyard.Dockerfile
And rebuild the graphscope image.
N/A
=> Fixes the global property graph stream for subgraph.

python/graphscope/framework/dag_utils.py, python/tests/conftest.py, python/tests/test_app.py
This PR fixed `string` not recognized in some frame files cause the `std` prefix is not there.
But when digging deep in whether all apps could run on graph which use string as original id, it seems that most apps will error out when quering. The reason includes 1. AutoWorkers cannot send string messages. 2. Some apps are not designed with support string in mind, so weird error happens, etc. These require a more careful case by case study.
=> Fix compile app with graph which use string as original id.

interactive_engine/tests/function_test.sh, python/graphscope/client/session.py, python/graphscope/deploy/kubernetes/cluster.py, python/graphscope/deploy/kubernetes/utils.py, python/graphscope/deploy/tests/test_demo_script.py, python/requirements.txt, python/tests/conftest.py, python/tests/test_scalability.py, python/tests/test_session.py, tutorials/6_unsupervised_learning_with_graphsage.ipynb, tutorials/7_supervised_learning_with_gcn.ipynb, tutorials/zh/6_unsupervised_learning_with_graphsage.ipynb, tutorials/zh/7_supervised_learning_with_gcn.ipynb
Minikube can not be deployed with non-driver in mac OS,  so we deprecate the k8s_minikube_vm_driver in session which is a bit hacky.
This PR also fixes #54 #106 
Fixes #54 #106 #114
=> Deprecated 'k8s_minikube_vm_driver' parameter in session.

interactive_engine/src/executor/runtime/src/dataflow/operator/sourcestep/builder.rs
Description
-----------
GIE scan all vertices unnecessarily for a simple query like `g.V().has('label','id', xxx).out()`.
It should use primary key to find the exact vertex.
Relational Context
------------------
This bug was found in an experiment of an industrial paper, where some simple query cost too much time to execute.
=> optimize source chain operator

coordinator/gscoordinator/cluster.py, interactive_engine/tests/function_test.sh, python/graphscope/client/session.py, python/graphscope/deploy/kubernetes/resource_builder.py
This pr also addresses problem #136. Now we can mount the same PVC with RWX mode between engine's pod and notebook server's pod
Fixes #154
=> Generalize k8s_volumes and support mount pvc

python/graphscope/learning/graph.py
put config to handle in get_handle; user can use get_handle to launch multiple learning workers
=> put config to handle in get_handle

coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/utils.py, k8s/graphscope.Dockerfile, k8s/precompile.py, python/graphscope/experimental/nx/classes/graph.py, python/graphscope/framework/app.py, python/graphscope/framework/dag_utils.py, python/graphscope/framework/graph.py
In order to reduce the response time of user statements such as load graph and querying apps.
Also revised the logic of signature computation and cache discovery.
Fixes #137
=> Pre-compile a set of graphs / apps in docker-build stage.

python/graphscope/experimental/nx/classes/digraph.py, python/graphscope/experimental/nx/classes/graph.py, python/graphscope/framework/app.py, python/graphscope/framework/context.py, python/graphscope/framework/graph.py, python/graphscope/framework/graph_schema.py, python/graphscope/interactive/query.py
Override `__repr__` and `__str__` for commonly used objects such as `Graph`, `App`, `Context`, etc. 
Now it's more easier to inspect informations about those objects.
Fixes #164
=> Print useful information for commonly used objects.

.github/workflows/ci.yml, analytical_engine/CMakeLists.txt, analytical_engine/core/fragment/dynamic_fragment.h, analytical_engine/core/grape_instance.cc, analytical_engine/core/grape_instance.h, analytical_engine/core/loader/arrow_fragment_loader.h, analytical_engine/core/object/fragment_wrapper.h, analytical_engine/core/object/graph_utils.h, analytical_engine/frame/property_graph_frame.cc, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/template/CMakeLists.template, docs/reference/graph.rst, interactive_engine/src/executor/runtime/native/CMakeLists.txt, k8s/graphscope.Dockerfile, k8s/gsvineyard.Dockerfile, proto/graph_def.proto, proto/types.proto, python/graphscope/__init__.py, python/graphscope/deploy/tests/test_demo_script.py, python/graphscope/experimental/nx/classes/graph.py, python/graphscope/experimental/nx/tests/test_nx.py, python/graphscope/framework/dag_utils.py, python/graphscope/framework/graph.py, python/graphscope/framework/graph_builder.py, python/graphscope/framework/graph_utils.py, python/requirements.txt
Add edges to existing graph.
Must merge alibaba/libvineyard#222 first and make a image.
=> Add edges to existing graph.

.github/workflows/ci.yml, python/graphscope/framework/graph.py, python/tests/test_graph.py
1. Add relationship check for `project_to_simple`, and some test cases.
2. Make `project_to_simple` more concise.
3. Add graph type check for `graph.to_numpy` and `graph.to_dataframe`.
4. Always clean up temporal image in CI.
=> Refine project_to_simple method.

coordinator/gscoordinator/coordinator.py, python/graphscope/client/session.py
This pr is a fix when `ctrl-c` will kill the analytical engine after session launched in python interpreter with  `run_on_local` mode.
Also, Add `SIGTERM` signal handle In coordinator to stop graceful. 
Fixes #178
=> [Bugfix]: Stop propgagating signal to coordinator subprocess

coordinator/gscoordinator/cluster.py, coordinator/gscoordinator/coordinator.py, python/graphscope/client/session.py, python/graphscope/config.py, python/graphscope/deploy/kubernetes/cluster.py, python/graphscope/deploy/kubernetes/resource_builder.py
Deploy 3 pods of ETCD in graphscope cluster to leverage its failure tolerance abilities.
Fixes #185
=> Distributed ETCD with 3 pods.

coordinator/gscoordinator/coordinator.py, proto/message.proto, python/graphscope/client/rpc.py, python/graphscope/client/session.py, python/graphscope/framework/graph.py
Support reconnect to the coordinator service in `addr` mode when session quit accidentally.
```python
import graphscope
graphscope.set_option(dangling_timeout_seconds=60)
sess = graphscope.session(addr='<ip>:<port>')
sess = graphscope.session(addr='<ip>:<port>')
```
This PR also fix problem of creating `interactive_query` pod asynchronously after loading graph.
Fixes #195
=> support dangling handle for each session connection

analytical_engine/CMakeLists.txt, analytical_engine/apps/pregel/louvain/auxiliary.h, analytical_engine/apps/pregel/louvain/louvain.h, analytical_engine/apps/pregel/louvain/louvain_app_base.h, analytical_engine/apps/pregel/louvain/louvain_context.h, analytical_engine/apps/pregel/louvain/louvain_vertex.h, analytical_engine/core/app/pregel/pregel_app_base.h, analytical_engine/core/app/pregel/pregel_compute_context.h, analytical_engine/core/app/pregel/pregel_vertex.h, analytical_engine/core/fragment/arrow_projected_fragment.h, coordinator/gscoordinator/builtin/app/.gs_conf.yaml, python/graphscope/analytical/app/__init__.py, python/graphscope/analytical/app/louvain.py, python/tests/test_app.py
implement a distributed louvain algorithm
Fixes #182
=> implement louvain algorithm

.github/workflows/ci.yml, charts/graphscope/templates/coordinator.yaml, charts/graphscope/templates/role_and_binding.yaml, charts/graphscope/templates/test/test-rpc.yaml
=> Add helm test

python/graphscope/framework/graph.py, python/graphscope/framework/graph_utils.py, python/graphscope/framework/loader.py, python/tests/test_create_graph.py
* Use None to select all property, and empty list to deselect all.
* Loader now accepts a `pathlib.Path` object.
* Add tests.
Related to #191
=> Use None to select all property, and empty list to deselect all.

.github/workflows/ci.yml, .github/workflows/graphscope.Dockerfile, k8s/graphscope.Dockerfile
Try to fixes the failed mars test.
I'm still not clear about the root cause, but that worth a quick fixes.
=> Fixes mars version to 35b44ed56e031c252e50373b88b85bd9f454332e.

docs/graph_transformation.rst, docs/reference/app.rst, python/graphscope/analytical/app/louvain.py, python/graphscope/framework/graph.py, python/tests/test_graph.py
- enrich the unit test of project
- add unit test for add_column
issue #206 
bugs need to fix:
=> enrich unitest of project and add_column

.github/workflows/ci.yml, .github/workflows/local.yml, analytical_engine/CMakeLists.txt, analytical_engine/core/grape_instance.cc, analytical_engine/core/grape_instance.h, analytical_engine/core/loader/arrow_fragment_loader.h, analytical_engine/core/object/graph_utils.h, analytical_engine/frame/property_graph_frame.cc, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/template/CMakeLists.template, interactive_engine/src/executor/runtime/native/CMakeLists.txt, k8s/graphscope.Dockerfile, k8s/gsvineyard.Dockerfile, k8s/ubuntu/gsvineyard.Dockerfile, proto/types.proto, python/graphscope/framework/dag_utils.py, python/graphscope/framework/graph.py, python/tests/test_graph.py, scripts/build.sh
Must be merged after alibaba/libvineyard#245
Related to #191
=> Support combine multiple add vertice and edges operation.

analytical_engine/core/fragment/dynamic_fragment.h, analytical_engine/core/grape_instance.cc, analytical_engine/core/grape_instance.h, analytical_engine/core/object/fragment_wrapper.h, analytical_engine/core/object/i_fragment_wrapper.h, proto/types.proto, python/graphscope/experimental/nx/classes/dicts.py, python/graphscope/experimental/nx/classes/graph.py, python/graphscope/experimental/nx/tests/classes/test_graph.py, python/graphscope/experimental/nx/tests/classes/test_graphviews.py, python/graphscope/experimental/nx/tests/test_nx.py, python/graphscope/framework/dag_utils.py, python/graphscope/framework/utils.py
- implement deepcopy version of netowrkx to_directed /to_undirected api;
- implement clear_edge of networkx Graph.
- open the related test cases.
#62
=> [networkx] implement clear_edges, deepcopy of to_directed and to_undirected api

analytical_engine/core/fragment/dynamic_fragment.h, analytical_engine/core/grape_instance.cc, analytical_engine/core/grape_instance.h, proto/types.proto, python/graphscope/experimental/nx/classes/graph.py, python/graphscope/experimental/nx/tests/algorithms/builtin/test_ctx_builtin.py, python/graphscope/experimental/nx/tests/classes/test_digraph.py, python/graphscope/experimental/nx/tests/classes/test_graph.py, python/graphscope/experimental/nx/tests/classes/test_graphviews.py, python/graphscope/framework/dag_utils.py
implement true subgraph/edge_subgraph in engine, not return a view.
#62 
todo:
=> [networkx] implement deepcopy subgraph/edge_subgraph in engine, not return a view

analytical_engine/core/fragment/dynamic_fragment.h, analytical_engine/core/fragment/dynamic_fragment_reporter.h, analytical_engine/core/fragment/dynamic_fragment_view.h, analytical_engine/core/grape_instance.cc, analytical_engine/core/grape_instance.h, proto/types.proto, python/graphscope/experimental/nx/classes/graph.py, python/graphscope/experimental/nx/tests/classes/test_graph.py, python/graphscope/framework/dag_utils.py, tutorials/2_graph_manipulations_with_networkx_compatible_apis.ipynb
- refact clear api by implement a ClearGraph in engine size.
- implement number_of_selfloops api and fix number_of_edges bug when graph contain selfloops
#62
=> [networkx] refact clear api and implment number_of_selfloops api

research/gaia/rustfmt.toml
rm unnecessary rustfmt.toml
Fixes #275
=> rm unnecessary rustfmt.toml

research/gaia/gremlin/gremlin_core/tests/early_stop_test.rs
update early stop test to two workers
Fixes #349
=> [GAIA]  update early stop test to two workers

python/graphscope/proto/__init__.py
As some other packages (i.e., `proto-plus-python`) may install a `proto` directory in the root path.
Fixes #400.
=> Ensure graphscope.proto preponderate over outside `proto` directory.

.github/workflows/ci.yml, .github/workflows/hadoop_scripts/prepare_hadoop.sh, interactive_engine/src/data_load_tools/README.md, interactive_engine/src/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/LoadTool.java, interactive_engine/src/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/DataBuildMapper.java, interactive_engine/src/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/OfflineBuild.java, interactive_engine/src/v2/src/main/java/com/alibaba/maxgraph/v2/store/StoreIngestService.java
add bulk load doc && some fix
#297
=> add doc && some fix

python/graphscope/client/session.py, python/graphscope/framework/graph.py, python/graphscope/nx/__init__.py, python/graphscope/nx/classes/digraph.py, python/graphscope/nx/classes/graph.py, python/graphscope/nx/convert.py, python/graphscope/nx/tests/classes/test_graph.py, python/graphscope/nx/tests/test_nx.py
Revise the networkx module import base on discussion in #303 
support two ways to import networkx module:
```python
import graphscope as nx 
nx = sess.nx()
```
if related session is not eager mode, raise Error.
#303 
Fixes
=> [networkx] Adapt the networkx import to eager/lazy session mode 

.github/workflows/local.yml
Try to fix the failure on master.
N/A.
=> Local CI: use latest vineyard (v0.2.4).

research/gaia/pegasus/pegasus/src/lib.rs, research/gaia/pegasus/server/Cargo.toml, research/gaia/pegasus/server/src/rpc.rs
return address when gaia started
#432
=> return address for jna

interactive_engine/src/executor/runtime/src/store/ffi.rs, interactive_engine/src/executor/runtime/src/store/v2/global_graph.rs, interactive_engine/src/executor/store/src/api/graph_partition.rs
Add a function in GraphPartitionManager for GAIA Integration: 
`fn get_server_id(&self, pid: PartitionId) -> i32;`
=> [graphscope] add mapping of partition id to server id in GraphPartitionManager

python/graphscope/client/session.py, python/tests/test_session.py
This PR enables `with` keyword in session, which can automatically release resourced when the context manager exits.
Moreover, use `with` will automatically set the session as the default session.
Two simple test cases has been added that can fully demonstrate its usage.
Fixes #393
=> Support `with` keyword in session

analytical_engine/core/loader/arrow_to_dynamic_converter.h, python/graphscope/nx/tests/test_nx.py
- no need to call the vertex map construct, since every worker has the complete global vertex map.
=> Fix string oid graph transformation bug

python/requirements.txt
can reproduce with NetworkX 2.6.1 and decorator 4.4.2
```python
from networkx.utils.decorators import not_implemented_for
@not_implemented_for("directed")
def sp_function(G):
pass
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-b6e5bef0b8d8> in <module>
----> 1 @not_implemented_for("directed")
2 def sp_function(G):
3     pass
4
~/.local/anaconda3/envs/graphscope/lib/python3.8/site-packages/networkx/utils/decorators.py in not_implemented_for(*graph_types)
89         return g
90
---> 91     return argmap(_not_implemented_for, 0)
92
93
TypeError: __init__() missing 1 required keyword-only argument: 'try_finally'
```
=> Set decorator>=5.0.5 since it's old version(4.4.2) may not compatible with NetworkX latest release

k8s/gsruntime.Dockerfile, python/graphscope/nx/tests/algorithms/builtin/test_shortest_paths.py, python/graphscope/nx/utils/compat.py
Its `__init__` has following signature
```
class argmap:
def __init__(self, func, *args, try_finally=False):
```
and we cannot handle that currently.
Follow-up work for #507.
=> Fixes the copy_class hack for `argmap` in networkx.

.github/workflows/mac.yml, Makefile, interactive_engine/src/common/rust/common/src/util/ip.rs, interactive_engine/src/executor/runtime/src/bin/executor.rs, python/tests/test_run_locally.py, scripts/install_dependencies.sh
=> Add a local deploy and test ci on MacOS

.github/workflows/mac.yml, scripts/install_dependencies.sh
In MacOS runner image version 20210712.4, the llvm@9 we use in ci thinks 'preadv' and 'pwritev' is enable to use but it's available until MacOS 11.0, so we downgrade  llvm to 8.
=> Fix macOS ci: change to llvm 8

.github/workflows/local.yml, scripts/deploy_local.sh
Fixes CI failure: https://github.com/alibaba/GraphScope/runs/3101487940?check_suite_focus=true
=> Install the inplace vineyard-io as well.

python/graphscope/client/session.py, python/graphscope/deploy/hosts/cluster.py
The reason for the Local-CI failure is timeout when waiting for stopping vineyard in coordinator.
=> Fix local CI by catching exception in sess.close

research/gaia/dyn_type/src/error.rs, research/gaia/dyn_type/src/object.rs, research/gaia/dyn_type/src/serde.rs, research/gaia/gremlin/gremlin_core/src/result_process.rs
Fix a bug in where step, e.g.,  g.V(-1).as('a').out().in().where(eq('a')). 
The reason is that in where step, it will set the expected value (i.e., global id referred by tag 'a') as a type of Object (in this case it is Object::Blob). However, when it comes to comparing with the output of in() step, we have the actual global_id of type u128, and the type inference in rust will also regard the expected value as u128. Thus, the bug occurs when we try to get Object::Blob value as a u128 value.
The solution is to add u128 as a primitive in Object, since it is commonly used in runtime (as it is the type of global id).
Fixes
=> [Bug Fix]: add u128 in Primitive in Object

interactive_engine/src/executor/runtime/native/htap_ds_impl.cc, interactive_engine/src/executor/runtime/src/store/ffi.rs, research/gaia/gremlin/gs_gremlin/src/graph_proxy/partitioner.rs
1. fix bug in: `g.V().has("author", "id", 2)`, where query is not processed by dataflow (since it only needs to query storage)
2. fix bug in:  `g.V().has("author", "id", 2).out("writes")`, by implementing get_property() and get_properties() as returning null results rather than unimplement!() for IdOnlyVertex in vineyard
#641
=> [Bug Fix] Fix bugs in CI of GAIA on Vineyard

analytical_engine/apps/pregel/louvain/louvain.h, analytical_engine/apps/pregel/louvain/louvain_vertex.h
Fix stuck when the in-degree or out-degree of some vertex is very large.
=> Improve calculateQ efficiency

python/graphscope/client/session.py, python/graphscope/interactive/graph_traversal.py, python/graphscope/interactive/query.py
Drop the "global variable" hack.
N/A
=> Assocate the interactive query instance to Traversal object.

.github/workflows/ci.yml, .github/workflows/docker_nightly.yml, python/graphscope/nx/tests/conftest.py
- fix docker nightly ci with short sha
- make graphscope_session scope to `module` to fix #528
=> Fix docker-nightly ci with short sha

analytical_engine/core/fragment/append_only_arrow_fragment.h, analytical_engine/core/fragment/arrow_projected_fragment.h, analytical_engine/core/vertex_map/arrow_projected_vertex_map.h
The static `Create()` method returns a `std::unique_ptr` instead.
N/A
=> Adapt to latest vineyard: the `Create()` API has changed.

.github/workflows/docs.yml
We previously expect maintainers push the "release" commit and "tag" to the main branch at the same time, but seems we don't do in that way.
This commit pushes docs for tags as well to ensure docs for our releases are pushed to gh-pages branch as expected.
=> Push docs for tags as well.

analytical_engine/core/grape_engine.cc, coordinator/gscoordinator/cluster.py, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/launcher.py, proto/message.proto, python/graphscope/client/rpc.py, python/graphscope/deploy/hosts/cluster.py
- This pull request revise the fetch log implement of client tp get stdout and stderr log separately. 
- In engine side, we use a RedirectLogSink to process LOG(ERROR) and OTHERS LOG of glog separately.
Fixes #729
=> Fetch stdout and stderr log of grape engine separately

analytical_engine/core/context/column.h, analytical_engine/core/context/selector.h, analytical_engine/core/grape_instance.cc, analytical_engine/core/object/fragment_wrapper.h, analytical_engine/core/object/graph_utils.h, analytical_engine/core/object/gs_object.h, analytical_engine/core/server/analytical_server.cc, analytical_engine/core/server/graphscope_service.cc, analytical_engine/frame/project_frame.cc, analytical_engine/frame/property_graph_frame.cc, coordinator/gscoordinator/cluster.py, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/launcher.py, coordinator/gscoordinator/utils.py, proto/message.proto, python/graphscope/client/connection.py, python/graphscope/client/rpc.py, python/graphscope/client/session.py, python/graphscope/deploy/hosts/cluster.py, python/graphscope/deploy/kubernetes/cluster.py, python/graphscope/deploy/launcher.py, python/graphscope/framework/errors.py, python/graphscope/nx/tests/test_nx.py, python/tests/unittest/test_app.py
This PR does the following:
1. In analytical server side when something wrong happens, return a GRPC Status with a StatusCode indicating error kinds and details messages (which will in `INTERNAL` for most of cases),
2. In coordinator we catch all exceptions or responses in engines, do some work, and set the error code and dump exception details in response,
3. For rpc calls other than `RunStep` (which is much simple) we set context codes and details, so we can eliminate the ResponseStatus in most of protos,
4. Revised error messages that will be carried to make it more intuitive,
5. Check for coordinator status in initializing stage,
6. separate coordinator failure from analytical engine failure in heartbeat code.
=> Revise error messages and handling of GRPC exception.

.github/workflows/ci.yml, .github/workflows/graphscope-store.Dockerfile, .github/workflows/graphscope.Dockerfile, .github/workflows/local.yml, Makefile, analytical_engine/CMakeLists.txt, analytical_engine/benchmarks/apps/bfs/bfs.h, analytical_engine/benchmarks/apps/bfs/property_bfs.h, analytical_engine/benchmarks/apps/sssp/property_sssp.h, analytical_engine/benchmarks/apps/sssp/sssp.h, analytical_engine/benchmarks/apps/wcc/property_wcc.h, analytical_engine/benchmarks/apps/wcc/wcc.h, coordinator/gscoordinator/template/CMakeLists.template, docs/deployment.rst, docs/developer_guide.rst, docs/zh/deployment.rst, docs/zh/developer_guide.rst, interactive_engine/src/executor/runtime/native/CMakeLists.txt, interactive_engine/src/executor/runtime/native/graph_builder_ffi.cc, interactive_engine/src/executor/runtime/native/property_graph_stream.h, k8s/graphscope-store.Dockerfile, k8s/graphscope.Dockerfile, k8s/gsvineyard.Dockerfile, k8s/precompile.py, k8s/ubuntu/gsvineyard.Dockerfile, python/graphscope/analytical/app/sssp.py, scripts/deploy_local.sh
Fixes #770 
Fixes #762
Fixes #726 
Fixes #755
=> Install GraphScope into /opt/graphscope and link to the /usr/local

interactive_engine/conf/log4rs.yml, interactive_engine/distribution/src/bin/store_ctl.sh, interactive_engine/distribution/src/conf/log4rs.yml, interactive_engine/distribution/src/conf/logback.xml, interactive_engine/distribution/src/conf/logback_debug.xml
- the log4rs.yml has been unified in [commit](https://github.com/alibaba/GraphScope/commit/032ed994a874525f55cf16f7bd05462cccbb491c). Since the `store-ctl` has been separate from `giectl`,  the log4rs.yml need to be recovered too.
- fix the log output location of `logback.yml` and `log4rs.yml`
Fixes #813
=> Recover log4rs.yml of graphscope-store and fix the log output location

interactive_engine/src/gaia-adaptor/gremlin_test.sh
add data cache clean in gremlin_test.sh to avoid failed when we manually run the test.
Fixes #661
=> Fix: add  data cache clean in gremlin_test.sh

.github/workflows/ci.yml, analytical_engine/CMakeLists.txt, analytical_engine/core/loader/arrow_fragment_loader.h, coordinator/gscoordinator/template/CMakeLists.template, interactive_engine/src/executor/runtime/native/CMakeLists.txt, k8s/graphscope-store.Dockerfile, k8s/graphscope.Dockerfile, k8s/gsvineyard.Dockerfile, k8s/ubuntu/gsvineyard.Dockerfile, python/graphscope/framework/graph.py, python/tests/unittest/test_context.py, python/tests/unittest/test_create_graph.py, python/tests/unittest/test_graph.py, python/tests/unittest/test_session.py, scripts/deploy_local.sh
Now the `add_edges` will always deduce the vertex tables when not found in existed labels
Fixes #727
=> Make the `add_edges` behavior more Pythonic

analytical_engine/core/launcher.cc
Using vineyardd in the python package, in preparing for graphscope.wheel.
N/A
=> Launch vineyard in a nicer way when vineyardd not found.

python/requirements.txt
Followup revision for #780, fixes #779 in a nicer way.
Fixes #779.
=> Require vineyard (for serialization test, etc.), but only on x86_64.

.github/workflows/ci.yml, charts/graphscope-store/templates/frontend/statefulset.yaml, charts/graphscope-store/values.yaml
Add readinessProbe to graphscope-store frontend, to ensure the service remains unavailable until the GRPC service is started.
Now we can rely on helm test, the sleep trick in `ci.yml` has been removed.
Fixes #785
=> Add readiness probe to graphscope-store frontend.

.github/workflows/cancel.yaml, k8s/Makefile, k8s/ubuntu/gsvineyard.Dockerfile, scripts/deploy_local.sh
Seems that there are conflicts between brew installed glog, and the `libc++.dylib`
in `/usr/local/opt/llvm/lib`.
The issue is tracked as v6d-io/v6d#565
Fixes v6d-io/v6d#565
=> Don't export `/usr/local/opt/llvm/lib` to linker search path on MacOS.

python/graphscope/dataset/ogbn_arxiv.py, python/tests/unittest/test_download.py
Add the arxiv dataset to graphscope sample datasets.
The arxiv datasets contains 2 files, one is nodes.csv, which have 130 properties,
and one is edge.csv, which is the mapping between nodes.
Partially address #776
=> Add arxiv dataset

.github/workflows/build-graphscope-wheels-linux.yml, .github/workflows/build-graphscope-wheels-macos.yml, .github/workflows/ci.yml, Makefile, analytical_engine/CMakeLists.txt, coordinator/foo/__init__.py, coordinator/gscoordinator/launcher.py, coordinator/gscoordinator/template/CMakeLists.template, coordinator/requirements.txt, coordinator/setup.py, interactive_engine/assembly/bin/giectl, k8s/Makefile, k8s/graphscope-store.Dockerfile, k8s/graphscope.Dockerfile, k8s/gsvineyard.Dockerfile, k8s/jupyter.Dockerfile, k8s/ubuntu/gsvineyard.Dockerfile, python/requirements.txt, scripts/install_deps.sh
For shrink the package size less than "100M", we split graphscope into
- `gs-scoordinator`: include python releated code of gscoordinator
- `gs-lib`: lib dir exclude jython-standalone-**.jar
- `gs-jython`: only jython-standalone-**.jar, cause this jar is 40M
-  `gs-include`: header files
- `gs-engine`: other runtime info such as 'bin', 'conf', and 'include'
Fixes #959
=> Shrink wheel size by split graphscope package

analytical_engine/core/fragment/arrow_projected_fragment.h
Arrow_projected_fragment causes a bug. When `edge_prop_` is -1. (A graph with no edge property).
https://github.com/alibaba/GraphScope/blob/699eea6cc187bdfaf9d5371ae5c5ba7b25963ffc/analytical_engine/core/fragment/arrow_projected_fragment.h#L573-L577
will set `edge_data_array_` to `nullptr`(correct)
https://github.com/alibaba/GraphScope/blob/699eea6cc187bdfaf9d5371ae5c5ba7b25963ffc/analytical_engine/core/fragment/arrow_projected_fragment.h#L686-L688
Unfortunately, a general method `GetEdgeNum()` will reference `edge_data_array_` without check.
=> [Bug Fix] fix nullptr in arrow_projected_fragment.h

interactive_engine/executor/runtime/native/graph_builder_ffi.cc, interactive_engine/executor/runtime/native/property_graph_stream.cc
(As seems no one is familiar with the rust-side codebase, we workaround the issue the FFI wrapper).
Fixes the errors in #973 when subgraph op involved, where users feed `vid_field` to prorperies, causing (which will be finally addressed by #1022), and there are `null` columns in the input, causing missing property when feed v/e tables to vineyard to construct the subgraphs.
Fixes #973
=> Subgraph: allow empty properties and duplicate properties.

python/graphscope/framework/app.py
It is quite strange that builtin gars accept a `context` argument for context type, but when loading custom gars it is not allowed.
When there's a `context_type` entry in the gar config, it would still be overwrite, but we need to check if the value is available first.
N/A
=> Allow feed a `context_type` when loading custom gars.

coordinator/gscoordinator/utils.py
=> Set OPAL_PREFIX in CMAKE_PREFIX_PATH to find MPI

charts/graphscope-store/templates/coordinator/statefulset.yaml, charts/graphscope-store/templates/store/statefulset.yaml
I think this could fix the below problems:
1. `statefulset.apps/graphscope-store-store`
```
Caused by: java.nio.file.AccessDeniedException: /var/lib/graphscope-store/8
```
2. `statefulset.apps/graphscope-store-coordinator`
```
Caused by: java.nio.file.AccessDeniedException: /etc/graphscope-store/my.meta/query_snapshot_info
```
=> Charts: Fix the GraphScope store mount volume permission issue

analytical_engine/core/app/app_invoker.h, analytical_engine/core/io/property_parser.h, analytical_engine/core/object/app_entry.h, analytical_engine/frame/app_frame.cc, analytical_engine/frame/cython_app_frame.cc, analytical_engine/frame/cython_pie_app_frame.cc, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/io_utils.py, python/graphscope/analytical/udf/wrapper.py, python/graphscope/deploy/hosts/cluster.py, python/graphscope/framework/app.py, python/graphscope/framework/errors.py, python/graphscope/framework/utils.py, python/graphscope/tests/unittest/test_udf_app.py
This PR fixes several issues about exceptions,
1. We have `CHECK_OR_RAISE(args_num == query_args.args_size());` but it still succeeds (and returns a uninitialized context) on client-side, as the error is not propogated from app frame to GAE engine.
2. Eliminates the too deep nested stack when printing `AnalyticalEngineInternalError`s, as it is hard to understand.
3. A `_ReprableString` is used to ensure `\n` are rendered in our exceptions to make it more readable.
None
=> Fixes the error printing, and propogate errors in `Query` to client.

CONTRIBUTING.md, analytical_engine/README-zh.md, analytical_engine/README.md, docs/interactive_engine.rst, docs/zh/interactive_engine.rst, k8s/Makefile, k8s/gsvineyard.Dockerfile, k8s/ubuntu/gsvineyard.Dockerfile, python/graphscope/framework/loader.py, scripts/install_deps.sh
To keep things consistent.
N/A
=> Rename occurances of repository name "libvineyard" to "v6d".

analytical_engine/core/grape_instance.cc, coordinator/gscoordinator/utils.py, docs/reference/gnn_engine/graph_query_en.rst, docs/reference/gnn_engine/quick_start_en.rst, python/graphscope/analytical/app/sssp.py, python/graphscope/framework/context.py, python/graphscope/framework/graph_schema.py, python/graphscope/tests/unittest/test_app.py, python/graphscope/tests/unittest/test_lazy.py
1. More rigid input validation for selector
2. Use `pd.Series` and `pd.MultiIndex` to pretty print the schema
3. Fix a bug that context type of property sssp doesn't consistent across Python and C++
Schema example:
* VertexData
```python
>>> ret.schema
type  property
v     id            v.id
data        v.data
r                      r
```
* VertexProperty
```ipython
>>> ret.schema
type  property
v     id            v.id
data        v.data
r     auth        r.auth
hub          r.hub
```
* LabeledVertexData
```ipython
>>> ret.schema
type  label     property
v     person    id                v:person.id
name            v:person.name
age              v:person.age
software  id              v:software.id
name          v:software.name
lang          v:software.lang
r     person …
```
=> Enhanced input validation and schema representation

.github/workflows/nightly.yml
=> Upload codecover report only in ubuntu20 platform

docs/persistent_graph_store.rst
Fixed a typo in `persistent_graph_store.rst` by renaming the deprecated API `partition_by` to `add_primary_key`.
=> 修改为新的add_primary_key

docs/persistent_graph_store.rst
1. renaming the deprecated API `from` to `source`, `to` to `destination`
2. a doc typo 
Fixes
=> fix some typo in persistent_graph_store.rst

.github/workflows/ci.yml, .github/workflows/gae.yml, .github/workflows/gss.yml, .github/workflows/networkx-forward-algo-nightly.yml, analytical_engine/CMakeLists.txt, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/io_utils.py, coordinator/requirements.txt, k8s/Makefile, k8s/graphscope-dev.Dockerfile, k8s/graphscope-store.Dockerfile, k8s/graphscope.Dockerfile, k8s/gsvineyard.Dockerfile, k8s/ubuntu/gsvineyard.Dockerfile, python/graphscope/framework/utils.py, python/graphscope/tests/kubernetes/test_demo_script.py, python/graphscope/tests/unittest/test_context.py, python/requirements.txt, scripts/install_deps.sh
Upgrade vineyard to v0.3.14 to leverage the new IO adaptors to make hdfs IO works.
Fixes #1183
=> Bump up required vineyard version to v0.3.14 and reable HDFS IO tests.

python/graphscope/deploy/kubernetes/resource_builder.py
I just increased the ETCD pods default `livenessProbe.periodSeconds` from `2` to `10`,
with the previous config
`periodSeconds * failureThreshold = 2 * 8 = 16` is a bit small~
=> etcd: Increate the ETCD pods period seconds

analytical_engine/core/utils/transform_utils.h, python/graphscope/nx/tests/test_ctx_builtin.py
Fix an error when selecting from empty graph by setting the corresponding numpy dtype of `folly::NULLT` to `np.dtype('void')`.
Fixes #1194
=> Fix error when selecting from empty graph

.github/workflows/ci.yml, coordinator/gscoordinator/cluster.py, k8s/graphscope-dev.Dockerfile, k8s/graphscope.Dockerfile, python/graphscope/config.py, python/graphscope/deploy/kubernetes/resource_builder.py, python/graphscope/deploy/kubernetes/utils.py, python/graphscope/tests/kubernetes/test_with_mars.py
The mars's web session is expose to the client, the default session won't work as we use the `fixed` backend for services when launching mars's scheduler.
The mars test is disable by default on CI, and can be enabled by export a environment variable `WITH_MARS`. The test case has been manually validated.
N/A
=> Bring back mars support, re-enable mars test in CI, and fixes several related issues.

analytical_engine/apps/bfs/bfs_generic.h, analytical_engine/core/grape_instance.cc
Fix the build error when `NETWORKX=OFF`
Remove a warning.
=> Guard folly headers when NETWORKX=OFF

.github/workflows/build-graphscope-wheels-linux.yml, .github/workflows/build-graphscope-wheels-macos.yml, README-zh.md, coordinator/setup.py, docs/frequently_asked_questions.rst, docs/installation.rst, docs/zh/installation.rst, python/graphscope/__init__.py, scripts/install_deps.sh
since the NetworkX dependency has been bump up to 2.6 and it has droped support for Python3.6,  the GraphScope should drop support for python 3.6.
Fixes #1269
=> Drop support for Python 3.6

docs/_templates/css/custom.css, docs/conf.py, docs/reference/networkx/graphs.rst, docs/reference/networkx/transformation.rst
Remove the `vineyard` module from the mock import to ensure the doc could be generated.
This PR fixes a bug of the scroll bar on small screens (macbook 13) as well.
Fixes N/A
=> Fixes building docs for graphlearning, and the scroll bar.

analytical_engine/core/loader/arrow_fragment_loader.h
This allows the user to pass zero vertex tables or edge tables from command-line.
=> Check the nullptr of graph_info_

docs/reference/cython_sdk.rst
loading_graph.rst: Context.superstep() change return type str -> int
Fixes
=> loading_graph.rst: Context.superstep() change return type str -> int

.github/workflows/build-graphscope-wheels-macos.yml, coordinator/gscoordinator/utils.py
=> Fix failure on macOS CI

.github/workflows/ci.yml, analytical_engine/core/app/pregel/pregel_vertex.h, python/graphscope/nx/tests/classes/test_graphviews.py, python/graphscope/tests/kubernetes/test_demo_script.py
`std::to_string` doesn't have the `std::to_string(std::string)` overload, thus when used with string id fragment, it will error out.
=> Use boost::lexical_cast to handle string id fragment

analytical_engine/CMakeLists.txt, scripts/install_deps.sh
GraphScope can't compile with vineyard v0.3.18, the required version appears to have been forgotten to update.
The other locations of vineyard version are v0.3.19 already.
=> Upgrade required vineyard version to 0.3.19

analytical_engine/exported_symbols_osx.lds, k8s/Makefile
Possible fixes the ci failure on Mac.
=> Keep the global symbol to avoid it been stripped on Mac.

.github/workflows/ci.yml, .github/workflows/gae.yml, .github/workflows/gaia.yml, .github/workflows/gss.yml
Limit the condition of ci actions to the `alibaba/graphscope` repo, as it may require self-hosted runners.
=> Limit the condition of ci actions to the alibaba/graphscope repo, as it may require self-hosted runners.

docs/reference/session.rst, python/graphscope/__init__.py, python/graphscope/client/session.py, python/graphscope/framework/graph.py, python/graphscope/tests/unittest/test_graph.py
```python
import graphscope
sess = graphscope.session()
graph = load_graph(sess)
sess.close()
print(g.loaded())
True
```
Fixes
=> Correct the lifecycle of graph with session

analytical_engine/core/fragment/dynamic_fragment.h
=> [BugFix] Fix analytical engine can't not compile with NETWORKX=OFF

interactive_engine/pom.xml, research/query_service/ir/compiler/pom.xml
Upgrade the `jackson.databind`, not `jackson`.
See also:
- https://github.com/alibaba/GraphScope/pull/1415
- https://github.com/alibaba/GraphScope/pull/1423
=> Upgrade the version of databind, fixes the dependent bot warnings.

interactive_engine/executor/store/Cargo.toml
=> migrate cargo rocksdb dependency to 0.18.0 version

coordinator/gscoordinator/coordinator.py, python/graphscope/client/session.py
1.Client cannot create coordinator which not compatible to it's version.
2.Coordinator throws an Exception when a not compatible client connect to it, and then the client throws it to user.
3.add a legacy doc of session param etcd_addrs.
Fixes #1435
=> Add version check to coordinator & client, fixes #1435

coordinator/gscoordinator/dag_manager.py, python/graphscope/client/session.py
Submitting empty DAG should not trigger some unhandled case such as no such attribute or index out of range.
=> Correctly handle the empty DAG

python/graphscope/framework/app.py, python/graphscope/framework/context.py, python/graphscope/framework/graph.py, python/graphscope/nx/tests/test_transformation.py, python/graphscope/tests/conftest.py, python/graphscope/tests/unittest/test_download.py, python/graphscope/tests/unittest/test_graph.py, python/graphscope/tests/unittest/test_java_app.py, python/graphscope/tests/unittest/test_lazy.py
- Use del rather than unload
- Projected graph now hold a reference to the base graph
Fixes #1394
=> Correctly handle the lifecycle of graph

python/graphscope/client/session.py, python/graphscope/config.py, python/graphscope/dataset/io_utils.py
Add backoff and retry mechanism with `urllib.request` rather than use [urllib3](https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py), as compared with [urllib3](https://urllib3.readthedocs.io/en/stable/), The `urllib` we used has the following advantages:
-  The `urlretrieve` in [urllib.request](https://docs.python.org/3/library/urllib.request.html) is a wrapper to copy a network object denoted by a URL to a local file, which doesn't have in `urllib3 (just a HTTP client)`
- support `reporthook` to display ProgressBar
Fixes #1391
=> Attempt backoff and retry during download dataset

coordinator/gscoordinator/coordinator.py
See also: https://github.com/alibaba/GraphScope/pull/1445
=> Add a lock in the coordinator's RunStep as well.

python/graphscope/client/session.py
E.g., warnings in https://github.com/alibaba/GraphScope/runs/6137579818?check_suite_focus=true
```
E0423 03:09:25.767161956   10235 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0423 03:09:29.762132882   10235 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
```
=> Suppress the grpc warnings in `fork_posix.cc`.

analytical_engine/core/grape_instance.cc, analytical_engine/core/grape_instance.h, analytical_engine/core/object/fragment_wrapper.h, analytical_engine/frame/project_frame.cc, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/dag_manager.py, coordinator/gscoordinator/utils.py, proto/graphscope/proto/types.proto, python/graphscope/framework/context.py, python/graphscope/framework/dag_utils.py
- Add another write path that uses the C++ IO adaptor
- Reduce some code duplication in `grape_instance.cc`
- Move ArrowFlattenProject related stuff out of the NETWORKX guard.
Fixes #1468
=> Add another write path that uses the C++ IO adaptor

python/graphscope/nx/classes/dict_factory.py, python/graphscope/nx/convert_matrix.py, python/graphscope/nx/tests/convert/test_convert.py, python/graphscope/nx/tests/convert/test_convert_numpy.py, python/graphscope/nx/tests/convert/test_convert_pandas.py, python/graphscope/nx/tests/convert/test_convert_scipy.py
- add copy method to `NeighborDict`
- Fix broken convert test of networkx
Fixes  #1488
=> Fix broken convert test of networkx

python/requirements.txt
+ Sync some improvements from graph learn upstream
+ Force pyarrow to version `<=6.0.0` as pyarrow starts to depends on protobuf (C++ library dependency) from 7.0.0, which makes `pywrap_graphlearn.so` un-importable on Mac for inplace built artifacts.
N/A
=> Upgrade graph learn version and force pyarrow<=6.0.0.

scripts/install_deps.sh
As titled, to accelerate the macos CI.
N/A
=> Disable brew update when installing dependencies as it is super slow.

.github/workflows/ci.yml, python/graphscope/framework/operation.py, python/graphscope/nx/algorithms/tests/builtin/test_eigenvector_centrality.py, python/graphscope/nx/algorithms/tests/builtin/test_katz_centrality.py
=> Mark operation evaluated after the op is run

coordinator/requirements.txt, python/requirements.txt
latest protobuf 3.20 not compatible with GraphScope:
```python
t = 'int64_t'
def _unify_str_type(t):
t = t.lower()
if t in ("b", "bool"):
return graph_def_pb2.DataTypePb.BOOL
elif t in ("c", "char"):
return graph_def_pb2.DataTypePb.CHAR
elif t in ("s", "short"):
return graph_def_pb2.DataTypePb.SHORT
elif t in ("i", "int", "int32", "int32_t"):
return graph_def_pb2.DataTypePb.INT
elif t in ("l", "long", "int64_t", "int64"):
>           return graph_def_pb2.DataTypePb.LONG
E           AttributeError: 'EnumTypeWrapper' object has no attribute 'LONG'
```
=> Restrict protobuf version

research/engine/pegasus/pegasus/src/operator/concise/keyed/join.rs, research/engine/pegasus/pegasus/tests/join_test.rs
The join operator in Pegasus sometimes misses some results. 
The reason is that applying session.give() to output the join results one by one will throw away the data that overflow the cache of the stream.
We replace it but session.give_iterator() and fix the bug.
Fixes #1613
=> fix the join bug

analytical_engine/core/object/fragment_wrapper.h, python/graphscope/tests/unittest/test_graph.py
Vertex maps `string` OID type doesn't have the `o2g_*` keys.
Add a test case to prevent it from being broken in the future as well.
Fixes #1626
=> Fixes the bug in AddColumn to graphs with `string` oid type.

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/ArgUtils.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/graph/RemoteTestGraph.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultParserFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransform.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/ValueMapTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/NegativeEvalTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
1. support valueMap() in gremlin grammar
2. translate valueMap() to expression '@.~all', and select('a').by(valueMap()) to '@a.~all'
Fixes #1622
=> support valueMap() to fetch all properties of vertices

coordinator/gscoordinator/coordinator.py, interactive_engine/executor/runtime/native/graph_builder_ffi.cc, interactive_engine/executor/runtime/native/graph_builder_ffi.h, interactive_engine/executor/runtime/native/property_graph_stream.cc, interactive_engine/executor/runtime/native/property_graph_stream.h, interactive_engine/executor/runtime/src/store/graph_builder_ffi.rs
Implemented the logic of `create_graph_builder` in the coordinator to reduce the complexity of the GIE ffi wrapper.
A `initialize_graph_builder` API has been added to initialize the builder using created schema.
Fixes #1604
=> Implement `createGraph` on coordinator, add API to initialize builder using schema

interactive_engine/executor/runtime/native/htap_ds_impl.cc
The support for string oid fragments for GIE was added in the https://github.com/alibaba/GraphScope/pull/1638. Unfornately, the string oid fragments hasn't been tested in CI thus the error is not captured in previous RP.
The root cause the we use `malloc` to allocate the struct thus the default initialization value is not respected.
N/A
=> Fixes the uninitialized pointer error for string fragment

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/InterOpCollection.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/SelectOp.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/strategy/ElementFusionStrategy.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/MatchStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/ldbc/LdbcQueryTest.java
fuse expand/getV with the following filters, i.e. out().has("name", "marko"), to support more nested patterns in match which are requirements from scope & insight
Fixes #1669
=> fuse expand/getV with the following filters to support more patterns in match

.github/workflows/release.yml, docs/frequently_asked_questions.rst, docs/zh/frequently_asked_questions.rst, python/graphscope/framework/graph_schema.py, python/graphscope/tests/unittest/test_graph.py
This is a requirement of `GraphInsight` for graph schema visualization.
This pr also:
Fixes #1646
=> Support return a dict for graph schema

analytical_engine/frame/app_frame.cc
=> Disable redefined warning of string_view

analytical_engine/apps/clustering/clustering.h, analytical_engine/apps/clustering/clustering_context.h, python/graphscope/nx/utils/compat.py
Since vertices which degree < 2 its clustering coefficient is 0 , we can optimize clustering by ignoring the computation of this kind of vertices.
Fixes #1586
=> Optimize clustering by ignoring computation of vertices that degree less than 2

.github/workflows/ci.yml, k8s/actions-runner-controller/manylinux-ci.yaml, k8s/actions-runner-controller/manylinux.yaml, k8s/actions-runner-controller/ubuntu.yaml
The `duration` is used to calculate if the replica number added via the trigger is expired or not.
Some jobs will require more than 1 hour to finish, so we increase the duration number so that we won't
scale down more than expected.
=> Increase the duration

coordinator/gscoordinator/launcher.py
The `addrs` argument still be useful in some cases, however in such cases vineyard need to be launched properly on multiple hosts as well, using MPI as the launch should be ok.
N/A
=> Supports launch vineyardd using on multiple hosts using MPI

scripts/install_deps.sh
add new vineyard version which can build on MacOS with LLVM<=14, find `homebrew_prefix` in `install_cppkafka()`, disable build tests and examples in `install_cppkafka()`, which can not compile on macOS.
Resolves #1734
=> Fixes bugs while building on macOS 12 wiht apple silicon

.github/workflows/gae.yml, .github/workflows/networkx-forward-algo-nightly.yml, analytical_engine/CMakeLists.txt, coordinator/gscoordinator/template/CMakeLists.template, coordinator/requirements.txt, interactive_engine/executor/runtime/native/CMakeLists.txt, k8s/Makefile, k8s/actions-runner-controller/manylinux/Dockerfile, k8s/graphscope-dev.Dockerfile, k8s/graphscope-store.Dockerfile, k8s/gsvineyard.Dockerfile, k8s/ubuntu/gsvineyard.Dockerfile, python/requirements.txt, scripts/install_deps.sh
Fixes the build failure on Mac and header not found issue after upgrading vineyard when compiling frames.
N/A
=> Upgrade vineyard version to fixes some build failures on Mac.

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/common/intermediate/operator/DedupOpTest.java
… to /tmp instead of current to have access to
1. write json file to /tmp instead of the current directory to solve the problem of file privilege
2. attach job id to each json file name to avoid conflicts in concurrent scenarios
Fixes #1729
=> [IR Compiler] fix error when creating json file

research/query_service/ir/graph_proxy/src/utils/expr/eval_pred.rs
fix bug, or_predicates is a collection of `AndPredicate` that forms a logical **OR** of all `AndPredicate`s
None
=> AndPredicate in IndexPredicate should be joined use or.

research/engine/pegasus/pegasus/src/communication/decorator/broadcast.rs
Fix broadcast error caused by DynPeers
https://github.com/alibaba/GraphScope/issues/1744
Fixes
=> fix communication caused by broadcast

Makefile, interactive_engine/executor/README.md, interactive_engine/executor/build.sh, interactive_engine/executor/cov.sh, interactive_engine/executor/update_proto.sh, scripts/install_deps.sh
Some improvements about dep installation and rust build
- the default version of `apache-arrow` on ubuntu20.04 is not 3 any more
- update deprecated `--all` to `--workspace` 
None
=> Some improvements about dep installation and rust builds

python/setup.py
PEP517 implemented recently in pip does not allow editable install in user site-packages.  Add a workaround to support install with editable mode with `--user`
See discussion here https://github.com/pypa/pip/issues/7953
=> Workaround for pip failure to perform editable install with `--user`

coordinator/gscoordinator/template/CMakeLists.template, research/query_service/ir/v6d_ffi/src/native/global_store_ffi.cc, research/query_service/ir/v6d_ffi/src/native/graph_builder_ffi.cc, research/query_service/ir/v6d_ffi/src/native/property_graph_stream.cc
- Fixes the issue about an empty property name in subgraph's schema.
- Addresses a bug about resolving primary key (OID) in subgraph builder as well.
- Tweak the `CMakeLists.template` to ensure graphscope can be run using the inplace build.
- Using `kDefaultBufferSize` as the default buffer size for subgraph.
Fixes #225
=> Fixes the long standing empty column name issue in subgraph

interactive_engine/groot-server/src/test/java/com/alibaba/maxgraph/tests/gremlin/MaxTestGraph.java, interactive_engine/groot-server/src/test/java/com/alibaba/maxgraph/tests/gremlin/MaxTestGraphProvider.java, interactive_engine/tests/src/main/java/com/alibaba/maxgraph/function/test/RemoteTestGraph.java, research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/graph/RemoteTestGraph.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/PredicateExprTransform.java
1. hasNot("age") -> !@.age
2. lower bound of the limit operator should start from 0, range(1, 2) with a lower bound greater than 0 is unsupported in ir runtime, currently remove `traversalMethod_range` from the grammar
#1802
=> [IR Compiler] support hasNot in ir compiler

research/engine/pegasus/server/examples/echo_service.rs, research/engine/pegasus/server/src/cluster/standalone.rs, research/engine/pegasus/server/src/job.rs, research/engine/pegasus/server/src/rpc.rs, research/query_service/ir/runtime/src/assembly.rs
Make input data as generic data types in `JobAssembly`, so that in `IRJobAssembly`, we do not need to serialize/deserialize records when input data for pegasus. This will accelerate the query.
Fixes #1860
=> [GAIA] Make input data as generic data types in `JobAssembly` interface

analytical_engine/apps/clustering/avg_clustering.h, analytical_engine/apps/clustering/clustering.h, analytical_engine/apps/clustering/transitivity.h
The `is_rec` is construct/destroy with every vertex, no need to use `vertex_array_t`.  Optimize the clustering algorithm by replacing the complex `vertex_array_t` with `unordered_map`
Fixes #1850
=> Optimize the clustering algorithm by replacing the complex `vertex_array_t` with `unordered_map`

Makefile, analytical_engine/apps/sssp/sssp_path.h
This is a temporary solution to make the CI pass.
Change this back when #1864 is merged.
=> Decrease the make job numbers when building gae.

interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/DataBuildMapper.java, interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/DataBuildMapperOdps.java, interactive_engine/data_load_tools/src/main/java/com/alibaba/maxgraph/dataload/databuild/OfflineBuildOdps.java
=> Data load tools supports partition

.gitignore, interactive_engine/executor/store/groot/Cargo.toml, interactive_engine/executor/store/groot/src/api/property.rs
impl partial_eq for Property and add deps for build tests and benches, then fix gitignore
None
=> impl partial_eq for Property and fix gitignore

interactive_engine/executor/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java
create FfiNameOrId from java side to avoid memory leak problems @siyuan0322 @sighingnow 
Fixes #1896
=> [IR Compiler] create FfiNameOrId from java side to fix k8s test error

python/graphscope/framework/graph_schema.py
Fixed graph schema drop, origin labels return string but expect get object 
Fixed init error when edge_kinds's src or dst gone, because can't get label from id_to_label by id
=> Fixed graph schema drop and init error when edge_kinds's src or dst gone

interactive_engine/executor/ir/graph_proxy/src/adapters/exp_store/read_graph.rs, interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/read_graph.rs, interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/edge.rs, interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/mod.rs, interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/property.rs, interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/vertex.rs, interactive_engine/executor/ir/graph_proxy/src/apis/mod.rs, interactive_engine/executor/ir/graph_proxy/src/utils/expr/eval.rs, interactive_engine/executor/ir/graph_proxy/src/utils/expr/eval_pred.rs, interactive_engine/executor/ir/integrated/tests/auxilia_test.rs, interactive_engine/executor/ir/integrated/tests/common/mod.rs, interactive_engine/executor/ir/integrated/tests/expand_test.rs, interactive_engine/executor/ir/runtime/src/process/operator/flatmap/edge_expand.rs, interactive_engine/executor/ir/runtime/src/process/operator/flatmap/get_v.rs, interactive_engine/executor/ir/runtime/src/process/operator/group/group.rs, interactive_engine/executor/ir/runtime/src/process/operator/join/join.rs, interactive_engine/executor/ir/runtime/src/process/operator/keyed/keyed.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/get_v.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/project.rs, interactive_engine/executor/ir/runtime/src/process/operator/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/sink/sink_vineyard.rs, interactive_engine/executor/ir/runtime/src/process/operator/sort/sort.rs
=> [GraphProxy] Optimize LazyDetails

interactive_engine/executor/engine/pegasus/pegasus/examples/page_rank.rs, interactive_engine/executor/engine/pegasus/pegasus/src/communication/decorator/exchange.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/other_tests.rs
=> [pegasus] fix bug in (#1954)

interactive_engine/executor/engine/pegasus/network/src/send/mod.rs
Fixes
https://github.com/alibaba/GraphScope/issues/1885
=> fix: add ipc sender after former one removed

interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/ingestor/BatchSender.java
Fixed ingestor high CPU usage when empty buffer, because no wait loop happened.
I don't know, maybe has a other better way.
=> Fixed ingestor high CPU usage when empty buffer

analytical_engine/CMakeLists.txt
=> Support for version suffixes like '0.15.0a1' in cmake

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java
=> [GAIA-IR] fix gaia-test ci caused by invalid group type used in compiler

analytical_engine/core/fragment/arrow_projected_fragment.h, analytical_engine/core/grape_instance.cc, analytical_engine/frame/project_frame.cc, coordinator/gscoordinator/coordinator.py
The `ArrowProjectedFragment` holds `ArrowFragment` as a member and should be drop from vineyard when been unloaded otherwise the `ArrowFragment` itself cannot be dropped and leading to memory leak.
Fixes #1737
=> Drop from vineyard when unloading a arrow projected fragment

.github/workflows/ci.yml, analytical_engine/core/grape_instance.cc, analytical_engine/core/server/dispatcher.cc
The analytical engine shouldn't be fault in any cases when dispatch requests from client.
Fixes N/A
=> No fatal even when meet unknown errors

coordinator/gscoordinator/launcher.py
As titled. On macOS the `socket.gethostname()` is not always resolvable by `getaddrinfo()`.
n/a, we received the bug report from our end users.
=> Use a `getaddrinfo` resolvable hostname as the local hostname (will be used as the etcd endpoint further).

python/graphscope/client/session.py
Signal is not working when the running program is not in python main thread. ensure session close can work in above case.
Fixes
=> Ensure session close work when triggered not in main thread

python/graphscope/client/session.py
GAE add connected() in session.py to indicate if the session is still valid and available for the graph computing work. In some case analytical engine cannot be connected, with this new function, client side can check the session status and process this special case(try to restart runtime or close session etc).
GAE add connected() in session.py to indicate if the session is still valid and available for the graph computing work.
In some case analytical engine cannot be connected, with this new function, client side can check the session status and process this special case(try to restart runtime or close session etc).
Fixes
=> Add connected() in session.py to figure out session status

interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/read_graph.rs
`Some(vec[])` means need all props,  so can't merge it with props needed in filter
#1530
=> fix bug in extract_needed_columns

interactive_engine/executor/engine/pegasus/pegasus/src/communication/decorator/exchange.rs, interactive_engine/executor/engine/pegasus/pegasus/src/progress.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/fold_test.rs
Update method `contains_source` in progress.rs to avoid bug in https://github.com/alibaba/GraphScope/issues/1999. The operators count, any, etc. in dataflow with aggregate will no longer output multi results.
Apply commit in https://github.com/bmmcq/fork-pegasus/commit/2ca02e401a09ba62aa9fa859e38a0700db781ac1#diff-0db0ad0daf508cf2b957808eefe7445c43d66a8621b538e5b15ac36866832a71 . 
Fixes https://github.com/alibaba/GraphScope/issues/1999
=> [pegasus] update contains_source in progress

.github/workflows/gae.yml, Makefile, analytical_engine/CMakeLists.txt, analytical_engine/java/giraph-on-grape/pom.xml, analytical_engine/java/grape-demo/pom.xml, analytical_engine/java/grape-jdk/pom.xml, analytical_engine/java/grape-runtime/CMakeLists.txt, analytical_engine/java/grape-runtime/pom.xml, analytical_engine/java/grape_jvm_opts, analytical_engine/java/pom.xml, coordinator/gscoordinator/utils.py, docs/analytics_engine.rst, docs/zh/analytics_engine.rst
- Refactor the building procedure of GAE Java SDK.
- Currently the Java SDK is built after GAE building, however, the building of Java SDK should be a part of GAE Building.
- GAE Java SDK version keep same with c++(currently 0.16)
- Format `pom.xml`
=> GAE java build refactor

.dockerignore, k8s/graphscope-dev.Dockerfile
The artfiact path for gaia executor was wrong in the graphscope-dev.Dockerfile.
N/A
=> Fixes the path of gaia executor, add a dockerignore file as well

analytical_engine/CMakeLists.txt
as titled.
Credit to @doudoubobo
=> Avoid install java related targets if java sdk is not enabled.

.github/workflows/build-graphscope-wheels-linux.yml, .github/workflows/build-graphscope-wheels-macos.yml, .github/workflows/ci.yml, Makefile, k8s/Makefile
pandas v1.5.0 releases last night and doesn't support lower version of numpy anymore.
N/A, see failure on CI: https://github.com/alibaba/GraphScope/actions/runs/3086602666/jobs/4991491718
=> Tensorflow requires lower version of pandas

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/script/AntlrToJavaScriptEngine.java
We receive the following error report from end user, from the documentation of apache common, we know that `t` might be null: https://commons.apache.org/proper/commons-lang/javadocs/api-3.4/org/apache/commons/lang3/exception/ExceptionUtils.html#getRootCause(java.lang.Throwable)
```java
[2022-09-20 11:55:37,018][INFO][gremlin-server-exec-2][com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor:131] query "g.V().limit(1)" total execution time is 669.3701 ms
[2022-09-20 11:55:37,019][INFO][gremlin-server-exec-2][MetricLog:136] 1 | g.V().limit(1) | true | 669.3701 | 1663646136347
[2022-09-20 11:55:37,158][INFO][gremlin-server-exec-3][com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor:131] query "g.V().has('year', inside(2014, …
```
=> The `ExceptionUtils.getRootCause()` may returns null, record the error and backtrace in such cases

interactive_engine/executor/store/global_query/src/store_impl/v6d/native/htap_ds_impl.cc
as titled. The struct may be allocated using `malloc()` or allocated from rust side then those fields would be leave as uninitialized.
N/A
=> Fixes an uninitialized field bug in FFI reader

.pre-commit-config.yaml, pre-commit/README.md
=> [GIE] introduce a pre-commit hook to prevent committing sensitive information

coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/template/CMakeLists.template
=> Fix GAE-Bug: Cannot compile GAE app if java not installed

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/strategy/ExpandFusionStepStrategy.java
fuse bothE() with otherV instead of bothV()
Fixes
=> [GIE-IR] fix expand fusion strategy

.github/workflows/gae.yml, analytical_engine/java/giraph-on-grape/pom.xml, analytical_engine/java/grape-demo/pom.xml, analytical_engine/java/grape-jdk/pom.xml, analytical_engine/java/grape-runtime/pom.xml, analytical_engine/java/grape_jvm_opts, analytical_engine/java/graphx-on-graphscope/pom.xml, analytical_engine/java/pom.xml, coordinator/gscoordinator/utils.py
Make GAE Java SDK version not fixed in code/configuration. BUT we still need to change `analytical_engine/java/pom.xml` for GraphScope version change.
=> [GAE-Java] Make GAE Java SDK version align with GraphScope

python/graphscope/dataset/io_utils.py
as titled, fixes the typo.
Fixes #2091
=> Fixes the typo in error message template when encounter dataset download failure

coordinator/gscoordinator/coordinator.py, python/graphscope/client/rpc.py, python/graphscope/client/utils.py
- Don't reuse the "generator" during retry
- Some operation shouldn't be retried
Fixes #2093
=> Ensure the correctness of retry (in the RunStep request) to avoid the strange "has no attribute" error

analytical_engine/frame/cython_pie_app_frame.cc
The error was introduced in https://github.com/alibaba/GraphScope/pull/2089
N/A, see failure on CI: https://github.com/alibaba/GraphScope/actions/runs/3142674404/jobs/5108718098
=> Fixes the missing return statement in frames

analytical_engine/core/error.h, k8s/precompile.py
Fixes the CI failure on MacOS in: https://github.com/alibaba/GraphScope/actions/runs/3142684408/jobs/5109428900
=> Get the exception type in correct way, both on Linux and on MacOS.

.github/workflows/gae.yml
It is necessary to run GAE CI when `CMakeLists.template` is changed in pull request. As file will not be changed frequently, most pull requests' CI time will not be increased.
Fixes #2070
=> [GAE-Java] Invoking GAE CI when CMakeLists.template changes

interactive_engine/executor/engine/pegasus/pegasus/src/communication/output/output.rs
=> [Pegasus] Avoid get iter.next() when it is None already in sending batches

.dockerignore
as some dockerfile, e.g., `graphscope-dev-image` still requires the `.git` directory.
N/A
=> Fixes configuration in dockerignore

interactive_engine/executor/ir/graph_proxy/src/adapters/exp_store/read_graph.rs, interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/partitioner.rs, interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/read_graph.rs, interactive_engine/executor/ir/runtime/src/error.rs, interactive_engine/executor/ir/runtime/src/process/operator/accum/accum.rs, interactive_engine/executor/ir/runtime/src/process/operator/accum/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/filter/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/flatmap/fused.rs, interactive_engine/executor/ir/runtime/src/process/operator/flatmap/get_v.rs, interactive_engine/executor/ir/runtime/src/process/operator/flatmap/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/group/fold.rs, interactive_engine/executor/ir/runtime/src/process/operator/group/group.rs, interactive_engine/executor/ir/runtime/src/process/operator/group/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/join/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/keyed/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/auxilia.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/get_v.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/path_end.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/path_start.rs, interactive_engine/executor/ir/runtime/src/process/operator/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/sink/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/sink/sink_vineyard.rs, interactive_engine/executor/ir/runtime/src/process/operator/sort/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/source.rs, interactive_engine/executor/ir/runtime/src/process/operator/subtask/apply.rs, interactive_engine/executor/ir/runtime/src/process/operator/subtask/mod.rs
=> [GIE/Runtime] Refine some error infos in Runtime

coordinator/setup.cfg, docs/analytics_engine.rst, docs/developer_guide.rst, docs/interactive_engine.rst, docs/reference/app.rst, docs/reference/gnn_engine/data_loader_en.rst, docs/reference/gnn_engine/gsl_en.rst, docs/reference/networkx/transformation.rst, docs/reference/operation.rst, docs/zh/analytics_engine.rst, docs/zh/deployment.rst, python/graphscope/analytical/app/__init__.py, python/graphscope/framework/app.py, python/graphscope/framework/context.py, python/graphscope/framework/graph.py, python/graphscope/learning/graph.py, python/graphscope/nx/classes/graph.py, python/pyproject.toml
=> Fixes the docstring rendering for GAE apps

interactive_engine/pom.xml
There are 1 security vulnerabilities found in org.apache.kafka:kafka-clients 2.5.0
- [CVE-2021-38153](https://www.oscs1024.com/hd/CVE-2021-38153)
Upgrade org.apache.kafka:kafka-clients from 2.5.0 to 2.7.2 for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` failed locally, couldn't complete the build process.
Run `mvn clean test` failed locally, unit-test couldn't pass.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.apache.kafka:kafka-clients to 2.7.2

interactive_engine/pom.xml
There are 1 security vulnerabilities found in commons-codec:commons-codec 1.11
- [MPS-2022-11853](https://www.oscs1024.com/hd/MPS-2022-11853)
Upgrade commons-codec:commons-codec from 1.11 to 1.13 for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` failed locally, couldn't complete the build process.
Run `mvn clean test` failed locally, unit-test couldn't pass.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade commons-codec:commons-codec to 1.13

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrGremlinServer.java
=> [BUG FIX] Make gremlin server listen to 0.0.0.0 instead of localhost

python/graphscope/nx/utils/compat.py, python/requirements-dev.txt
- add pytest-timeout to the dependency list
- filter out the deprecated warning when importing imp.
n/a
=> Add pytest-timeout to requirements-dev.txt and fixes a deprecated warnings when running tests

interactive_engine/assembly/src/bin/graphscope/giectl, interactive_engine/assembly/src/conf/graphscope/executor.vineyard.properties, interactive_engine/executor/assembly/v6d/src/bin/gaia_executor.rs
Rename the ambiguous `pegasus.hosts` to `network.servers` for executor.
=> Rename pegasus.hosts to network.servers for executor

.github/workflows/gae-dummy.yml, .github/workflows/gae.yml, python/graphscope/tests/unittest/test_java_app.py
- Make the CI conditions consistent in pull request and on main
- Extend the timeout limits for java app tests.
N/A
=> Fixes the conditions for GAE CI in PR and on main, add timeout for test_java_app.py

analytical_engine/CMakeLists.txt, analytical_engine/java/giraph-on-grape/pom.xml, analytical_engine/java/grape-annotation/pom.xml, analytical_engine/java/grape-demo/pom.xml, analytical_engine/java/grape-jdk/pom.xml, analytical_engine/java/grape-runtime/pom.xml, analytical_engine/java/graphx-on-graphscope/pom.xml, analytical_engine/java/pom.xml
Fixes
Fix the problem that user can not compile only the submodule of GAE Java SDK
=> [GAE-Java] Fix : can not compile the submodule of GAE Java SDK

interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/SnapshotCache.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/ClientDdlService.java
The graph def is read from rust side after restarting.
And the edge kinds proto in rust only has label ID.
Fixes #2154
=> fix src label and dst label of edge kinds may be empty

.github/workflows/build-graphscope-wheels-linux.yml, .github/workflows/build-graphscope-wheels-macos.yml, .github/workflows/ci-dummy.yml, .github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/gae.yml, .github/workflows/gaia.yml, .github/workflows/gss.yml, .github/workflows/networkx-forward-algo-nightly.yml, .github/workflows/nightly.yml, .github/workflows/pegasus.yml, .github/workflows/release.yml
As github have deprecated the use of node 12 and will gives warning in every CI.
=> upgrade actions version to use node 16

charts/graphscope/README.md, charts/graphscope/templates/NOTES.txt, charts/graphscope/templates/_helpers.tpl, charts/graphscope/templates/coordinator.yaml, charts/graphscope/templates/service.yaml, charts/graphscope/templates/test/test-rpc.yaml
In helm installed cluster the names of coordinator and coordinator service are prefixed by instance id, whereas in python launched cluster the names are suffixed by instance id.
Reported by #2161
=> fix create interactive engine failure on helm installed graphscope

analytical_engine/java/grape-annotation/pom.xml, analytical_engine/java/grape-demo/pom.xml, analytical_engine/java/grape-giraph/pom.xml, analytical_engine/java/grape-graphx/pom.xml, analytical_engine/java/grape-jdk/pom.xml, analytical_engine/java/grape-runtime/pom.xml, analytical_engine/java/pom.xml, docs/Makefile
Add some configuration and plugins in `pom.xml`, so we can publish to maven central repo.
https://issues.sonatype.org/browse/OSSRH-85660
Fixes #2165
=> [GAE-Java] Add necessary configurations in `pom.xml` to publish GRAPE jdk to maven central repo

coordinator/gscoordinator/kubernetes_launcher.py, interactive_engine/executor/engine/pegasus/pegasus/src/operator/primitives/sink.rs, interactive_engine/executor/engine/pegasus/pegasus/src/result.rs, interactive_engine/executor/engine/pegasus/pegasus/src/worker.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/fold_test.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/timeout_test.rs, interactive_engine/executor/engine/pegasus/server/config/tests/standalone2/server_config.toml
1. Query will be cancelled when timeout
2. User can cancel running job by set cancel hook in ResultSink
3. ResultSink will call method `on_error` when query is cancelled
Resolves https://github.com/alibaba/GraphScope/issues/1867
=> [GIE pegasus] Support cancelling query. 

.github/workflows/networkx-forward-algo-nightly.yml
See https://github.com/alibaba/GraphScope/actions/runs/3388531965/jobs/5630625900
=> Fix failure in networkx forward CI

.github/workflows/docs.yml, analytical_engine/java/README.md, analytical_engine/java/grape-rdd-reader/pom.xml, analytical_engine/java/pom.xml, docs/Makefile, docs/analytics_engine.rst
Update GAE-Java docs.
Should be merged after https://github.com/alibaba/GraphScope/pull/2195
Rename `Vertex.GetValue()` to `Vertex.getValue()`.
=> [GAE-Java] Update doc

coordinator/gscoordinator/op_executor.py, k8s/graphscope.Dockerfile, python/graphscope/framework/loader.py
Vineyard supports ORC and Parquet files in its IO adaptors, see also: https://github.com/v6d-io/v6d/pull/1052
Fixes #1041
=> Delegate parquet/orc files to vineyard io adaptors

charts/graphscope-store/templates/_helpers.tpl
Thanks for @siyuan0322 , https://github.com/alibaba/GraphScope/pull/2205 doesn't use the `.Chart.AppVersion`.
I have tested it with the pr and works as expected.
```shell
$ kubectl create ns graphscope-store
namespace/graphscope-store created
$ helm install graphscope-store "./graphscope-store" -n graphscope-store
NAME: graphscope-store
LAST DEPLOYED: Tue Nov  8 12:29:11 2022
NAMESPACE: graphscope-store
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
export NODE_IP=$(kubectl -n graphscope-store get pod graphscope-store-frontend-0  -o jsonpath="{.status.hostIP}")
export GRPC_PORT=$(kubectl -n graphscope-store get services graphscope-store-frontend -o jsonpath="{.spec.ports[0].nodePort}")
export GREMLIN_PORT=$(kubectl -n graphscope-store get …
```
=> [Bug Fix]Update the DefaultTag to .Chart.AppVersion

analytical_engine/java/pom.xml, docs/Makefile
The GAE Java doc not generated due to `javadoc` path error.
=> [BugFix] GAE JavaDoc not generated

analytical_engine/java/grape-graphx/src/main/scala/org/apache/spark/scheduler/cluster/ExecutorInfoHelper.scala
Support user running grape-graphx in local mode, where driver and executor resides in one process.
=> [GAE-Java] GRAPE JDK support Spark local mode for graphx

analytical_engine/core/java/graphx_runner.h
Fix an include error under gcc 10.2.1
```
[ 94%] Building CXX object CMakeFiles/graphx_runner.dir/core/java/javasdk.cc.o
In file included from /home/graphscope/graphscope/analytical_engine/core/java/graphx_runner.cc:15:
/home/graphscope/graphscope/analytical_engine/core/java/graphx_runner.h:46:15: error: expected constructor, destructor, or type co
nversion before ‘(’ token
46 | DECLARE_string(task);
|               ^
/home/graphscope/graphscope/analytical_engine/core/java/graphx_runner.h:47:15: error: expected constructor, destructor, or type co
nversion before ‘(’ token
47 | DECLARE_string(ipc_socket);
```
=> fix compilation error of graphx runner

interactive_engine/executor/engine/pegasus/executor/src/reactor.rs
=> [GIE/Engine]: add direct executor implementation;

interactive_engine/executor/store/exp_store/src/graph_db/csr_topo.rs, interactive_engine/executor/store/exp_store/src/graph_db/graph_db_impl.rs, interactive_engine/executor/store/exp_store/src/graph_db/labeled_topo.rs, interactive_engine/executor/store/exp_store/src/lib.rs, interactive_engine/executor/store/exp_store/src/sorted_map.rs, interactive_engine/executor/store/exp_store/src/table.rs
As titled, reducing the memory footprint of `exp_store` by nearly half the original size.
=> [GIE/Store] Reduce memory footprint in `exp_store`

.github/workflows/ci.yml, interactive_engine/assembly/pom.xml, interactive_engine/common/pom.xml, interactive_engine/compiler/Makefile, interactive_engine/compiler/pom.xml, interactive_engine/data_load_tools/pom.xml, interactive_engine/executor/engine/pegasus/clients/java/client/pom.xml, interactive_engine/executor/pom.xml, interactive_engine/frontend/pom.xml, interactive_engine/groot-module/pom.xml, interactive_engine/groot-server/pom.xml, interactive_engine/lgraph/pom.xml, interactive_engine/pom.xml, interactive_engine/sdk-common/pom.xml, interactive_engine/sdk/pom.xml, interactive_engine/tests/pom.xml
Build a GIE target with a unified version by running `mvn clean package -Drevision=<XXX>`, default  is https://github.com/shirly121/GraphScope/blob/ir_unify_version/interactive_engine/pom.xml#L71
Fixes #2164
=> [GIE POM] Unify GIE version by the global flag 'revision'

.github/workflows/ci.yml, charts/ir-standalone/templates/frontend/statefulset.yaml, interactive_engine/compiler/Makefile
set the version of compiler as 0.0.1-SNAPSHOT (default value in pom of interactive_engine) to fix the ci issue reported by @siyuan0322 
Fixes
=> [GIE POM] Make the version of GIE compiler consistent with the default value in interactive_engine pom

interactive_engine/executor/engine/pegasus/pegasus/src/lib.rs, interactive_engine/executor/ir/graph_proxy/src/adapters/exp_store/partitioner.rs, interactive_engine/executor/ir/graph_proxy/src/adapters/exp_store/read_graph.rs, interactive_engine/executor/ir/integrated/tests/scan_test.rs
As titled. 
Have tested `g.V().count()` on LDBC.30, in which parallel scan brings about 50% acceleration in time cost.
Fixes #2252
=> [GIE] Support parallel scan on ExpStore

.github/workflows/build-graphscope-wheels-linux.yml, .github/workflows/build-graphscope-wheels-macos.yml, Makefile, k8s/build_scripts/build_vineyard.sh, k8s/build_scripts/build_vineyard_dependencies.sh, k8s/dockerfiles/graphscope-dev-base.Dockerfile, k8s/internal/Makefile, scripts/install_deps.sh
=> Fixes CI failure both on Linux and MacOS

.github/workflows/build-graphscope-wheels-linux.yml, k8s/internal/Makefile
=> Push jupyter image nightly with the latest client

interactive_engine/compiler/src/test/java/com/alibaba/graphscope/integration/pattern/PatternQueryTest.java, interactive_engine/executor/ir/core/src/plan/physical.rs
=> [BUG] Fix bug in Pattern Match when project properties

coordinator/gscoordinator/coordinator.py, python/graphscope/client/rpc.py, python/graphscope/client/session.py, python/graphscope/proto/message.proto
=> Make sure reconnect behaves as expected

charts/graphscope-store/templates/test/test-rpc.yaml
as titled.
See also: https://github.com/alibaba/GraphScope/actions/runs/3627042971/jobs/6117279514
=> Use a self-hosted public image to avoid reaching the download limits

analytical_engine/core/app/pregel/pregel_context.h, coordinator/gscoordinator/utils.py, python/graphscope/framework/app.py
Have a demo case in graphscope/cpp-template#1
Fixes #2299
=> Enable plug udf cpp pregel algorithm to graphscope.

.github/workflows/ci.yml, charts/graphscope/templates/NOTES.txt, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/kubernetes_launcher.py, coordinator/gscoordinator/launcher.py, coordinator/gscoordinator/op_executor.py, python/graphscope/tests/kubernetes/test_demo_script.py
- Wait for analytical engine ready instead of sleep
- Fix the logic of reconnecting
- Improved the helper template to reduce complexity
- Add tests for helm installed graphscope
=> fix connect session logic and wait for gae ready

coordinator/gscoordinator/op_executor.py, coordinator/gscoordinator/utils.py, python/graphscope/framework/loader.py
See changes in `loader.py`.
Fixes #2328
Requires https://github.com/v6d-io/v6d/pull/1104
=> Accept a filetype arguments in loader for reading orc/parquet using prefix

.github/workflows/gae.yml, .github/workflows/networkx-forward-algo-nightly.yml, analytical_engine/CMakeLists.txt, analytical_engine/core/java/graphx_loader.h, analytical_engine/core/loader/arrow_fragment_loader.h, analytical_engine/core/loader/dynamic_to_arrow_converter.h, analytical_engine/frame/property_graph_frame.cc, analytical_engine/test/run_vy_app_local_vm.cc, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/template/CMakeLists.template, coordinator/gscoordinator/utils.py, k8s/Makefile, k8s/actions-runner-controller/manylinux/Makefile, k8s/internal/Makefile, k8s/utils/precompile.py, python/graphscope/client/rpc.py, python/graphscope/framework/utils.py, python/graphscope/nx/tests/convert/test_convert_numpy.py, scripts/install_deps.sh
Let the `BasicFragmentLoader` inherits from the vineyard ones.
- fixes #2127 
- fixes #2269
=> Upgrade the fragment loader to reuse vineyard components

charts/graphscope-store/Chart.yaml
Fix `Error: can't get a valid version for repositories kafka. Try changing the version constraint in Chart.yaml`
See https://github.com/alibaba/GraphScope/actions/runs/3736733548/jobs/6341482973
=> Fix kafka version

charts/graphscope/templates/coordinator.yaml, charts/graphscope/templates/role_and_binding.yaml
In a real k8s cluster, we find the finalizers can't work as expected, and using ownerReferences to perform cascade deletion of role and rolebinding works fine.
Related https://github.com/alibaba/GraphScope/pull/2208
Related https://github.com/alibaba/GraphScope/pull/2324
=> Use ownerReferences to replace finalizers during helm uninstall

docs/java_tutorial_0_pie.md, docs/java_tutorial_1_giraph.md, docs/java_tutorial_2_graphx.md, docs/java_tutorials.md
Add java tutorials for GRAPE-jdk.
Fix #2292
=> Add Java tutorial

analytical_engine/core/server/analytical_server.h, analytical_engine/core/server/graphscope_service.cc, analytical_engine/core/server/graphscope_service.h, interactive_engine/executor/store/global_query/build.rs, interactive_engine/executor/store/global_query/src/store_impl/v6d/native/CMakeLists.txt
Fix several build failures
- Fix build gae with grpc 1.30 (which is the default version of ubuntu:latest)
- Fix build gie and gle with arrow10 and gcc11
=> Fix compile error under newer toolchain and arrow 10

coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/utils.py, python/graphscope/client/rpc.py, python/graphscope/client/session.py
=> Fixes the hangs up issue in Python test

analytical_engine/core/app/app_base.h, analytical_engine/core/app/parallel_property_app_base.h, analytical_engine/core/app/property_app_base.h, analytical_engine/core/app/property_auto_app_base.h, analytical_engine/core/worker/parallel_property_worker.h
When building my test, I encounter some compile errors as some header files are missed, besides, namespace is not assigned in some macro definitions.
Fixes
=> Fix missing header files

analytical_engine/core/context/i_context.h, analytical_engine/core/context/tensor_context.h
These changes add implementation of ToArrowArrays method for TensorContext to enable convert tensor context to arrow::Table.
Fixes
=> Implement ToArrowArrays method for TensorContext

coordinator/gscoordinator/utils.py, coordinator/setup.cfg
=> OpenMPI: bind to none to leverage all cores for when there are 2 processes

charts/graphscope-store/README.md, charts/graphscope-store/templates/configmap.yaml, charts/graphscope-store/templates/coordinator/statefulset.yaml, charts/graphscope-store/templates/frontend/statefulset.yaml, charts/graphscope-store/templates/ingestor/statefulset.yaml, charts/graphscope-store/templates/store/statefulset.yaml, charts/graphscope-store/values.yaml, charts/ir-standalone/values.yaml, interactive_engine/assembly/src/bin/groot/store_ctl.sh, interactive_engine/assembly/src/conf/groot/log4rs.yml, interactive_engine/assembly/src/conf/groot/logback.xml, interactive_engine/executor/assembly/groot/Cargo.toml, interactive_engine/executor/assembly/v6d/Cargo.toml, interactive_engine/executor/engine/pegasus/common/Cargo.toml, interactive_engine/executor/store/groot/Cargo.toml, interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/GrootGraph.java, interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/NodeBase.java
1. Rename groot config file from `my.cnf` to `groot.config` for better readability
2. Fix a bug that rust log are not redirect to console
3. Enable reload of logback for java servers
4. Bump up version of rust log crate
5. Fix the log output location.
Fixes
=> Some minor improvement in logs and configurations of groot.

.github/workflows/gae.yml, .github/workflows/networkx-forward-algo-nightly.yml, analytical_engine/CMakeLists.txt, analytical_engine/core/fragment/arrow_projected_fragment.h, analytical_engine/test/app_tests.sh, analytical_engine/test/run_vy_app.cc, interactive_engine/executor/store/global_query/src/store_impl/v6d/native/CMakeLists.txt, k8s/Makefile, k8s/actions-runner-controller/manylinux/Makefile, k8s/build_scripts/build_vineyard.sh, k8s/internal/Makefile, python/graphscope/config.py, python/graphscope/learning/__init__.py, python/graphscope/tests/unittest/test_context.py, scripts/install_deps.sh
`ProjectToSimple()` requires scan all edges to establish the new offset ranges. The previous implements runs slow (slower than scan edges for many times in pagerank) because
- It use a scan implementation to find the start and end point for a given label. As the CSR is internally sorted, a bisect could be enough, the complexity is `O(E)`.
- It use a single-thread implementation for vertices
- The method `getRangeOfLabel` takes `std::shared_ptr` as argument, the shared ptr would be constructed and destructed for `O(V)` times. 
This PR optimize the implementation. Benchmark shows that it improve the `Project()` operation from `2~3 seconds` to `0.02~0.1 seconds` (consider the overhead of creating threads for parallelism) on an internal datasets. (PageRank requires about `0.02~0.03 seconds` …
=> Fixes the performance issue in `Project()`

.github/workflows/build-graphscope-wheels-linux.yml, .github/workflows/build-graphscope-wheels-macos.yml, coordinator/requirements.txt, coordinator/setup.py, k8s/internal/Makefile, k8s/utils/precompile.py, python/graphscope/tests/minitest/test_min.py, python/requirements.txt, python/setup.py, scripts/install_deps.sh
=> Build wheel package on python3.10 and python3.11

interactive_engine/compiler/src/test/java/com/alibaba/graphscope/integration/IrGremlinQueryTest.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/integration/pattern/PatternQueryTest.java, interactive_engine/executor/ir/core/src/glogue/pattern.rs, interactive_engine/executor/ir/core/src/plan/logical.rs, interactive_engine/executor/store/global_query/src/store_impl/v6d/read_ffi.rs
1. Fix the bug when we want to fetch properties of tags that generated by `Project` opr,
e.g., `g.V().out().as("a").in().select("a").as("b").select("b").by("name")`
2. Further replace `Auxilia` (to remove unnecessary system-given tags) by `Project` (to project necessary user-given tags) in `Pattern`
Fixes #2401
=> [BUG Fix] fix bug when fetch properties of tags generated by a `Project`

.github/workflows/k8s-ci.yml, charts/graphscope/values.yaml, python/graphscope/tests/kubernetes/test_demo_script.py
=> test demo on helm

.github/workflows/build-graphscope-wheels-linux.yml, .github/workflows/build-graphscope-wheels-macos.yml, README.md, k8s/internal/Makefile, scripts/install_deps.sh
It have been failed for quite a while... Removing unsupported Python 3.7 from CI (and install_deps.sh) as well.
=> Fixes building wheel process on local CI.

analytical_engine/apps/pregel/louvain/louvain.h, python/graphscope/tests/conftest.py, python/graphscope/tests/unittest/test_app.py
With projected fragment, `0` may not be in the range of `Vertices()/InnerVertices` thus cannot be used as the index of vertex arrays.
Fixes #2446
=> Fixes louvain on projected fragment when v label is not 0

coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/local_launcher.py, coordinator/gscoordinator/op_executor.py, interactive_engine/assembly/src/bin/graphscope/giectl, interactive_engine/executor/assembly/v6d/src/bin/gaia_executor.rs, interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/partitioner.rs, interactive_engine/executor/ir/integrated/src/assemble/vineyard.rs, interactive_engine/executor/store/global_query/src/store_impl/v6d/native/global_store_ffi.h, python/graphscope/tests/minitest/test_min.py
We will decouple the deploy of vineyard and graphscope (see also #2458) where vineyard and graphscope workers may not aligned. After that, on one kubernetes node, there might be only 1 vineyardd instance and more than one graphscope workers (specially GIE executors) on it.
Before this pull request, that workable, but yields wrong (duplication) query results. This pull fixed that by first sync process partition list and splitted the partitions to "local" work processes.
To avoid disturbe existing users, the new feature is only availbel when the environment variable `PARALLEL_INTERACTIVE_EXECUTOR_ON_VINEYARD ` is set to `OFF` (both `ON` and `OFF` are covered by CI). 
N/A
=> Enable running multiple GIE instances on a same vineyardd server

charts/graphscope/templates/coordinator.yaml, charts/graphscope/values.yaml, coordinator/gscoordinator/cluster_builder.py, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/kubernetes_launcher.py
This PR adds an option of configuring the proxy service address for the dataset container should be added to the configuration file of helm
The dataset container of graphscope provides the function of obtaining sample dataset online, but there are many inconveniences in accessing the external network to obtain data in many Intranet environments. 
Fixes #2512
=> Add proxy support to the dataset container #2512

docs/development/dev_guide.md, docs/index.rst, docs/overview/intro.md, docs/overview/positioning.md
as titled, partial commit to #2522
=> add intro.md

interactive_engine/assembly/src/bin/graphscope/giectl
When starting the gremlin instance, you need to get the instance_id. If the release name of the current application contains' - ', for example, 'b-c', the coordinator_name is' coordinator-b-c ', and every char after the last '-' is captured in the case of existing code, and the instance_id is' c '. In fact, every char after the first '-' should be captured. instance_id is' b-c '.
#2524 
Fixes
=> Fix: Gremlin startup error when k8s release name contains' - '. #2524

.github/workflows/gaia.yml, .github/workflows/gss.yml, .github/workflows/k8s-ci.yml, .github/workflows/local-ci.yml, .github/workflows/pegasus.yml
As titled.
Fix https://github.com/alibaba/GraphScope/issues/2528.
=> Add a CI step to avoid running the tmate session on the self-hosted machine

.github/workflows/k8s-ci.yml, README-zh.md, charts/graphscope/templates/coordinator.yaml, charts/graphscope/values.yaml, coordinator/gscoordinator/cluster_builder.py, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/kubernetes_launcher.py, coordinator/gscoordinator/op_executor.py, python/graphscope/client/session.py, python/graphscope/config.py, python/graphscope/deploy/kubernetes/cluster.py, python/graphscope/tests/kubernetes/test_demo_script.py
The pr uses Deployment to replace the original Daemonset as the vineyard operator uses `Deployment` to install the vineyard cluster. Also, after specifying the vineyard deployment, we need to use the vineyard operator python API to deploy the engines to vineyard nodes.
BTW, the pr needs to wait for the https://github.com/v6d-io/v6d/pull/1183 ready.
=> Integrate vineyard operator python API with Graphscope

.github/workflows/release.yml
Previously `cd $GITHUB_WORKSPACE/charts && cp -r oss://graphscope/charts ./` will output all contents to `$GITHUB_WORKSPACE/charts/charts/xxx`.
Change to `cd $GITHUB_WORKSPACE && cp -r oss://graphscope/charts ./charts` will output all contents to `$GITHUB_WORKSPACE/charts/xxx`.
The latter case would make older .tgz files in the same level of the newest tgz file that `helm package` generated.
=> fix chart download path

Makefile, k8s/dockerfiles/analytical.Dockerfile, k8s/dockerfiles/coordinator.Dockerfile, k8s/dockerfiles/graphscope-dev.Dockerfile, k8s/dockerfiles/interactive-experimental.Dockerfile, k8s/dockerfiles/interactive.Dockerfile, k8s/dockerfiles/learning.Dockerfile, k8s/dockerfiles/manylinux2014-ext.Dockerfile, k8s/internal/graphscope.Dockerfile
- Move `pip install` to previous section, so that `make coordinator` will use local installed client, instead of download client wheel from remote.
- `sh` doesn't have `source` command, and docker use `sh` as default shell in dockerfiles.
- `sh` doesn't supports `==` operator
- Install ipython to `dev` docker
- Remove unnecessary hadoop contents to save space.
=> `sh` doesn't have `source`

docs/analytical_engine/tutorial_dev_algo_cpp_pie.md
=> Add document tutorial_dev_algo_cpp_pie.md

coordinator/requirements.txt
The error is
```
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' 
module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: 
https://github.com/urllib3/urllib3/issues/2168
```
urllib3 release 2.0.0 today and dropped support for openssl < 1.1.1, whereas out centos7 bundled openssl library is 1.0.2k.
This restraints could be dropped when our image base has been switch to ubuntu #2607
=> temporarily fix the urllib3 2.0.0 incompatible with openssl

analytical_engine/core/parallel/thread_local_property_message_buffer.h
Fix #2664
Call flushLocalBuffer() to avoid send big msg between workers
=> [GAE] Fix overflow of MPI_Isend()'s data size

python/graphscope/framework/graph.py
Fixes https://github.com/alibaba/GraphScope/discussions/2619#discussioncomment-5698332
Fixes https://github.com/alibaba/GraphScope/discussions/2626#discussioncomment-5698356
After this pull request, the error message looks like
```python
In [4]: g = g.project(vertices={"paper"}, edges={"cites"})
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /usr/local/lib/python3.11/site-packages/graphscope/framework/graph.py:1136 in project            │
│ …
```
=> Improve the error message when passing unexpected arguments to `g.project()`

interactive_engine/compiler/Makefile, interactive_engine/executor/assembly/groot/Cargo.toml, interactive_engine/executor/assembly/v6d/Cargo.toml, interactive_engine/executor/ir/core/src/plan/physical.rs, interactive_engine/executor/ir/graph_proxy/Cargo.toml, interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/read_graph.rs, interactive_engine/executor/ir/graph_proxy/src/adapters/mod.rs, interactive_engine/executor/ir/graph_proxy/src/lib.rs, interactive_engine/executor/ir/integrated/Cargo.toml, interactive_engine/executor/ir/integrated/src/assemble/mod.rs, interactive_engine/executor/ir/integrated/src/lib.rs
As titled.
Notice that by default compiling (`cargo build` in ir-core), it won't depend on `GlobalQuery` anymore. If you want to compile GIE based on `GlobalQuery` (including Groot and V6d), do `cargo build --features with_global_query`.
Fixes #2679
=> [GIE/Runtime] Remove the dependency of GIE Runtime on GlobalQueryStore to accelerate the compilation

.github/workflows/gss.yml, .github/workflows/k8s-ci.yml
=> Export the k8s logs of graphscope helm test and upload to artifact when the helm test failed

k8s/dockerfiles/graphscope-store.Dockerfile
See failure in nightly CI: https://github.com/alibaba/GraphScope/actions/runs/4984139366/jobs/8922080662
=> Fixes the 'sudo' in dockerfile for gss image

python/graphscope/client/session.py
=> Ensure use string as log-level, even for logging.XXX

python/graphscope/deploy/kubernetes/cluster.py, python/graphscope/deploy/kubernetes/utils.py, python/graphscope/framework/utils.py, python/jupyter/graphscope/setupbase.py
Fixes #2746
After this pull request, the error in issue #2746 becomes more readable and accurate:
```python
In [1]: import logging
...: import graphscope
...: graphscope.set_option(show_log=True)
...: graphscope.set_option(log_level=logging.DEBUG)
...: sess = graphscope.session()
2023-05-25 19:28:48,699 [INFO][session:650]: Initializing graphscope session with parameters: {'addr': None, 'mode': 'eager', 'cluster_type': 'k8s', 'num_workers': 2, 'preemptive': True, 'k8s_namespace': None, 'k8s_service_type': 'NodePort', 'k8s_image_registry': 'registry.cn-hongkong.aliyuncs.com', 'k8s_image_repository': 'graphscope', 'k8s_image_tag': '0.22.0', 'k8s_image_pull_policy': 'IfNotPresent', 'k8s_image_pull_secrets': [], 'k8s_coordinator_cpu': 0.5, 'k8s_coordinator_mem': '512Mi', 'etcd_addrs': None, …
```
=> Propogate the k8s exception to avoid waiting forever

analytical_engine/core/grape_engine.cc, analytical_engine/core/launcher.cc, analytical_engine/core/server/dispatcher.cc, analytical_engine/core/server/dispatcher.h
- Reset the pointer to prevent double-shutdown which causes crash inside grpc
- Terminate dispatcher (and its queues) correctly when closing
Fixes #2749
=> Make sure grape-engine exit when CTRL-C without crash

docs/learning_engine/dev_and_test.md, docs/learning_engine/tutorial_node_classification_local.md
=> [GLE docs] minor fixes

analytical_engine/frame/property_graph_frame.cc
=> Fixes the graphdef value when constructing graphs from vineyard_id.

coordinator/gscoordinator/kubernetes_launcher.py, python/graphscope/client/session.py
- Support users to only input the kubeconfig path for connecting the k8s cluster
- Get the current kubeconfig for vineyardctl.
Fixes #2796
=> Support users to only input the kubeconfig path for connecting the k8s cluster

.github/workflows/gae.yml, gs, k8s/dockerfiles/analytical.Dockerfile, k8s/dockerfiles/coordinator.Dockerfile, k8s/dockerfiles/graphscope-store.Dockerfile, k8s/dockerfiles/interactive-experimental.Dockerfile, k8s/dockerfiles/interactive.Dockerfile, k8s/dockerfiles/learning.Dockerfile, k8s/internal/Makefile
Fixes the CI failures introduced in https://github.com/alibaba/GraphScope/pull/2791
=> Add local python script path to PATH

interactive_engine/executor/assembly/groot/Cargo.toml, interactive_engine/executor/rust-toolchain.toml
=> disable debug-assert in groot

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/suite/standard/IrGremlinQueryTest.java
Committed-by: 有理 from Dev container
As title.
issue #2822
=> [GIE/tests] Add pattern matching test cases for GIE 

analytical_engine/core/fragment/dynamic_fragment.h, analytical_engine/core/fragment/fragment_reporter.h, python/graphscope/client/session.py, python/graphscope/framework/app.py, python/graphscope/framework/context.py, python/graphscope/framework/graph.py, python/graphscope/nx/classes/cache.py, python/graphscope/nx/classes/digraph.py, python/graphscope/nx/classes/graph.py, python/graphscope/nx/tests/classes/test_graphviews.py, python/requirements.txt, python/setup.py
=> Fixes the inconsistent usage of msgpack/json in graph reporter

docs/interactive_engine/tinkerpop_eco.md
The official python gremlin client lacks guidelines about how to use streaming apis, here give a java example instead. The python example will be added later.
Fixes
=> [GIE Doc] Add examples to collect gremlin results in a streaming way

docs/index.rst, docs/interactive_engine/faq.md, docs/interactive_engine/tinkerpop_eco.md, docs/interactive_engine/tinkerpop_gremlin.md
Committed-by: longbinlai from Dev container
Re-organized all Gremlin related documentations into a single doc, so that we can organize Cypher's doc in a similar way.
=> [GIE/docs] reorganize gremlin docs

.devcontainer/devcontainer.json
since the `Rebuild Container Without Cache` of VS code is [not work](https://github.com/microsoft/vscode-remote-release/issues/7104), this change using a workaround to pull newer image before create the container.
Fixes
=> Add a initializeCommand to `devcontainer.json`: always pull newer image before create container

coordinator/gscoordinator/op_executor.py
[code](https://github.com/alibaba/GraphScope/blob/086fa63622ee4fa67d8894fbcaee91e274ef550a/coordinator/gscoordinator/op_executor.py#L114) shows that when error message is too large, truncated to 30 chars. BUT A snippet of 30 chars is usually not enough to tell something useful. This change enlarge the 30 to 1024 to show more log.
Fixes #2864
=> [BugFix] Make the error message truncated not so aggressive

interactive_engine/executor/ir/runtime/src/assembly.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/get_v.rs
=> [BugFix] Fix bug in endV() after PathExpand

analytical_engine/java/grape-graphx/performance.md, analytical_engine/java/performance.md
Add performance evaluation for `grape-graphx`.
=> [Grape-Java] Add `grape-graphx` performance.md

python/graphscope/client/session.py, python/graphscope/framework/app.py, python/graphscope/framework/context.py, python/graphscope/framework/graph.py, python/graphscope/nx/classes/graph.py
The issue was first introduced in #2843. See also error messages in CI like https://github.com/alibaba/GraphScope/actions/runs/5222275661/jobs/9428251359
=> Update the pre-genereated unload_op when the op itself been deepcopied

analytical_engine/core/grape_instance.cc, interactive_engine/assembly/src/bin/graphscope/giectl, python/graphscope/interactive/query.py
=> fix munew line are not rendered correclty when multiple params are given

analytical_engine/java/grape-rdd-reader/pom.xml, analytical_engine/java/pom.xml
When upgrading `guava` for `GAE Java SDK`, there seems to be some problem with `maven-enforcer-plugin`. Relax this version control.
=> [GAE-Java] Relax version enforce for some mvn dependencies

analytical_engine/CMakeLists.txt
See also:
- https://github.com/protocolbuffers/protobuf/issues/12292
- the macos CI failure: https://github.com/alibaba/GraphScope/actions/runs/5271097039/jobs/9531496683
=> Use CONFIG mode to find protobuf to address the absl dependency issue.

k8s/internal/Makefile
See also:
- nightly CI failure in https://github.com/alibaba/GraphScope/actions/runs/5271097039/jobs/9531496683
=> Upgrade the graphlearn submodule to fixes nightly CI, refactor the Makefile for early error exit

.github/workflows/gae.yml, .github/workflows/k8s-ci.yml, .github/workflows/local-ci.yml, .github/workflows/networkx-forward-algo-nightly.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
To avoid failures like https://github.com/alibaba/GraphScope/actions/runs/5274772989/jobs/9539563789
=> Upload coverage: continue on error to avoid false negative on main branch

analytical_engine/core/app/app_invoker.h, coordinator/gscoordinator/cluster_builder.py
=> Print metrics of application running time

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/RpcExecutionClient.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, interactive_engine/executor/ir/clients/rust/client/src/physical_builder.rs, interactive_engine/executor/ir/common/src/utils.rs, interactive_engine/executor/ir/core/src/plan/ffi.rs, interactive_engine/executor/ir/core/src/plan/physical.rs, interactive_engine/executor/ir/integrated/tests/catalog_test.rs, interactive_engine/executor/ir/integrated/tests/join_test.rs, interactive_engine/executor/ir/integrated/tests/match_test.rs
Return physical plan bytes from ffi interface `build_physical_plan` directly,  instead of wrapping the physical plan in the JobRequest, which was previously bound to the pegasus engine API.
Fixes
=> [GIE] Refine FFI interface `build_physical_plan`

coordinator/gscoordinator/dag_manager.py, coordinator/gscoordinator/op_executor.py, python/graphscope/framework/dag_utils.py, python/graphscope/framework/graph.py, python/graphscope/proto/types.proto
Current graph serialization and deserialization is performed at client side, which should be done on coordiantor.
#1982
=> [good-first-issue]Move `save_to/load_from` from client side to coordinator

python/graphscope/analytical/app/sssp.py
=> Show explicit error message for SSSP run over a graph with no edge weight

analytical_engine/CMakeLists.txt
Opt-out the Java SDK when JNI is not found for more flexibility as the cmake option `ENABLE_JAVA_SDK` defaults to `ON`.
See also: #2809
=> Disable JAVA SDK (with a warning) when JNI not found

interactive_engine/compiler/src/main/antlr4/GremlinGS.g4, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/graph/RemoteTestGraph.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/suite/standard/IrGremlinTestSuite.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/LabelParser.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/ProjectResultParser.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransform.java
```gremlin
gremlin> g.V(1,2,4).elementMap()
==>{label=person, id=1, name=marko, id=1, age=29}
==>{label=person, id=2, name=vadas, id=2, age=27}
==>{label=person, id=4, name=josh, id=4, age=32}
gremlin> g.V(1,2,4).elementMap("name", "age")
==>{age=27, label=person, id=2, name=vadas}
==>{age=32, label=person, id=4, name=josh}
==>{age=29, label=person, id=1, name=marko}
gremlin> g.V().elementMap()
==>{label=person, id=2, name=vadas, id=2, age=27}
==>{label=software, id=72057594037927941, name=ripple, id=5, lang=java}
==>{label=person, id=1, name=marko, id=1, age=29}
==>{label=software, id=72057594037927939, name=lop, id=3, lang=java}
==>{label=person, id=4, name=josh, id=4, age=32}
==>{label=person, id=6, name=peter, id=6, age=35}
```
Compare to the official result,  now …
=> ElementMap step support

analytical_engine/test/run_vy_app.cc, coordinator/gscoordinator/builtin/app/.gs_conf.yaml, python/graphscope/tests/conftest.py, python/graphscope/tests/unittest/test_app.py
- use pagerank_local_parallel rather than pagerank_local
=> Use pagerank_local_parallel rather than pagerank_local for better performance

analytical_engine/core/fragment/arrow_projected_fragment.h, analytical_engine/core/fragment/dynamic_fragment.h, analytical_engine/core/fragment/fragment_reporter.h, analytical_engine/core/server/rpc_utils.h
Reduce the PrepareToRunApp time for twitter-2010 from >20s to about 2 seconds.
=> Parallelize the PrepareToRun implementation in projected fragment

interactive_engine/executor/assembly/v6d/src/bin/gaia_executor.rs
In some cases the server list is in different order inside different process, and yields unexpected partition dispatch plan, e.g.,
worker 1:
```
2023-06-30 04:55:27.508318003 INFO  (src/bin/gaia_executor.rs:167) [main] partition_lists before dedup = {1: [0, 1, 2, 3], 0: [0, 1, 2, 3]}
2023-06-30 04:55:27.508339604 INFO  (src/bin/gaia_executor.rs:177) [main] partition_lists = {1: [2, 3], 0: [0, 1]}
2023-06-30 04:55:27.508355604 INFO  (src/bin/gaia_executor.rs:190) [main] partition_server_index_map = {0: 0, 2: 1, 3: 1, 1: 0}
2023-06-30 04:55:27.508361404 INFO  (src/bin/gaia_executor.rs:105) [main] server_index: 0, partition_server_index_map: {0: 0, 2: 1, 3: 1, 1: 0}
2023-06-30 04:55:27.508449905 INFO  (/work/interactive_engine/executor/engine/pegasus/server/src/rpc.rs:314) [main] starting …
```
=> Sort the server list before iterate to keep consistent between workers

interactive_engine/compiler/conf/ir.compiler.properties, interactive_engine/compiler/src/main/antlr4/GremlinGS.g4, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/ExecutionClient.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/HttpExecutionClient.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/RpcExecutionClient.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/FrontendConfig.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/QueryTimeoutConfig.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/executor/GraphPlanExecution.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/executor/GraphQueryExecutor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/result/CypherRecordProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/GraphTraversalSourceVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/processor/IrTestOpProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/processor/AbstractResultProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrGremlinServer.java, interactive_engine/executor/engine/pegasus/clients/java/client/src/main/java/com/alibaba/pegasus/ClientExample.java, interactive_engine/executor/engine/pegasus/clients/java/client/src/main/java/com/alibaba/pegasus/RpcClient.java
Unify gremlin timeout configurations. By this pr, the console will output like this if gremlin query execution timeout is set to 2000ms.
Timeout can be set by two ways: 
1. system configuration, set `query.execution.timeout.ms: 2000` in `conf/ir.compiler.properties`
2. set per query in gremlin query `g.with(ARGS_EVAL_TIMEOUT, 2000).V()` or `g.with(Tokens.ARGS_EVAL_TIMEOUT, 2000).V()`. if timeout value is of long type, suffix with 'L'
Fixes #2854
=> [GIE Compiler] Unify Gremlin Timeout Configurations

python/setup.py
Fixes https://github.com/alibaba/GraphScope/actions/runs/5438100852/jobs/9889099878
See also: https://github.com/alibaba/graph-learn/pull/266
=> Fixes the "illegal thread local variable reference to regular symbol" error on macOS for GLE

docs/interactive_engine/tinkerpop/supported_gremlin_steps.md
=> Update the elementMap-step's doc of GIE

interactive_engine/executor/engine/pegasus/pegasus/src/communication/buffer.rs, interactive_engine/executor/store/exp_store/src/graph_db/csr_topo.rs
```
warning: unused return value of `std::boxed::Box::<T>::from_raw` that must be used
--> /Users/runner/work/GraphScope/GraphScope/interactive_engine/executor/engine/pegasus/pegasus/src/communication/buffer.rs:121:13
|
121 |             Box::from_raw(ptr.as_ptr());
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: call `drop(Box::from_raw(ptr))` if you intend to drop the `Box`
= note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
|
121 |             let _ = Box::from_raw(ptr.as_ptr());
|             +++++++
Compiling pegasus_server v0.1.0 (/Users/runner/work/GraphScope/GraphScope/interactive_engine/executor/engine/pegasus/server)
warning: `pegasus` (lib) generated 1 warning
Compiling timely v0.10.0
Compiling env_logger v0.7.1
Compiling …
```
=> Fixes two compliation warnings

.github/workflows/build-graphscope-wheels-linux.yml, .github/workflows/build-graphscope-wheels-macos.yml, Makefile, coordinator/gscoordinator/op_executor.py, coordinator/gscoordinator/template/CMakeLists.template
Use Java 11 on CI as it is required since https://github.com/alibaba/GraphScope/commit/30e45e0edacaa6e6edc58259a41c9e0ed5f27b1b
Fixes https://github.com/alibaba/GraphScope/actions/runs/5447760850/jobs/9910147098
=> Install jdk 11 on MacOS CI and fixes the GAE link failure in nightly CI on MacOS

interactive_engine/executor/assembly/groot/src/executor/gaia/engine_ports_response.rs, interactive_engine/executor/assembly/groot/src/executor/gaia/gaia_library.rs, interactive_engine/executor/assembly/groot/src/executor/gaia/gaia_server.rs, interactive_engine/executor/assembly/groot/src/store/backup.rs, interactive_engine/executor/assembly/groot/src/store/ffi.rs, interactive_engine/executor/assembly/groot/src/store/graph.rs, interactive_engine/executor/assembly/groot/src/store/jna_response.rs, interactive_engine/executor/store/groot/Cargo.toml, interactive_engine/executor/store/groot/src/db/graph/types/edge.rs, interactive_engine/executor/store/groot/src/db/storage/rocksdb.rs, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/StoreService.java
1. Fix memory leak in groot
2. Fix compiler warnings
3. Bump up version of rocksdb and crossbeam-epoch
4. Add trace logs
Fixes #2819
=> Fix memory leak in groot and add trace logs

.github/workflows/gss.yml, .github/workflows/k8s-ci.yml
* Add the previous logs of restarted pods.
* Add the description info of not running pods.
* Add the pod yaml of the specific pods.
Actually, the current kubernetes-log-export-action will export all needed debugging info:
- Pod logs.
- Previous logs for restarted pods.
- Pod yamls.
- Pod description info.
- Events in the specific namespaces.
Signed-off-by: Ye Cao <caoye.cao@alibaba-inc.com>
Committed-by: Ye Cao from Dev container
=> Bump up the version of kubernetes-log-export-action to v5

coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/kubernetes_launcher.py, coordinator/gscoordinator/local_launcher.py
1. Add timeout parameters for coordinations such that they can be adjusted via arguments;
2. Add retry time parameters for coordinations such that they can be adjusted via arguments;
3. Refine the logic of testing timeout to avoid the unwanted error if timeout is less than retry time;
4. Correct a typo in a function name.
Fixes #2734
=> [Coordinator] Fix issue #2734: unifying timeout parameter in coordinators

docs/interactive_engine/tinkerpop/tutorial_ldbc_gremlin.md
In some previous commits, figures in the GIE LDBC tutorial failed to display due to file structure modifications. This commit has resolved the issues related to figure display.
=> Fix figure display issues in GIE LDBC tutorial

interactive_engine/executor/ir/core/src/plan/logical.rs, interactive_engine/executor/ir/runtime/src/process/operator/source.rs, python/graphscope/tests/minitest/test_min.py
=> [BugFix] Fix bug when process pk scan of multiple labels

.github/workflows/docs.yml
With this PR merged, new checks are introduced:
- the PR titles should follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/),  
which in the format of `<type>(<scope>): <description>`. e.g., 
- fix: Correct typo
- feat(interactive): Add support for `g.V().outE().inV()`
- refactor!: Drop support for Python 3.8
- feat(analytical): Add delta-version for PageRank
- if the PR is in type of `feat(<scope>):`, then documentation must be updated.
=> ci: Add check for conventional commit and docs

docs/analytical_engine/design_of_gae.md, docs/analytical_engine/performance_tuning.md
=> Add the performance & tunning page for GAE

.github/workflows/pr-check.yml, docs/development/how_to_contribute.md
With this PR merged, new checks are introduced:
the PR titles should follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/), which in the format of <type>(<scope>): <description>. e.g.,
- fix: Correct typo
- feat(interactive): Add support for g.V().outE().inV()
- refactor!: Drop support for Python 3.8
- feat(analytical): Add delta-version for PageRank
if the PR is in type of `feat(<scope>):`, then documentation must be updated.
=> ci: add conventional checks for PR title and docs

.github/workflows/docs.yml, .github/workflows/pr-check.yml
The submodule was first introduced in #3010 and it should be removed before `git add -A` to gh-pages.
Fixes https://github.com/alibaba/GraphScope/actions/runs/5665819421/job/15351324239
=> fix: Fixes error in docs generation by removing the submodule

analytical_engine/CMakeLists.txt, analytical_engine/java/grape-giraph/pom.xml, analytical_engine/java/grape-giraph/src/test/java/com/alibaba/graphscope/serialization/FFIByteVectorStreamTest.java, analytical_engine/java/grape-jdk/pom.xml, analytical_engine/java/grape-runtime/build.xml, analytical_engine/java/grape-runtime/pom.xml, analytical_engine/java/grape-runtime/src/main/java/com/alibaba/graphscope/runtime/GraphScopeClassLoader.java, analytical_engine/java/grape-runtime/src/main/java/com/alibaba/graphscope/runtime/LoadLibrary.java, analytical_engine/java/pom.xml
Committed-by: zhanglei1949 from Dev container
Currently we pack the `libgrape-jni.so/dylib` into `grape-runtime-shaded-{}.jar` and  use `NativeLibLoader` to load the jni lib at runtime. But If we want to package `GRAPE-jdk` into GraphScope wheel package, we need to user `auditwheel` to reorg the dynamic linking and RPATH staffs.
So maybe we should abandon current approach, just copy `libgrape-jni` to /opt/graphscope/lib, such that is can be found by auditwheel.
Related Issue: #3064
=> refactor(analytical): Remove `nativeLibLoader` in GRAPE-jdk

analytical_engine/core/fragment/arrow_flattened_fragment.h
fix error: wrong result when flatten from projected data
Fixes
=> fix(analytical): fixes wrong result when flatten from projected arrow fragment

coordinator/gscoordinator/local_launcher.py, coordinator/gscoordinator/utils.py
Previously it could not auto detect grape_engine from `/opt/graphscope`, need to rely on `GRAPHSCOPE_HOME` be set.
Also try to simplify the logic to probe GRAPHSCOPE_HOME, and others. But its still messy.
And delete the unused `.install_prefix` usage.
=> chore: Refine the logic to probe GRAPHSCOPE_HOME

interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/OfflineBuildOdps.java
Suppose the source file `config.init` contains a line
```json
{"xxx/${bizdate}": "${another-var}"
```
User could substitute the variables in `${}` by specify `key=value` in the command line:
```bash
java -jar data-load-tools.jar config.init bizdate=20180808 another-var=value
```
Then in runtime the content of `config.init` will be replaced to
```json
{"xxx/20180808": "value"}
```
=> chore: allow user pass variables for substitutions

interactive_engine/executor/assembly/groot/src/executor/gaia/gaia_library.rs, interactive_engine/executor/common/dyn_type/Cargo.toml, interactive_engine/executor/common/dyn_type/src/serde.rs, interactive_engine/executor/common/dyn_type/src/serde_dyn.rs, interactive_engine/executor/store/groot/src/db/common/mod.rs, interactive_engine/executor/store/groot/src/db/common/unsafe_util.rs, interactive_engine/executor/store/groot/src/db/graph/iter.rs, interactive_engine/executor/store/groot/src/db/graph/store.rs, interactive_engine/executor/store/groot/src/db/graph/types/edge.rs
This pull request fixes some incompatible issues with recently stable Rust compilers (>=1.72.0).
- TypeId casting:
The `TypeId` in rust becomes `i128` since https://github.com/rust-lang/rust/commit/9e5573a0d275c71dce59b715d981c6880d30703a, makes the original `std::mem::transmute` stop working.
- The ref to mut-ref `&mut *(t as *const T as *mut T)` has become undefined behaviour since Rust 1.70, and was rejected by recent nightly compilers.
- The `EdgeInfo::kinds` yields a anti-pattern design for Rust (a constant Vec is modified without any protection). This pull request adds a lock to the `kinds` vector, and refactors its iter implementation to make it safer (and, can be compiled).
=> fix(interactive): fixes some unsafe rust code that cannot be compiled with recent stable rust compilers

.cirrus.yml, .github/workflows/build-graphscope-wheels-macos.yml, .github/workflows/nightly.yml, README-zh.md, README.md, docs/analytical_engine/dev_and_test.md, docs/deployment/install_on_local.md, docs/development/dev_guide.md, docs/development/how_to_test.md, docs/interactive_engine/dev_and_test.md, docs/learning_engine/dev_and_test.md, docs/zh/deployment.rst, docs/zh/developer_guide.rst, python/graphscope/gsctl/gsctl.py, python/graphscope/gsctl/scripts/install_deps_command.sh
Added the test method to gsctl.
Modify files associated with gsctl.
issue #3074
=> refactor: Upgrade gsctl and modify files associated with gsctl

README.md
The readme.md might be rendered somewhere outside the github repo, where the relative link won't work, e.g., pypi.
=> chore: fixes the link for the flex directory

analytical_engine/core/object/fragment_wrapper.h, charts/graphscope-store/values.yaml, docs/storage_engine/groot.md, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/example/BuildSchema.java, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/example/RealtimeWrite.java, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/example/TestUtils.java, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/schema/EdgeLabel.java, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/schema/Label.java, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/schema/Property.java, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/schema/Schema.java, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/schema/VertexLabel.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/wal/kafka/KafkaLogWriter.java, proto/schema_common.proto
- Encapsulate GraphDefPb into customized class `Schema`
- Set a high bytes default for kafka producer.
Fixes #3192
=> feat(interactive): Add schema management ability for groot java sdk

interactive_engine/executor/common/dyn_type/Cargo.toml, interactive_engine/executor/common/dyn_type/src/error.rs, interactive_engine/executor/common/dyn_type/src/lib.rs, interactive_engine/executor/common/dyn_type/src/object.rs, interactive_engine/executor/common/dyn_type/src/serde.rs, interactive_engine/executor/common/dyn_type/tests/date_formats.rs, interactive_engine/executor/common/dyn_type/tests/datetime_formats.rs, interactive_engine/executor/common/dyn_type/tests/object.rs
=> refactor(interactive): Support DateFormats in GIE Runtime

docs/interactive_engine/tinkerpop/supported_gremlin_steps.md, interactive_engine/executor/ir/core/src/plan/logical.rs, interactive_engine/executor/ir/core/src/plan/physical.rs, interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/path.rs, interactive_engine/executor/ir/integrated/tests/pathxd_test.rs, interactive_engine/executor/ir/runtime/src/assembly.rs, interactive_engine/executor/ir/runtime/src/process/operator/filter/mod.rs, interactive_engine/executor/ir/runtime/src/process/operator/filter/path_condition.rs
As titled. We support to project property of a `path`, i.e., we project the property of each element in `path`. 
e.g., on modern graph:
```
gremlin> g.V().out("1..3", "knows").with('RESULT_OPT', 'ALL_V').values("name")
==>[marko, vadas]
==>[marko, josh]
```
Fixes #3199
=> feat(interactive): support project properties of a `path`

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/suite/standard/IrGremlinQueryTest.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/LabelParser.java
When converting a label name into an ID, it is necessary to first infer whether it is a vertex label or an edge label based on the operator preceding the elementMap. There will be issues when the preceding operator falls into one of the following categories: 
1. When the preceding operator is an `ExpandFusionStep` after optimization (fusion of outE + filter + inV); 
2. When the preceding operator is an operator like `limit` or `where` that does not change the input type.
This PR addresses the two issues mentioned above.
fix #3219 
Fixes
=> fix(interactive): Fix bugs in Label Name to Id Conversion

interactive_engine/assembly/src/conf/groot/logback.xml, interactive_engine/executor/assembly/groot/src/store/graph.rs, interactive_engine/executor/common/dyn_type/src/serde.rs, interactive_engine/executor/ir/core/src/plan/logical.rs, interactive_engine/executor/store/groot/src/api/mod.rs, interactive_engine/executor/store/groot/src/db/graph/iter.rs, interactive_engine/executor/store/groot/src/db/graph/store.rs, interactive_engine/executor/store/groot/src/db/graph/types/edge.rs, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/GrootClient.java, interactive_engine/groot-client/src/main/java/com/alibaba/graphscope/groot/sdk/schema/Edge.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/ClientWriteService.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/write/GraphWriter.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/operation/EdgeId.java
- Add API for writing vertices and edges in one batch
- Add eid to the Edge class in client
- Update an not existing edge will create a new edge.
- Update and Delete when eid is not given will try to search for it by src and dst vertex first.
=> fix(interactive): Not requiring eid in update/delete edges in groot

charts/graphscope-store/templates/configmap.yaml, interactive_engine/assembly/src/bin/groot/store_ctl.sh, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/util/PkHashUtils.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/DataBuildMapper.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/DataBuildMapperOdps.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/DataBuildMapperOdpsDebug.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/DataBuildReducerOdps.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/DataEncoder.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/OfflineBuild.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/OfflineBuildOdps.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/OfflineBuildOdpsDebug.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/SstOutputFormat.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/SstRecordWriter.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/Utils.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/external/ExternalStorage.java
1. Fix that partspec is not included in the table identifier that caused label id could not be correctly retrieved.
2. Disable the backup instance of reducer, which could truncated the file that uploaded to volume.
3. Limit the total size of log files.
=> fix(interactive): Fix several bugs in data-load-tools 

flex/interactive/examples/modern_graph/modern_graph.yaml, flex/storages/rt_mutable_graph/README.md, flex/storages/rt_mutable_graph/schema.cc
User now can put `x_csr_params` to provide csr-related configuration for each edge triplet.
=> fix(flex): Support set edge strategy on each `vertex_type_pair_relation`

.gitmodules, Makefile, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/kubernetes_launcher.py, coordinator/gscoordinator/launch_graphlearn.py, coordinator/gscoordinator/launch_graphlearn_torch.py, coordinator/gscoordinator/launcher.py, coordinator/gscoordinator/local_launcher.py, docs/learning_engine/guide_and_examples.md, docs/learning_engine/tutorial_node_classification_pyg_local.md, examples/local_glt.py, proto/message.proto, python/graphscope/__init__.py, python/graphscope/client/rpc.py, python/graphscope/client/session.py, python/graphscope/learning/gl_torch_examples/local.py, python/graphscope/learning/gl_torch_graph.py, python/graphscope/learning/graphlearn_torch, python/requirements.txt, python/setup.cfg, python/setup.py
This PR integrates [GLTorch](https://github.com/alibaba/graphlearn-for-pytorch) into GraphScope, allowing training GNNs using GLTorch in the local mode of GraphScope.
=> feat(learning): Integrate GLTorch into GraphScope

.cirrus.yml, .github/workflows/build-graphscope-wheels-macos.yml, README-zh.md, README.md, docs/deployment/install_on_local.md, docs/interactive_engine/getting_started.md, docs/zh/deployment.rst, docs/zh/frequently_asked_questions.rst, docs/zh/installation.rst, k8s/internal/Makefile
See also: https://github.com/alibaba/GraphScope/actions/runs/6460682621/job/17538859836
```
Warning: You are using macOS 11.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or …
```
=> ci: requires macos 12 as homebrew (and apple) do not provide support for this old version

analytical_engine/apps/pregel/louvain/auxiliary.h, analytical_engine/apps/pregel/louvain/louvain.h, analytical_engine/apps/pregel/louvain/louvain_app_base.h, analytical_engine/apps/pregel/louvain/louvain_context.h, analytical_engine/apps/pregel/louvain/louvain_vertex.h
baseline 初始engine内存50M， p2p 图 50M，运行louvain 额外内存 300 M
- 存临时的边结构 map -> vector  额外内存 300 M -> 250 M
- 及时清除无用的临时 edge 和 nodes  250 M -> 232 M
- vid_type uint64 -> uint32, edata double -> float  232 M -> 151 M
注意：
- 如要使用 uint32 作为 vid 类型, 载图时指定 vid_type `sess.g(vid_type='uint32')`
- map 换成 vector 之后，算法效率会有所下降，具体为通过终点找边时，必须遍历 vector，时间复杂度为 O(E)，E 为构建出来的社区新边的大小。一般来说，会比原图小很多。
Fixes #3244
=> fix(analytical): reduce louvain memory usage

python/graphscope/gsctl/scripts/install_deps_command.sh, python/graphscope/gsctl/scripts/lib/install_vineyard.sh
The `command -v` is not what we want actually, removing.
Fixes https://github.com/alibaba/GraphScope/actions/runs/6525924157/job/17719124120
=> ci: fixes the check of libarrow-dev existence on Ubuntu

.github/workflows/local-ci.yml, k8s/internal/Makefile, python/requirements-dev.txt, python/requirements.txt, python/setup.py
- Don't pin the pytorch version
- Move the pytorch dependency to `requirements-dev.txt` instead of `requirements.txt`, as it is so large and not everyone need it.
- Install pytorch where it is being required (the same logic with tensorflow)
- Make sure it has been installed before building the client wheels (otherwise the gltorch part would be skipped)
Fixes https://github.com/alibaba/GraphScope/actions/runs/6525923593/job/17719122557
=> ci: fixes the handling the pytorch dependency

.github/workflows/k8s-ci.yml, .github/workflows/local-ci.yml, python/graphscope/nx/conftest.py, python/graphscope/tests/conftest.py, python/requirements-dev.txt
To fixes cases like python tests are all passed but the pytest process failed with segfault, causing a "RED" mark.
Fixes failures like: https://github.com/alibaba/GraphScope/actions/runs/6542043095/job/17765519436
=> ci: run test cases in subprocess with pytest-sdist

interactive_engine/executor/ir/common/src/utils.rs, interactive_engine/executor/ir/core/src/plan/logical.rs, interactive_engine/executor/ir/runtime/src/process/operator/source.rs
=> fix(interactive): Support Index predicate with multiple expected values given via P.within()

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphBuilder.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/GraphBuilderVisitor.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/antlr4/MatchTest.java
This PR fixes a bug related to queries like `Match (a) Match (a)-[]->(b), (b)-[]->(c) Return a, b`, where there are multiple sentences in the second Match clause, causing issues when converting such matches into join structures.
Fixes
=> fix(interactive): Fix Bugs in Converting Match into Join

.github/workflows/build-graphscope-wheels-macos.yml
Seems that the default Python version has been bumped up to 3.12.
Fixes https://github.com/alibaba/GraphScope/actions/runs/6763190139/job/18380023533
=> ci: explicitly set python version on MacOS CI

interactive_engine/compiler/src/main/antlr4/GremlinGS.g4, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/Configs.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/GraphTraversalSourceVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/GremlinAntlrToJava.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/script/AntlrGremlinScriptEngine.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/traversal/IrCustomizedTraversalSource.java
make pegasus.XX settings configurable per query:
```
g.with(pegasus.worker.num, 2).V()
g.with(pegasus.batch.size, 64).V()
g.with(pegasus.output.capacity, 64).V()
```
the priority is : query > system env > system property > config file
Fixes #3318
=> fix(interactive): Make Pegasus Related Settings Configurable Per Query

flex/storages/rt_mutable_graph/loader/csv_fragment_loader.cc
Fix a bug in CSVFragmentLoader.  Previous implementation fails to parse header to some files if the header lines contains more than one spaces or other characters.
=> fix(interactive): Fix a bug for CSVFragmentLoader

interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/read_graph.rs, interactive_engine/executor/store/global_query/src/store_impl/groot/global_graph.rs
Previously, when query a vertex by pk, it doesn't check whether the vertex exists.
```
g.V().has('person', 'id', 1)
```
This PR will do a lookup in the database and return empty if not exists.
=> fix(interactive): Check vertex existence whenever queried

.github/workflows/flex.yml, docs/flex/interactive/data_model.md, flex/engines/graph_db/database/graph_db_session.cc, flex/engines/graph_db/database/transaction_utils.h, flex/engines/graph_db/database/update_transaction.cc, flex/engines/graph_db/grin/predefine.h, flex/engines/graph_db/grin/src/index/pk.cc, flex/engines/graph_db/grin/src/predefine.cc, flex/engines/graph_db/grin/src/property/primarykey.cc, flex/engines/graph_db/grin/src/property/property.cc, flex/engines/graph_db/grin/src/property/row.cc, flex/engines/graph_db/grin/src/topology/structure.cc, flex/engines/hqps_db/core/operator/sink.h, flex/engines/hqps_db/database/mutable_csr_interface.h, flex/engines/hqps_db/structures/multi_edge_set/untyped_edge_set.h, flex/storages/rt_mutable_graph/loader/csv_fragment_loader.cc, flex/storages/rt_mutable_graph/loading_config.cc, flex/storages/rt_mutable_graph/mutable_csr.cc, flex/storages/rt_mutable_graph/mutable_property_fragment.cc, flex/storages/rt_mutable_graph/schema.cc, flex/storages/rt_mutable_graph/types.h, flex/utils/arrow_utils.cc, flex/utils/arrow_utils.h, flex/utils/id_indexer.h, flex/utils/property/column.cc, flex/utils/property/column.h, flex/utils/property/types.cc, flex/utils/property/types.h
Add more data type support for vertex/edge property, now we support the following types.
- DT_SIGNED_INT32
- DT_UNSIGNED_INT32
- DT_SIGNED_INT64
- DT_UNSIGNED_INT64
- DT_BOOL
- DT_FLOAT
- DT_DOUBLE
- DT_STRING
- DT_DATE32
The vertex property column of following types can be used as primary key column
- DT_SIGNED_INT32
- DT_UNSIGNED_INT32
- DT_SIGNED_INT64
- DT_UNSIGNED_INT64
- DT_STRING
=> feat(interactive): Support more data types for vertex/edge property

charts/graphscope-store-one-pod/templates/configmap.yaml, charts/graphscope-store-one-pod/values.yaml, charts/graphscope-store/templates/configmap.yaml, charts/graphscope-store/values.yaml, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/FrontendConfig.java, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/impl/DefaultGraphEdge.java, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/impl/DefaultGraphSchema.java, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/mapper/EdgeTypeMapper.java, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/mapper/ElementIndexMapper.java, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/mapper/VertexTypeMapper.java, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/util/PkHashUtils.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/DataEncoder.java, interactive_engine/data-load-tool/src/main/java/com/alibaba/graphscope/groot/dataload/databuild/OfflineBuildOdps.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/write/DefaultEdgeIdGenerator.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/write/EdgeIdGenerator.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/frontend/write/GraphWriter.java, interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/Frontend.java
extension use hash(srcId, dstId, edgeLabelId, edgePks) to generate eid.
It can support edge update scenarios where eid is not known in advance.
Compatible with the original way of generating eid, use "enable.hash.generate.eid parameter" to judge
if enable.hash.generate.eid parameter=true:
use hash generate
else:
use increase generate
Fixes
=> fix(interactive): extension use hash(srcId, dstId, edgeLabelId, edgePks) instead of increase eid

flex/storages/rt_mutable_graph/loader/csv_fragment_loader.cc
=> fix(interactive): Comparison between `std::shared_ptr<arrow::DataType>` should use `Equals()`

.github/workflows/docker/graphscope-store.Dockerfile, .github/workflows/docker/interactive-experimental-local-artifacts.Dockerfile, k8s/dockerfiles/coordinator.Dockerfile, k8s/dockerfiles/graphscope-dev.Dockerfile, k8s/dockerfiles/graphscope-store.Dockerfile, k8s/dockerfiles/interactive-experimental.Dockerfile, k8s/dockerfiles/interactive.Dockerfile, k8s/dockerfiles/vineyard-dev.Dockerfile, k8s/dockerfiles/vineyard-runtime.Dockerfile
Fixes https://github.com/v6d-io/v6d/issues/1618
=> chore: fixes the missing tzdata issue in graphscope ubuntu-22.04 based images

.github/workflows/docker/graphscope-store.Dockerfile, .github/workflows/docker/interactive-experimental-local-artifacts.Dockerfile, k8s/dockerfiles/coordinator.Dockerfile, k8s/dockerfiles/graphscope-dev.Dockerfile, k8s/dockerfiles/graphscope-store.Dockerfile, k8s/dockerfiles/interactive-experimental.Dockerfile, k8s/dockerfiles/interactive.Dockerfile, k8s/dockerfiles/vineyard-dev.Dockerfile, k8s/dockerfiles/vineyard-runtime.Dockerfile
Fixes https://github.com/alibaba/GraphScope/issues/3364
See also: https://github.com/alibaba/GraphScope/pull/3363
=> chore: make sure tzdata can be installed

interactive_engine/executor/engine/pegasus/common/src/rc.rs, interactive_engine/executor/engine/pegasus/pegasus/src/errors/mod.rs, interactive_engine/executor/engine/pegasus/pegasus/src/lib.rs, interactive_engine/executor/engine/pegasus/pegasus/src/worker.rs
Fixes
https://github.com/alibaba/GraphScope/issues/3366
=> fix(interactive): fix memory leak in pegasus

interactive_engine/executor/assembly/groot/Cargo.toml, interactive_engine/executor/build.sh
Also upgrades tonic version to fix warnings.
=> fix(interactive): Add a new release-with-debug-info profile

.github/workflows/k8s-ci.yml, charts/gie-standalone/templates/frontend/statefulset.yaml, charts/gie-standalone/values.yaml, docs/interactive_engine/deployment.md, docs/storage_engine/groot.md, interactive_engine/compiler/conf/ir.compiler.properties, interactive_engine/compiler/set_properties.sh, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/Config.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/FrontendConfig.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/manager/RateLimitExecutor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/QueryStatusCallback.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/processor/AbstractResultProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrGremlinServer.java, interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/ir/IrServiceProducer.java
1. add rate limiter for control flow.
2. write exception logs from executor to notify its unexpected behaviors.
Fixes
=> feat(interactive): Add Rate Limiter for Control Flow

interactive_engine/executor/ir/core/src/plan/ffi.rs, interactive_engine/executor/ir/core/src/plan/logical.rs, interactive_engine/executor/ir/core/src/plan/meta.rs
Improve the performance of checking if a given label sets contain all labels in the schema
=> refactor(interactive): Improve the code of checking if a given label sets contain all labels in the schema 

interactive_engine/benchmark/README.md
The main fix was for the README quickstart module description in the GIE benchmark, where an error was found that was inconsistent with the current code directory structure.
Fixes #3388
=> docs: Fix GIE Benchmark Readme bug

interactive_engine/executor/engine/pegasus/pegasus/src/event/emitter.rs, interactive_engine/executor/engine/pegasus/pegasus/src/worker.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/limit_test.rs
Fixes
https://github.com/alibaba/GraphScope/issues/3177
=> fix(interactive): event message error

interactive_engine/executor/engine/pegasus/pegasus/src/operator/concise/count.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/fold_test.rs
Fixes
https://github.com/alibaba/GraphScope/issues/3177
https://github.com/alibaba/GraphScope/issues/3370
=> fix(interactive): fix peers_contains bugs in count operator in subtasks

interactive_engine/executor/engine/pegasus/pegasus/src/operator/iteration/mod.rs, interactive_engine/executor/engine/pegasus/pegasus/src/stream.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/iteration_test.rs
Fixes
https://github.com/alibaba/GraphScope/issues/3177
Query2
=> fix(interactive): fix unexpect result of operator aggregate() + iterate()

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/MetricsCollector.java
Use `System.currentTimeMillis()` to obtain the start time of a query execution, instead of `System.nanoTime()`. The latter should only be used to calculate elapsed time and is not related to any other notion of system or wall-clock time.
Fixes
=> fix(interactive): Fix Start Time Metric in Compiler Log

docs/flex/interactive/development/admin_service.md, flex/bin/bulk_loader.cc, flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/handler/hqps_http_handler.cc, flex/engines/http_server/handler/hqps_http_handler.h, flex/engines/http_server/options.h, flex/engines/http_server/service/hqps_service.cc, flex/engines/http_server/service/hqps_service.h, flex/engines/http_server/workdir_manipulator.cc, flex/tests/hqps/hqps_admin_test.sh
When a `StartService(graph)` is received by admin service, we will 
1.  The actor scope for current query actors will be cancelled.
2. During the scope cancellation process of the query actors or after scope cancellation is completed, all requests sent to the query_service will fail and be rejected. 
The response of the http request will be like
```json
{
"code": 500,
"message" : "Unable to send message, the target actor has been canceled!"
}
```
3. After the previous graph is closed and new graph is opened, the new query actors will be available in a new scope. 
4. The query service is now ready to serve requests on the new graph.
Fix #3394
=> feat(interactive): Introduce explicit barrier for actors when switching query service to a different graph

flex/CMakeLists.txt
Remove one gcc option `-mno-avx512f` for flex's CMakeLists.txt. Which cause `find_package(MPI)` error on macos arm arch.
Fix #3430
=> fix(interactive): Remove gcc option `-mno-avx512f` 

interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/external/ExternalStorage.java
Due to the instability of the network and tunneling tools, a certain store encountered an error while downloading the original file. At this point, the file already exists but only a portion has been downloaded, causing subsequent retry operations to result in a `FileAlreadyExisted` error. This PR addresses the issue by enabling the `REPLACE_EXISTING` option, allowing the overwriting of existing files.
Fixes
=> fix(interactive): Fix bugs of Groot Bulk Load When Retrying to Download Source Files

flex/storages/rt_mutable_graph/file_names.h
Fix [#3447](Fixeshttps://github.com/alibaba/GraphScope/issues/3447)
=> fix(interactive): Fix the Invalid cross-device link error occurring with copy_file_range in the Docker environment.

analytical_engine/apps/pregel/louvain/auxiliary.h, analytical_engine/apps/pregel/louvain/louvain_app_base.h, python/graphscope/nx/algorithms/tests/builtin/test_cluster.py, python/graphscope/tests/unittest/test_app.py, python/graphscope/tests/unittest/test_lazy.py
This change try to fix the louvain algorithm that the result is not consistent with #183
Close #3457
=> fix(analytical): fix the louvain algorithm that the result is not consistent with #183

analytical_engine/CMakeLists.txt
=> fix(analytical): Fix the rapidjson find_package

flex/CMakeLists.txt, flex/bin/rt_server.cc, flex/engines/graph_db/database/graph_db.cc, flex/engines/graph_db/database/graph_db.h, flex/storages/rt_mutable_graph/dual_csr.h, flex/storages/rt_mutable_graph/mutable_csr.h, flex/storages/rt_mutable_graph/mutable_property_fragment.cc, flex/storages/rt_mutable_graph/mutable_property_fragment.h, flex/utils/allocators.h, flex/utils/id_indexer.h, flex/utils/mmap_array.h, flex/utils/property/column.cc, flex/utils/property/column.h, flex/utils/property/table.cc, flex/utils/property/table.h
Passing parameter "--memory-level=n" to rt_server to configure memory allocation strategy.
- n = 0: memory allocation will be mmap to files in SHARED mode. Suitable for scenarios with severe memory constraints.
- n = 1: memory allocation will be mmap to files in PRIVATE mode. The modified parts in the storage cannot be swapped to disk; if the modified portions become too large, it may lead to a crash due to insufficient memory.
- n = 2: the storage of certain data will utilize hugepages, which can enhance the system's throughput. However, the portion using hugepages will be fixed in memory usage, and hugepages require static allocation.
- n = 3: the storage of all data will endeavor to make use of hugepages as much as possible.
=> feat(flex): Configure the memory strategy with memory-level.

.github/workflows/build-graphscope-wheels-macos.yml, .github/workflows/gae.yml, .github/workflows/networkx-forward-algo-nightly.yml, .github/workflows/nightly.yml, k8s/Makefile, k8s/actions-runner-controller/manylinux/Makefile, k8s/internal/Makefile, scripts/install_deps.sh
The PR is to fix the bug caused by the version mismatch of vineyard in the graphscope-dev image.
As:
https://github.com/alibaba/GraphScope/actions/runs/7771225038/job/21192444777
https://github.com/alibaba/GraphScope/actions/runs/7753022954/job/21144025198
Also, the dev image updated.
https://github.com/alibaba/GraphScope/actions/runs/7773830300
=> fix(k8s): Bump up vineyard to v0.20.3

interactive_engine/compiler/pom.xml
This pr add a profile in compiler's pom.xml.
This pom.xml can generate a fat-jar and package libircore.so within the jar when the procedure-generator profile is specified.
To generate a compiler's fat-jar, run
`mvn clean package -DskipTests -Drevision=0.0.1-SNAPSHOT -Pexperimental,procedure-generator`
in directory GraphScope/interactive_engine
https://github.com/alibaba/GraphScope/issues/3573
=> feat(interactive): Add profile to build compiler fat-jar

.gitignore, analytical_engine/java/pom.xml, python/graphscope/analytical/app/java_app.py
Fix #3616 
Also use a maven plugin for solve the problem of `mvn install -Drevision={}` doesn't replace the `revision` tag in child modules.
=> fix(analytical): Fix graph template parsing in Java SDK

flex/bin/load_plan_and_gen.sh, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/procedure/StoredProcedureMeta.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphPlanner.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/config/YamlConfigTest.java, interactive_engine/compiler/src/test/resources/config/modern/plugins/ldbc_ic2.yaml
Add optional field `type: cpp/cypher` and `queryStr: ` for stored procedure's metadata. The queryStr could be cypher query or c++ code.
=> refactor(interactive): Add type and queryStr for `StoredProcedureMeta`

python/graphscope/gsctl/scripts/lib/install_vineyard.sh
Enable the BUILD_VINEYARD_GRAPH_WITH_GAR compile option in gsctl
Fixes
=> fix(python): Enable the BUILD_VINEYARD_GRAPH_WITH_GAR compile option in gsctl

flex/bin/interactive_server.cc
As titled, causing CI failure for hqps-db-ci
=> fix(interactive): Fix argument parsing for `enable-admin-service`

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/processor/IrTestOpProcessor.java
The issue is caused by PR #3630, which changed the result collection from asynchronous to synchronous. After submitting a request to the client, it is necessary to actively call a request to retrieve the result from the buffer. However, the test chain forgot to add this call, leading to the problem. This PR mainly fix the issue.
Fixes
=> fix(interactive): Fix CI Bug Caused By PR #3630

flex/engines/http_server/workdir_manipulator.cc, flex/tests/hqps/admin_http_test.cc, flex/utils/yaml_utils.cc, flex/utils/yaml_utils.h
`YAML::Emitter` will convert a `int` value to `string`, which is not desired.
We Implement a converter which convert a yaml to json.
=> fix(interactive): Fix the incorrect casting from int into string when converting from `YAML` to `JSON`

k8s/internal/Makefile
- Fixed `delocate` version in 0.10.7
- Correctly find torch library by setting `DYLD_LIBRARY_PATH` env
=> ci: Fixes CI failure on macOS

coordinator/gscoordinator/op_executor.py, python/graphscope/framework/loader.py
Or it would be pass to the storage backend.
Fixes #3682
=> fix(python): filetype should be in read_options

docs/flex/interactive/development/admin_service.md, flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/actor/admin_actor.act.h, flex/engines/http_server/handler/admin_http_handler.cc
Add support for stop the interactive query service.
=> feat(interactive): Support stopping query service

docs/flex/interactive/development/admin_service.md, flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/actor/admin_actor.act.h, flex/engines/http_server/handler/admin_http_handler.cc, flex/engines/http_server/handler/admin_http_handler.h, flex/engines/http_server/handler/http_utils.cc, flex/engines/http_server/handler/http_utils.h
- Internally use `Result<>` to store the runtime error, and map the error to http code at `admin_http_handler`.
- Extract commonly used code into utils function `http_utils.h`.
=> refactor(interactive): Return the correct http code

flex/bin/bulk_loader.cc
When `bulk_loader` fails or got cancelled, we should clean the data directory, avoid leaving a consistent data directory.
=> fix(interactive): Clean data_dir when bulk_loader fails or cancelled

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/RpcExecutionClient.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/type/ExecutionRequest.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/QueryIdGenerator.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/executor/GraphQueryExecutor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/processor/IrTestOpProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/QueryLogger.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/LifeCycleSupplier.java
Re-implement `QueryIdGenerator` strategy to avoid duplicated plan id generation after failover. The new implemented function is to assign a unique job id for the query, which needs to ensure uniqueness in time and space. 
Specifically, for queries a and b, the following two cases are required not to produce duplicated plan ids:
1. When query a and b are sent to the same frontend but at different times;
2. When query a and b are sent to different frontends, regardless if the timestamps are the same or not;
This requires us to implement the functionality of `UUID`. The default Java `UUID` is composed of 128 bits, with the first 64 bits determined by timestamp and the latter 64 bits composed of MAC address plus other items. However, our job id is made up of 64 bits, and converting 128 bits …
=> fix(interactive): Fix Bug of Duplicated Plan Id Generation After Failover

analytical_engine/apps/clustering/clustering.h, python/graphscope/nx/algorithms/tests/builtin/test_cluster.py, python/graphscope/nx/tests/test_ctx_builtin.py
=> fix(analytical): make clustering support undirected graph

flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/workdir_manipulator.cc, flex/engines/http_server/workdir_manipulator.h, flex/storages/metadata/graph_meta_store.cc, flex/storages/metadata/graph_meta_store.h
- Return the meta of plugins when retrieving a graph's metadata.
- AdminService can create graph from schema with no `type_id` and `property_id` specified.
- Add `query` and `type` field for stored procedure's meta.
=> refactor(interactive): add plugin into graph meta

.github/workflows/flex.yml, docs/flex/interactive/custom_graph_data.md, docs/flex/interactive/data_model.md, docs/flex/interactive/development/admin_service.md, flex/storages/metadata/graph_meta_store.cc, flex/storages/rt_mutable_graph/README.md, flex/storages/rt_mutable_graph/schema.cc, flex/storages/rt_mutable_graph/schema.h, flex/storages/rt_mutable_graph/types.h, flex/tests/rt_mutable_graph/modern_graph_unified_schema.yaml, flex/utils/property/types.cc, flex/utils/property/types.h
Support parsing the data type from the new unified type definition.
```yaml
GS_DATA_TYPE:  # choose one
primitive_type:
string:  # choose one
long_text: # string with unlimited length
var_char:  # string with variable length, bounded by max_length
max_length: <uint32>
temporal: # choose one
date32:
timestamp:
```
Also compatible with previous schema files.
=> feat(interactive): Adapt to new data type definition

docs/interactive_engine/neo4j/supported_cypher.md, docs/interactive_engine/tinkerpop/supported_gremlin_steps.md, interactive_engine/compiler/src/main/antlr4/ExprGS.g4, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/ExpressionVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4x/visitor/ExtExpressionVisitor.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/antlr4/WhereTest.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4x/GraphBuilderTest.java
1. Support `elementId` operator in cypher, used to obtain the inner id specific to graph storage; 
2. Support obtaining inner id through `elementId` in Gremlin expression syntax sugar;
Fixes
=> refactor(interactive): Support `elementId` Operator to Get Node Identifier in Cypher

.github/workflows/flex.yml, flex/engines/hqps_db/core/operator/group_by.h, flex/engines/hqps_db/structures/collection.h, flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/workdir_manipulator.cc, flex/engines/http_server/workdir_manipulator.h, flex/storages/metadata/default_graph_meta_store.cc, flex/storages/metadata/graph_meta_store.cc, flex/storages/metadata/graph_meta_store.h, flex/storages/rt_mutable_graph/schema.cc, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/Utils.java
- Create a graph with no edge types.
- Return the detail message when error happens. e.g. creating graph with vertex have `DT_DOUBLE` primary keys(currently not supported)
- Support open and running query on an empty graph.
- Other issues.
Fix #3707 
Fix #3693
=> fix(interactive): Fix some issues of AdminService

python/graphscope/gsctl/commands/common.py
Example usage:
```bash
❯ PYTHONPATH=`pwd` python3 graphscope/gsctl/gsctl.py estimate -v 222111111 -e 1610000000 -vf 2 -ef 28 -g gae -p 4
Disclaimer: The `estimate` command serves as a estimator for various kind of GraphScope resources.
- GAE memory usage estimator:
It would do a rough estimation of the total memory usage of the GAE.
The actual memory usage may vary vastly due to the complexity of the graph algorithm and the data distribution.
Here's some assumption when estimating the memory usage:
1. Assuming the graph is a simple graph, e.g. only has 1 label and at most 1 property for each label.
2. Assuming the graph algorithms has a fixed amount of memory consumption, e.g. PageRank, SSSP, CC;
It should not generate a huge amount of intermediate result, like K-Hop, Louvain.
3. Assuming …
```
=> chore: Add estimate memory usage command for gsctl

.github/workflows/hqps-db-ci.yml, flex/bin/load_plan_and_gen.sh, flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/workdir_manipulator.cc, flex/tests/interactive/modern_graph_schema_v0_0.yaml, flex/tests/interactive/modern_graph_schema_v0_1.yaml, flex/tests/interactive/sample_app.cc, flex/utils/property/types.cc, flex/utils/property/types.h, flex/utils/service_utils.cc, flex/utils/service_utils.h
- Move the `from_json` and `to_json` method for `PropertyType` to a separate file, avoid including `nlohman_json` header(which will cause issue in cmake installed scenrio).
- Fix the creation of cpp procedure. Generate a yaml contains necessary metadata. Currently the metadata lacks `params` and `returns` info, we will parse from c++ code/ or let user specify later. 
Future work: https://github.com/alibaba/GraphScope/pull/3835
=> fix(interactive): Fix c++ procedure gen and codegen

flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/service/hqps_service.cc, flex/engines/http_server/service/hqps_service.h, flex/openapi/openapi_interactive.yaml, flex/tests/hqps/engine_config_test.yaml
The start_time is returns in timestamp, and will be refreshed when service got started.
=> feat(interactive): Track the start_time of `hqps_service` and return in `get_service_status`

README-zh.md, README.md, charts/graphscope/README.md, docs/python_tutorials.md, docs/zh/tutorials.rst, tutorials/zh/10_revisit_classification_on_citation_network_on_k8s.ipynb
Change the GraphScope playground's domain name to "https://try.graphscope.io"
=> docs: Update the domain name of GraphScope PlayGround

flex/utils/yaml_utils.cc, flex/utils/yaml_utils.h
Remove a redundant function and shift the inclusion of `nlohmann/json.hpp` header from the .h file to the .cc file. This will resolve a runtime code generation error that occurs after installing flex interactive system-wide.
=> fix(interactive): Remove dummy code

flex/storages/metadata/default_graph_meta_store.cc, flex/storages/metadata/default_graph_meta_store.h
Support identical plugin names for distinct plugins across graphs.
Currently plugin_name is deemed to be unique globally.
Fix #3841
=> fix(interactive): Support identical plugin names for distinct plugins across graphs.

docs/flex/interactive/data_model.md, flex/storages/rt_mutable_graph/schema.cc, flex/utils/id_indexer.h
For three string types: `long_text`, `var_char` and `fixed_char`, we currently support `long_text`, `var_char` and primary key for vertex. `fixed_char` hasn't been supported yet.
=> fix(interactive): Support using string as primary key

flex/CMakeLists.txt, flex/engines/http_server/handler/hqps_http_handler.cc, flex/interactive/docker/interactive-runtime.Dockerfile
- Install `nlohmann/json.hpp` to system as it is needed by procedure compilation.
- Skip building tests when building docker image.
=> fix(interactive): Install `nlohmann/json.hpp` as it is needed by procedure compilation

flex/engines/graph_db/database/graph_db_session.h, flex/engines/http_server/handler/hqps_http_handler.cc, flex/engines/http_server/handler/hqps_http_handler.h, flex/engines/http_server/service/hqps_service.cc, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/ProcedureInterface.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/impl/DefaultSession.java, flex/interactive/sdk/java/src/test/java/com/alibaba/graphscope/interactive/client/DriverTest.java, flex/interactive/sdk/python/interactive_sdk/client/session.py, flex/interactive/sdk/python/test/test_driver.py, flex/openapi/openapi_interactive.yaml, flex/tests/hqps/admin_http_test.cc, flex/tests/hqps/engine_config_test.yaml, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/HttpExecutionClient.java
- Introduce customized header `X-Interactive-Request-Format` with value `[proto, encoder, json]` to distinguish between different format. 
- There will be no byte appending on SDK side. The format byte will be append in `hqps_ic_handler`.
- Support calling procedure without specifying the graph id, by submitting queries to the running graph with url`/v1/graph/current/query` .
- Remove `hqps_exit_handler` since not used.
- Create handlers for each shard.
=> refactor(interactive): Refine Interactive SDK `call_proc` API design

docs/flex/interactive/development/restful_api.md, flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/actor/admin_actor.act.h, flex/engines/http_server/handler/admin_http_handler.cc, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/GraphInterface.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/impl/DefaultSession.java, flex/interactive/sdk/java/src/test/java/com/alibaba/graphscope/interactive/client/DriverTest.java, flex/interactive/sdk/python/interactive_sdk/client/session.py, flex/interactive/sdk/python/test/test_driver.py, flex/openapi/openapi_interactive.yaml, flex/storages/metadata/graph_meta_store.cc, flex/storages/metadata/graph_meta_store.h, flex/tests/hqps/admin_http_test.cc
`curl -X GET http://localhost:7777/v1/graph/{graph_id}/statistics` retrieves the graph's stats: total vertex and edge counts, plus label counts for each vertex and edge.
Currently, this API will only returns the statistics of the graph if it is running. inquire about a non-running graph will yield an error.
=> feat(interactive): Implement the `get_graph_statistics` for AdminService

flex/storages/rt_mutable_graph/schema.cc, python/graphscope/gsctl/gsctl.py, python/graphscope/gsctl/tests/test_interactive.py
=> fix(interactive): Fix parsing empty edge_type list when creation graph

Makefile, coordinator/gscoordinator/flex/core/client_wrapper.py, coordinator/gscoordinator/flex/core/utils.py, coordinator/gscoordinator/flex/models/upload_file_response.py, coordinator/gscoordinator/flex/openapi/openapi.yaml, docs/flex/coordinator.md, docs/utilities/gs.md, flex/openapi/openapi_coordinator.yaml, python/graphscope/flex/rest/models/upload_file_response.py, python/graphscope/gsctl/commands/__init__.py, python/graphscope/gsctl/commands/interactive/glob.py, python/graphscope/gsctl/commands/interactive/graph.py, python/graphscope/gsctl/config.py, python/graphscope/gsctl/impl/__init__.py, python/graphscope/gsctl/impl/graph.py, python/graphscope/gsctl/impl/utils.py, python/graphscope/gsctl/utils.py
- Start the service when switching graph context
- Move `gsctl service <start/stop/status>` from GLOBAL to GRAPH context
- Move `gsctl create/delete datasource/loaderjob` from GRAPH to GLOBAL context
- Display GRAPH_NAME(GRAPH_ID) in `gsctl service status` and `gsctl use GRAPH/GLOBAL` command
- Return metadata when uploading file
- Add `Y/N` interaction when deleting graph/storedproc/job resource
Fixes
=> feat: Start the service when switching graph context on Interactive

charts/gie-standalone/templates/frontend/statefulset.yaml, charts/gie-standalone/values.yaml, docs/interactive_engine/dev_and_test.md, docs/interactive_engine/getting_started.md, docs/storage_engine/groot.md, interactive_engine/compiler/set_properties.sh, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/PegasusConfig.java
=> fix(interactive): Refine Query Timeout Configuration in GIE Doc

interactive_engine/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4x/GraphBuilderTest.java
=> fix(interactive): Fix Errors Caused by Conflict Merge With Main

.gitignore, flex/interactive/sdk/python/.openapi-generator-ignore
- `py.typed` is needed, shouldn't be ignored
- `__init__.py` should be generated.
=> fix(interactive): Fix python sdk packing

flex/engines/http_server/handler/graph_db_http_handler.cc
Aligned with the interactive handler，append the query type after the request.
=> fix(interactive): append query type in graph_db_ic_handler

flex/utils/id_indexer.h
- Avoid redundant traversal when building the lf_indexer
- Return an invalid value to indicate the key doesn't exist, instead of crashing.
=> fix(interactive): Avoid redundant traversal when building lf_indexer

flex/engines/http_server/service/hqps_service.cc
The interactive service generates n cache files named neo4j-xxx in the /tmp/ directory during execution, each with a size of at least **0.5GB**. These files do not get deleted when the process ends. Here, n represents the number of times the interactive server has been started or restarted.
This issue was due to the previously used termination method for the compiler process, which utilized the **terminate()** function. Since terminate() does not facilitate a normal exit, it led to the compiler's inability to clean up the cache files it created.
Transitioning to sending the **SIGINT signal** ensures that the compiler exits gracefully and performs the necessary cache cleanup. And sleep for up to 10 seconds to wait for the compiler process to stop
=> fix(interactive): Fixed bug that wasted disk space

flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.cc, flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.h
- When there are duplicate vertices, only the first will be retained.
- edge with invalid vertex id will be discard.
=> fix(interactive): Allow duplicate vertices and edge with invalid vertex id in source data

docs/flex/interactive/data_model.md, flex/CMakeLists.txt, flex/otel/CMakeLists.txt, flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.cc, flex/storages/rt_mutable_graph/loader/basic_fragment_loader.h, flex/storages/rt_mutable_graph/schema.cc
=> fix(interactive): Only allow using of `var_char` and `long_text` on edge property for string type

analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/fragment/ArrowFragment.java
As titled.
see https://github.com/v6d-io/v6d/blob/ff2aa8f60caec1f20a73b33fd31656f43b9e712f/modules/graph/fragment/arrow_fragment.vineyard-mod#L290
=> fix(analytical): Fix ret type of `getIntData` and `getDoubleData` for arrow fragment java wrapper

python/graphscope/gsctl/commands/interactive/glob.py, python/setup_gsctl.py
=> fix: fix VERSION not found in gsctl

docs/flex/interactive/data_import.md, flex/bin/bulk_loader.cc, flex/engines/http_server/actor/admin_actor.act.cc, flex/interactive/sdk/python/test/test_driver.py, flex/openapi/openapi_interactive.yaml, flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.h, flex/storages/rt_mutable_graph/loader/csv_fragment_loader.cc, flex/storages/rt_mutable_graph/loader/csv_fragment_loader.h, flex/storages/rt_mutable_graph/loader/loader_factory.cc, flex/storages/rt_mutable_graph/loader/loader_factory.h, flex/storages/rt_mutable_graph/loader/odps_fragment_loader.cc, flex/storages/rt_mutable_graph/loader/odps_fragment_loader.h, flex/storages/rt_mutable_graph/loading_config.cc, flex/storages/rt_mutable_graph/loading_config.h
Add options: 
- parallelism: number of threads to use for bulk loading.
- use_mmap_vector: whether to use mmap vector for building columns.
- build_csr_in_mem: whether or not to build csr in memory.
to `LoadingConfig`. 
User could config the new options in `engine_config.yaml` or via SDK. 
Those options could also be overrode with command line args of `bulk_loader`.
Make sure all http api returns a json string.
=> refactor(interactive): Add more options to  `LoadingConfig`

flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/Driver.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/impl/DefaultSession.java, flex/interactive/sdk/java/src/test/java/com/alibaba/graphscope/interactive/client/DriverTest.java, flex/interactive/sdk/python/gs_interactive/client/driver.py, flex/interactive/sdk/python/gs_interactive/client/session.py, flex/interactive/sdk/python/test/test_driver.py, flex/tests/hqps/hqps_sdk_test.sh, k8s/internal/Makefile, python/graphscope/gsctl/commands/dev.py
Interactive service exposes many ports, including `admin_port`, `query_port(stored_proc_port)`, `cypher_port` and `gremlin_port`. In previous SDK implementation, we create a driver by only providing the `admin_endpoint`, hoping for get all other ports via `GET /v1/service/status`, However, this only works if the SDK runs inside the service's container. In cases like k8s deployment, the internal port will be mapped to a large port number which is chosen by the cluster.
In this PR, we let user to declare the endpoints to environment variables, and connect via SDK.
```bash
export INTERACTIVE_ADMIN_ENDPOINT: http://host:port
export INTERACTIVE_STORED_PROC_ENDPOINT: http://host:port
export INTERACTIVE_CYPHER_ENDPOINT: neo4j://host:port or bolt://host:port
export INTERACTIVE_GREMLIN_ENDPOINT: …
```
=> refactor(interactive): Support customizing ports when deploy interactive in local mode and connect via SDK

.github/workflows/interactive.yml, flex/storages/rt_mutable_graph/loader/abstract_arrow_fragment_loader.cc, flex/storages/rt_mutable_graph/mutable_property_fragment.cc, flex/tests/rt_mutable_graph/modern_graph_string_pk.yaml, flex/utils/property/column.cc, flex/utils/pt_indexer.h
Before, we only supported `var_char` as the primary key, but `long_text` makes no difference when used as a primary key in Interactive.
=> fix(interactive): Support `long_text` as primary key

interactive_engine/compiler/src/main/resources/statistics/imdb_statistics.json, interactive_engine/executor/ir/core/resource/imdb_schema.yaml, interactive_engine/executor/store/exp_store/data/imdb_metadata.json, interactive_engine/executor/store/exp_store/src/parser.rs
1. For GOpt, add schema and statistics for IMDB dataset
2. For ExpStore, add dataloading metadata  for IMDB dataset, and support parsing an empty value (for the columns that are optional)
#4014
=> fix(interactive): Add meta data information of IMDB dataset

.github/workflows/flex-interactive.yml, .github/workflows/release.yml, python/setup_flex.py
=> fix: No module named 'graphscope.flex.rest.api' in gsctl

flex/bin/load_plan_and_gen.sh, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/Driver.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/ProcedureInterface.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/QueryInterface.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/Session.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/common/Config.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/common/Result.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/common/Status.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/impl/DefaultSession.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/utils/Decoder.java, flex/interactive/sdk/java/src/main/java/com/alibaba/graphscope/interactive/client/utils/Encoder.java, flex/interactive/sdk/java/src/test/java/com/alibaba/graphscope/interactive/client/DriverTest.java
- Fix some interactive java sdk test problem
- Interactive Java SDK could be initiated without admin endpoint.
- Introduce configuration class.
User can submit query to the query interface without connecting to admin service.
```java
QueryInterface queryInterface = Driver.queryServiceOnly(queryEndpoint);
byte[] bytes = new byte[4 + 1];
Encoder encoder = new Encoder(bytes);
encoder.put_int(1);
encoder.put_byte((byte) 3); // Assume the procedure index is 3
Result<byte[]> resp = queryInterface.callProcedureRaw(graphId, bytes);
```
=> refactor(interactive): Fix some CI problem and code support procedure-query-only mode

.github/workflows/interactive.yml, flex/bin/load_plan_and_gen.sh, flex/codegen/gen_code_from_plan.cc, flex/engines/http_server/codegen_proxy.cc, flex/engines/http_server/codegen_proxy.h, flex/engines/http_server/workdir_manipulator.cc, flex/interactive/sdk/generate_sdk.sh, flex/storages/metadata/local_file_metadata_store.cc, flex/storages/rt_mutable_graph/schema.cc, flex/tests/hqps/admin_http_test.cc
Improve the codegen error propagation from server to client. Including more detailed information instead of just an internal error message.
- Remove some unnecessary log
- Redirect the stderr of codegen process to a string, returns if the codegen process fails.
=> fix(interactive): Improve the codegen error propagation from server to client 

flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/service/hqps_service.cc, flex/interactive/sdk/python/test/test_driver.py
There is no need to restart the compiler process when restarting the interactive query service, as the compiler already relies on HTTP requests.
=> refactor(interactive): No need to restart compiler when restarting interactive

docs/flex/interactive/data_import.md, flex/interactive/examples/modern_graph/bulk_load.yaml, flex/storages/rt_mutable_graph/loader/csv_fragment_loader.cc, flex/storages/rt_mutable_graph/loading_config.cc, flex/storages/rt_mutable_graph/loading_config.h
=> fix(interactive): fix bulkloading data from csv files without header and add null_values option for arrow

interactive_engine/executor/engine/pegasus/pegasus/src/communication/output/tee.rs
Fixes
https://github.com/alibaba/GraphScope/issues/4085
=> fix(interactive): Fix early stop in pegasus when unblock other output

charts/graphscope-store/templates/configmap.yaml, charts/graphscope-store/values.yaml, interactive_engine/groot-server/src/main/java/com/alibaba/graphscope/groot/servers/ir/IrServiceProducer.java
=> fix(interactive): Expose config for Glogue size and pattern decomposition size in Compiler in Charts

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rel/metadata/glogue/GlogueBasicCardinalityEstimationImpl.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rel/metadata/schema/GlogueSchema.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/rel/metadata/GLogueSchemaTest.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/rel/metadata/GlogueTest.java
As titled. When query cardinality of non-exist types or patterns, return 1.0.
Fixes
=> fix(interactive): fix query cardinality of non-exist types or patterns

flex/engines/http_server/actor/admin_actor.act.cc, flex/storages/metadata/default_graph_meta_store.cc, flex/storages/metadata/graph_meta_store.cc, flex/tests/hqps/context_test.cc
Catch exceptions thrown by nlohmann json and add additional debug logging.
=> fix(interactive): Catch exceptions thrown by nlohmann json

README.md, analytical_engine/core/server/command_detail.h, analytical_engine/java/grape-graphx/src/main/java/com/alibaba/graphscope/utils/PythonInterpreter.java, analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/communication/Communicator.java, analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/stdcxx/FFIByteVector.java, flex/interactive/sdk/python/gs_interactive/client/session.py, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/integration/graphAlgo/GraphAlgoTest.java, python/graphscope/gsctl/scripts/format_command.sh, python/graphscope/gsctl/scripts/lib/install_thirdparty_dependencies.sh, python/graphscope/gsctl/scripts/test_command.sh
Increase code robustness by making try-catch snippets of code that may cause resource leaks, and fixing some details.
Code optimization through the use of TONGYI LINGMA.
Fixes
=> fix: Improve the robustness of code

.github/workflows/interactive.yml, .github/workflows/k8s-ci.yml, .github/workflows/networkx-forward-algo-nightly.yml, analytical_engine/core/fragment/dynamic_fragment.h, analytical_engine/core/fragment/dynamic_projected_fragment.h, k8s/internal/Makefile, python/graphscope/gsctl/scripts/install_deps.sh, python/setup_gsctl.py
=> fix: upgrade boost version to v1.75.0 for leaf

k8s/dockerfiles/flex-interactive.Dockerfile
Those dependencies are already installed in graphscope-dev
=> refactor(interactive): Eliminate dummy installation in the Dockerfile.

docs/interactive_engine/neo4j/supported_cypher.md, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/IrMeta.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/procedure/GraphStoredProcedures.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/procedure/StoredProcedureMeta.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/reader/HttpIrMetaReader.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/reader/LocalIrMetaReader.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/IrGraphSchema.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/IrGraphStatistics.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/SchemaSpec.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/SchemaSpecManager.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/rex/RexProcedureCall.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/ffi/FfiPhysicalBuilder.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphBuilder.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphPlanExecutor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/ProcedureCallVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/executor/CypherPlanExecution.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/executor/GraphQueryExecutor.java
To get schema, run `call graph.procedure.meta.schema();`, which returns the schema in [FLEX specification](https://app.swaggerhub.com/apis/GRAPHSCOPE/flex-api/1.0.0#/Graph/importSchemaById) in json string;
To get statistiscs, run `call graph.procedure.meta.statistics();`, which returns the statistics in [json string](https://github.com/alibaba/GraphScope/blob/main/interactive_engine/compiler/src/test/resources/statistics/modern_statistics.json);
Fixes
=> refactor(interactive): Support Fetching Meta By Calling Procedure in Compiler

flex/bin/load_plan_and_gen.sh, flex/engines/http_server/codegen_proxy.cc, flex/interactive/sdk/examples/python/basic_example.py
=> fix(interactive): Fix description passing for procedure creation

docs/_static/coordinator_restful_api.html, docs/analytical_engine/dev_and_test.md, docs/development/dev_guide.md, docs/learning_engine/dev_and_test.md, docs/utilities/gs.md, k8s/dockerfiles/flex-interactive.Dockerfile, python/graphscope/gsctl/commands/common.py, python/graphscope/gsctl/impl/stored_procedure.py, python/graphscope/gsctl/tests/test_interactive.py, python/graphscope/gsctl/utils.py
```
gsctl create storedproc -f procedure.yaml
name: "cpp-procedure-name"
description: "This is a cpp test procedure"
query: "@/home/graphscope/sample_app.cc"
type: "cpp"
```
```cpp
namespace gs {
class ExampleQuery : public CypherReadAppBase<int32_t> {}
}
```
Fixes #4216
=> feat: Support creating c++ stored procedure via gsctl

flex/engines/http_server/actor/admin_actor.act.cc
Correct the `edge_num` in the graph statistics result.
Fix #4225 
TODO: Add a ci
=> fix(interactive): Correct the number of edge count

flex/engines/graph_db/CMakeLists.txt, flex/engines/graph_db/app/builtin/count_vertices.cc, flex/engines/graph_db/app/builtin/count_vertices.h, flex/engines/graph_db/database/graph_db.cc, flex/engines/graph_db/database/graph_db_session.cc, flex/engines/hqps_db/app/interactive_app_base.h, flex/engines/http_server/actor/admin_actor.act.cc, flex/interactive/sdk/python/gs_interactive/tests/conftest.py, flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py, flex/openapi/openapi_coordinator.yaml, flex/openapi/openapi_interactive.yaml, flex/storages/metadata/graph_meta_store.cc, flex/storages/metadata/graph_meta_store.h, flex/storages/rt_mutable_graph/schema.cc, flex/storages/rt_mutable_graph/schema.h, python/setup_gsctl.py
This PR introduces support for built-in procedures in Interactive. Users can access these procedures as soon as the graph is created, with more built-in apps to be added in the future.
For instance, a user can count the vertices of a specific label using:
```cypher
call count_vertices("person");
```
Please note that built-in procedures cannot be deleted or updated, and users cannot create procedures with the same name as a built-in procedure.
=> feat(interactive): Support builtin app in Interactive

flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/graph_db_service.cc, flex/engines/http_server/workdir_manipulator.cc, flex/engines/http_server/workdir_manipulator.h, flex/openapi/openapi_coordinator.yaml, flex/openapi/openapi_interactive.yaml, flex/storages/metadata/graph_meta_store.cc, flex/storages/metadata/graph_meta_store.h, flex/utils/result.h, flex/utils/yaml_utils.cc
- When starting the service from the default graph without specifying `property_id` and `type_id` in `graph.yaml`, we should be able  to generate them as needed. 
- We will also reuse the logic for creating the graph upon receiving a request. Additionally, we need to resolve the problem of using multiple `ASSIGN_AND_RETURN_IF_RESULT_NOT_OK` macros within a single code snippet.
=> fix(interactive): Reuse the graph schema preprocessing to create the default graph schema when the service starts

analytical_engine/core/launcher.h, analytical_engine/core/object/fragment_wrapper.h, charts/graphscope-store/templates/configmap.yaml, charts/graphscope-store/values.yaml, interactive_engine/assembly/src/conf/groot/logback.xml, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/CoordinatorConfig.java, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/config/StoreConfig.java, interactive_engine/executor/assembly/groot/src/store/graph.rs, interactive_engine/executor/store/groot/src/db/graph/meta.rs, interactive_engine/executor/store/groot/src/db/graph/store.rs, interactive_engine/executor/store/groot/src/db/storage/rocksdb.rs, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/coordinator/SchemaManager.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/coordinator/SchemaService.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/KafkaProcessor.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/StoreSchemaService.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/WriterAgent.java, interactive_engine/groot-module/src/main/java/com/alibaba/graphscope/groot/store/jna/JnaGraphStore.java, python/graphscope/gsctl/scripts/install_deps.sh
Fixes memory leak when reopening rocksdb instance.
=> fix(interactive): Fix memory leak when reopening rocksdb instance

docs/interactive_engine/neo4j/supported_cypher.md, interactive_engine/compiler/src/main/antlr4/ExprGS.g4, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/GraphConfig.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/function/BuiltInFunction.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/function/FunctionMeta.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/function/GraphFunctions.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/proto/RexToProtoConverter.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphBuilder.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphStdOperatorTable.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/ExpressionVisitor.java, interactive_engine/compiler/src/main/java/org/apache/calcite/sql/type/GraphOperandMetaDataImpl.java, interactive_engine/compiler/src/main/java/org/apache/calcite/sql/type/GraphOperandTypes.java, interactive_engine/compiler/src/main/resources/conf/graph_functions.yaml, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/antlr4/MatchTest.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/antlr4/WhereTest.java, interactive_engine/executor/ir/proto/expr.proto
=> refactor(interactive): Support User Defined Functions in Compiler

.github/workflows/gaia.yml, interactive_engine/assembly/src/conf/groot/logback.xml, interactive_engine/compiler/pom.xml, interactive_engine/pom.xml, k8s/dockerfiles/graphscope-store.Dockerfile
=> chore: fix log configuration format

flex/bin/interactive_server.cc, flex/engines/http_server/graph_db_service.cc, flex/storages/metadata/default_graph_meta_store.cc
Previously, when Interactive server exits and restart, the server will still opens the graph data of default_graph(with graph_id 1), while the MetaService may returns other graph's id as running graph id.
With this PR merged, when Interactive starts from an exiting workspace(directory), it will load the previous running graph. The status of metadata store will be consistent with actual graph storage.
Fix #4253
=> fix(interactive): Fix the behavior the service restarting from workspace

.github/workflows/build-graphscope-wheels-macos.yml, .github/workflows/gss.yml, python/graphscope/gsctl/scripts/install_deps.sh
=> fix: install-deps fails on macOS(intel) platform

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/PlannerConfig.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/GraphRelOptimizer.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/PlannerGroup.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/PlannerGroupManager.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/rules/JoinDecompositionRule.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphPlanner.java
=> fix(interactive): Fix Concurrent Bugs in Graph Optimizer

.github/workflows/build-graphscope-images-linux.yml, k8s/dockerfiles/learning.Dockerfile
=> fix: fails of building learning image

interactive_engine/compiler/pom.xml, interactive_engine/compiler/src/main/resources/logback.xml
Due to the PR #4255 , the Gremlin logs can not be printed properly. This PR fixes the issue using `Logback`.
Fixes
=> fix(interactive): Fix Logging Errors in Gremlin Server

flex/interactive/sdk/python/.openapi-generator-ignore
Resolve the documentation deployment issue at https://github.com/alibaba/GraphScope/actions/runs/11247023257/job/31269817278. When using `openapi-generator-cli` to generate documentation, do not override the setup.cfg.
=> docs: Fix document generation

flex/interactive/sdk/java/README.md, flex/interactive/sdk/java/pom.xml, interactive_engine/compiler/pom.xml, interactive_engine/pom.xml
The Interactive SDK and compiler both rely on gaia-ir-proto, including the protoc-generated classes. Previously, we used the maven-shade-plugin to shade the protoc files from the Interactive SDK, but this led to other build issues, as noted in PR #4255.
In this PR, we address the problem by adding an additional jar classifier, `no-gaia-ir`, which can be easily utilized by the compiler.
=> refactor(interactive): Resolve the dependency problem between compiler and interactive SDK

flex/engines/graph_db/database/graph_db.cc, flex/engines/graph_db/database/graph_db_session.cc, flex/engines/graph_db/database/graph_db_session.h, flex/storages/rt_mutable_graph/schema.cc
The meta info about builtin procedure should also be put in schema's fields.
=> fix(interactive): Incorporating the builtin procedure's metadata into the schema's plugin map

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/GraphServer.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/GraphRelOptimizer.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/PlannerGroupManager.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ConcurrentProcessRunner.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/planner/cbo/BITest.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/planner/cbo/ConcurrentBITest.java
1. Add `close()` interface in GraphOptimizer to shutdown `CleanScheduler` (used to clean memory occupation by CBO optimizer periodically) when compiler service stops.
2. Add `ConcurrentBITest` to run BI Tests in parallel, to verify the optimizer's functionality in concurrent cases.
Fixes
=> fix(interactive): Add Unit Tests for Graph Optimizer in Concurrent Scenario

flex/storages/rt_mutable_graph/mutable_property_fragment.cc, flex/storages/rt_mutable_graph/schema.h
We currently allocate an additional 1/4 of the required space when opening a graph, resulting in a smaller reserved space for smaller graphs. To address this, we are increasing the minimum capacity for vertex storage to 4096.
Fix #4105
=> feat(interactive): Increase the reserved slots for small graphs

docs/interactive_engine/neo4j/supported_cypher.md, interactive_engine/compiler/Makefile, interactive_engine/compiler/src/main/antlr4/CypherGS.g4, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/GraphIOProcessor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/proto/RexToProtoConverter.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/proto/Utils.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/config/GraphOpt.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/GraphBuilderVisitor.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/antlr4/MatchTest.java, interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/path.rs, interactive_engine/executor/ir/proto/physical.proto, interactive_engine/executor/ir/runtime/src/process/operator/map/path_start.rs, interactive_engine/executor/ir/runtime/src/process/operator/map/project.rs
=> refactor(interactive): Support `shortestpath` in Cypher Queries

charts/graphscope-store/templates/configmap.yaml, charts/graphscope-store/templates/coordinator/statefulset.yaml, charts/graphscope-store/templates/frontend/statefulset.yaml, charts/graphscope-store/templates/onepod/statefulset.yaml, charts/graphscope-store/templates/store/statefulset-backup.yaml, charts/graphscope-store/templates/store/statefulset.yaml, charts/graphscope-store/values.yaml
This pull request introduces PVCs for the coordinator, frontend, and stores components within Insight.
For instance, we can get log PVCs as follows:
Fixes #4307
=> fix(interactive): Add PVC support for Insight logs

.github/workflows/flex-interactive.yml, coordinator/gscoordinator/coordinator.py, coordinator/gscoordinator/flex/controllers/data_source_controller.py, coordinator/gscoordinator/flex/controllers/deployment_controller.py, coordinator/gscoordinator/flex/controllers/graph_controller.py, coordinator/gscoordinator/flex/controllers/job_controller.py, coordinator/gscoordinator/flex/controllers/service_controller.py, coordinator/gscoordinator/flex/controllers/stored_procedure_controller.py, coordinator/gscoordinator/flex/controllers/utils_controller.py, coordinator/gscoordinator/flex/core/__init__.py, coordinator/gscoordinator/flex/core/alert/builtin_rules.py, coordinator/gscoordinator/flex/core/client_wrapper.py, coordinator/gscoordinator/flex/core/insight/groot.py, coordinator/gscoordinator/flex/core/interactive/hqps.py, k8s/dockerfiles/interactive-entrypoint.sh, python/graphscope/config.py, python/graphscope/gsctl/commands/dev.py
Maintain the port mapping info in coordinator, if deployed with docker.
=> fix(interactive): Return the correct port in coordinator's API

flex/engines/graph_db/database/graph_db.cc, flex/engines/graph_db/database/graph_db.h, flex/engines/graph_db/database/graph_db_session.cc, flex/engines/graph_db/database/read_transaction.h, flex/engines/graph_db/runtime/adhoc/var.cc, flex/engines/graph_db/runtime/common/accessors.h, flex/engines/graph_db/runtime/common/columns/vertex_columns.h, flex/interactive/sdk/python/gs_interactive/tests/conftest.py, flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py, flex/storages/rt_mutable_graph/mutable_property_fragment.cc, flex/storages/rt_mutable_graph/mutable_property_fragment.h
- Unify the getter for primary key properties with the common property getters.
- Refactor the code, let `MutableFragment`, `GraphDB`, `GraphDBSession` and `ReadTransaction` all have methods to retrieve getters for vertex_id and vertex properties.
- DO we need to keep `VertexIdVertexAccessor` and `VertexIdPathAccessor`?
=> fix(interactive): Fix the property getter for primary key

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/rules/JoinDecompositionRule.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/planner/volcano/VolcanoPlannerX.java
=> fix(interactive): Fix Bugs of OOM in CBO

flex/interactive/sdk/generate_sdk.sh, flex/interactive/sdk/python/gs_interactive/tests/conftest.py, flex/interactive/sdk/python/gs_interactive/tests/test_driver.py, flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py
Use a fixed `openapi-generator` version to make codegen repeatable.
Related CI failure: https://github.com/alibaba/GraphScope/actions/runs/11948608684/job/33307061458
=> fix(interactive): Fix Interactive CI

charts/graphscope-store/templates/configmap.yaml, coordinator/gscoordinator/utils.py, k8s/dockerfiles/coordinator.Dockerfile, k8s/dockerfiles/graphscope-dev-wheel.Dockerfile
Previously we used a Gremlin query to check whether the Gremlin service is ready, which may reveal unexpected problems. It is better to use netcat to find out whether the endpoint is ready for serving.
=> refactor(interactive): Use netcat to check service readiness

interactive_engine/pom.xml
update interactive-no-gaia-ir to 0.4.3. The 0.4.2 version seems to contains the generated java files for insight.proto
=> fix(interactive): Fix the conflict of error proto for compiler

.github/workflows/gss.yml, .github/workflows/k8s-ci.yml, k8s/dockerfiles/graphscope-store.Dockerfile, k8s/dockerfiles/interactive.Dockerfile, k8s/internal/Makefile, python/graphscope/gsctl/scripts/install_deps.sh
=> fix(interactive): bump up rustup toolchain version to 1.81.0 to avoid compilation failure

docs/zh/frequently_asked_questions.rst
A missing `` ` `` breaks the rendering of the Chinese docs.
=> docs: fix typo

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/ExpressionVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/GraphBuilderVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/LiteralVisitor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/antlr4/visitor/Utils.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/antlr4/MatchTest.java, interactive_engine/compiler/src/test/resources/config/modern/graph.yaml, interactive_engine/compiler/src/test/resources/statistics/modern_statistics.json
allow special characters and reserved words as the label names, use back-ticks to escape, i.e.:
```
Match (n:`@person`) Return n;
Match (n1)-[m:`contains`]->(n2) Return m;
```
Fixes #4347 
Fixes #4317
=> fix(interactive): Fix Bugs of Special Characters as Label Name

flex/engines/graph_db/runtime/adhoc/expr_impl.cc, flex/engines/graph_db/runtime/common/rt_any.cc, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/integration/suite/movie/MovieQueries.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/integration/movie/MovieTest.java
=> fix(interactive): Fix bug of IS_NULL check for edge property

flex/engines/graph_db/runtime/adhoc/operators/group_by.cc, flex/engines/graph_db/runtime/common/operators/scan.cc, flex/engines/graph_db/runtime/common/rt_any.h
Fix bugs in scan and group by. 
Fix #4378
=> fix(interactive): Fix bugs of runtime

flex/engines/graph_db/runtime/adhoc/operators/procedure_call.cc, flex/engines/graph_db/runtime/common/accessors.h, flex/engines/graph_db/runtime/common/columns/edge_columns.cc, flex/engines/graph_db/runtime/common/columns/edge_columns.h, flex/engines/graph_db/runtime/common/columns/i_context_column.h, flex/engines/graph_db/runtime/common/columns/value_columns.h, flex/engines/graph_db/runtime/common/operators/get_v.h, flex/engines/graph_db/runtime/common/rt_any.cc, flex/engines/graph_db/runtime/common/rt_any.h, flex/engines/graph_db/runtime/common/types.h
Use In-memory EdgePropVector to store edge properties for EdgeColumn. Speed up EdgeColumn scanning.
Fix #4392 
Co-Authored-By: liulx20 liulexiao.llx@alibaba-inc.com
=> fix(interactive): Refactor EdgeColumn Implementation

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/runtime/proto/Utils.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/runtime/GraphRelToProtoTest.java, interactive_engine/compiler/src/test/resources/proto/collect_labels.json
=> fix(interactive): Fix Bugs of Type Inference in `Collect(labels(n))`

charts/graphscope-store/templates/portal/statefulset.yaml, charts/graphscope-store/values.yaml, coordinator/gscoordinator/flex/core/config.py, coordinator/gscoordinator/flex/core/insight/graph.py, coordinator/gscoordinator/flex/core/insight/groot.py, coordinator/gscoordinator/flex/core/insight/utils.py
- Add cypher_endpoint for GrootClient.
- Rename `gremlin_interface` to `groot_endpoints`.
=> feat(coordinator): Add cypher endpoint info when `list_service_status` for groot

python/graphscope/gsctl/scripts/install_deps.sh
Download boost source files from archives.boost.io rather than unavailable jfrog.
CI failure: https://github.com/alibaba/GraphScope/actions/runs/12578855110/job/35058156761
Related Issue: https://github.com/boostorg/boost/issues/997
=> fix(interactive): Download boost source files from archives.boost.io

.github/workflows/flex-interactive.yml, flex/CMakeLists.txt, python/graphscope/gsctl/tests/test_interactive.py
Fix flex interactive api test, also refine the workflow.
Fix #4395
=> fix(interactive): Fix flex interactive api test

interactive_engine/executor/engine/pegasus/pegasus/Cargo.toml, interactive_engine/executor/engine/pegasus/pegasus/src/worker.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/timeout_test.rs
https://github.com/alibaba/GraphScope/issues/4380
=> fix(interactive): Fix bugs of check ready 

analytical_engine/apps/pregel/louvain/louvain_app_base.h
When using Louvain algorithm, I found a question with its stop condition, the Louvain algotithm's quality may be 0, 0.85, 0.80, I want to stop the iterations at 0.80 as the quality has started to decrease, but the current stop condition can't do that.
Besides, the change is consistent with [NetworkX's implementation](https://github.com/networkx/networkx/blob/c34400f1ea5b9daa733b971f7f5ef7072fe410a9/networkx/algorithms/community/louvain.py#L216)
Fixes
=> fix(analytical): Fix Louvain algorithm's stop condition

interactive_engine/executor/ir/core/src/plan/logical.rs, interactive_engine/executor/ir/core/src/plan/meta.rs
=> fix(interactive): Fix bug in datatype conversion in ir-core

analytical_engine/java/grape-giraph/src/main/java/com/alibaba/graphscope/parallel/mm/impl/GiraphMpiMessageManager.java, analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/serialization/FFIByteVectorOutputStream.java
=> fix(analytical): Fix the garbage collection of GAE Java

analytical_engine/java/grape-giraph/src/main/java/com/alibaba/graphscope/parallel/mm/impl/GiraphMpiMessageManager.java, analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/serialization/FFIByteVectorOutputStream.java
As titled. 
https://github.com/alibaba/GraphScope/pull/4426#issuecomment-2589226617
=> fix(analytical): Remove duplicated function

flex/CMakeLists.txt, flex/utils/CMakeLists.txt, python/graphscope/gsctl/scripts/install_deps.sh
Link `PROTOBUF_libraries` for libflex_utils and by default use dynamic arrow libraries.
Fix #4416 
Fix #4430
=> fix(interactive): Fix linkage for libflex_utils

.github/workflows/flex-interactive.yml, k8s/dockerfiles/flex-interactive.Dockerfile
In #4419, Interactive is changed to link to dynamic arrow lib but forgot to change the image building, where we need a static library for arrow.
=> fix(interactive): Use static arrow when building interactive image

flex/engines/graph_db/runtime/common/rt_any.cc, flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py, flex/tests/hqps/hqps_robust_test.sh, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/integration/suite/simple/SimpleMatchQueries.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/integration/ldbc/SimpleMatchTest.java
=> fix(interactive): Including primary keys when sinking vertex

interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/impl/DefaultEdgeRelation.java, interactive_engine/common/src/main/java/com/alibaba/graphscope/groot/common/schema/impl/DefaultGraphProperty.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/GraphOptTable.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/IrDataTypeConvertor.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/IrGraphProperty.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/IrGraphSchema.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/schema/SchemaSpecManager.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/SchemaSpecTest.java
=> fix(interactive): Convert Schema from Groot Spec to Flex Spec

docs/flex/interactive/stored_procedures.md, flex/storages/metadata/graph_meta_store.cc
=> docs(interactive): Add documentations for Interactive builtin procedures.

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/config/YamlConfigs.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/glogue/PrimitiveCountEstimator.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphBuilder.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/GraphPlanner.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/QueryExecutionValidator.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/tools/Utils.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/type/GraphTypeInference.java, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/suite/standard/IrGremlinQueryTest.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/sdk/JNICompilePlanTest.java
1. Limit the maximum hops in path expansion to prevent compilation errors and excessive consumption of computational resources during execution.
2. Handle invalid hops, i.e. `Match (a)-[e:4..3]-(b)`, which will throw exceptions containing `exceeds the maximum allowed iterations` at compiling phase.
Fixes
=> fix(interactive): Limit Maximum Hops in Path Expand

flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py
As titled.
It seems that `MATCH(n)-[*1..4]-() RETURN count(n), n;` could be correctly executed on `graph_algo`, maybe this #4463 issue is due to other reasons.
=> ci: Add test cases for Interacitve runtime

coordinator/gscoordinator/coordinator.py, python/graphscope/config.py
Add a config item to control the maximum content length that coordinator's http server could handle. By default it is set to 1GB.
=> feat(coordinator): Add config `coordinator.max_content_length`

flex/engines/graph_db/runtime/common/context.cc, flex/engines/graph_db/runtime/execute/ops/retrieve/group_by.cc, flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py
=> fix(interactive): Fix group by with vertex as group key

.github/workflows/flex-interactive.yml, docs/flex/interactive/configuration.md, flex/tests/hqps/interactive_config_test.yaml, k8s/dockerfiles/interactive-entrypoint.sh, python/graphscope/gsctl/commands/dev.py, python/graphscope/gsctl/tests/test_file_uploading.py
Support specifying configuration for coordinator when deploy Interactive.
=> feat(interactive): Support customizing coordinator configuration for interactive

interactive_engine/pom.xml
[CI](https://github.com/alibaba/GraphScope/actions/runs/13279065828/job/37073806719) throws errors , exclude dependency of kerby from gremlin test to fix it.
Fixes
=> fix(interactive): Fix Dependency Errors

docs/flex/interactive/development/dev_and_test.md, flex/engines/graph_db/database/compact_transaction.cc, flex/engines/graph_db/database/compact_transaction.h, flex/engines/graph_db/database/graph_db_session.cc, flex/engines/graph_db/database/insert_transaction.cc, flex/engines/graph_db/database/insert_transaction.h, flex/engines/graph_db/database/read_transaction.cc, flex/engines/graph_db/database/read_transaction.h, flex/engines/graph_db/database/single_edge_insert_transaction.cc, flex/engines/graph_db/database/single_edge_insert_transaction.h, flex/engines/graph_db/database/single_vertex_insert_transaction.cc, flex/engines/graph_db/database/single_vertex_insert_transaction.h, flex/engines/graph_db/database/update_transaction.cc, flex/engines/graph_db/database/update_transaction.h, flex/engines/graph_db/database/wal.cc, flex/engines/graph_db/database/wal.h, flex/engines/graph_db/runtime/common/graph_interface.h
In Interactive's execution engine, transactions such as `ReadTransaction`, `UpdateTransaction`, and `InsertTransaction` are employed to maintain data consistency and integrity throughout operations. Each transaction can either succeed or fail, and it is important to understand the transactional guarantees provided by Interactive:
1. For every transaction, we first write the Write-Ahead Log (WAL) to persistent storage before applying it to the graph data. This ensures a reliable record of the transaction steps.
2. If a transaction returns `false` during the `commit()` process, the error occurred prior to applying the WAL to the graph data. This type of failure could arise during the construction of the WAL or during its writing phase.
3. It is important to note that errors can still occur …
=> refactor(interactive): Let transction returns commit result

flex/engines/graph_db/runtime/utils/expr_impl.cc, flex/engines/graph_db/runtime/utils/expr_impl.h, interactive_engine/compiler/src/main/java/com/alibaba/graphscope/cypher/integration/suite/graphAlgo/GraphAlgoQueries.java, interactive_engine/compiler/src/test/java/com/alibaba/graphscope/cypher/integration/graphAlgo/GraphAlgoTest.java
=> fix(interactive): Allow implicit type conversion in `WithInExpr`

flex/engines/graph_db/runtime/common/operators/retrieve/path_expand.cc
`MATCH (message: POST | COMMENT)-[:REPLYOF*0..*]->(post:POST)-[:HASCREATOR]->(person:PERSON)`
=> fix(interactive): support unbounded path expand

flex/engines/graph_db/app/builtin/pagerank.cc, flex/engines/graph_db/app/builtin/pagerank.h, flex/engines/graph_db/database/read_transaction.cc, flex/engines/graph_db/database/read_transaction.h, flex/interactive/sdk/python/gs_interactive/tests/test_robustness.py, flex/storages/metadata/graph_meta_store.cc
Preivously, builtin pagerank suppose that the src and dst vertex of the edge label is of the same label. In this PR, we remove this constraint.
=> refactor(interactive): Support running pagerank on edge triplet subgraph

flex/engines/graph_db/runtime/common/operators/retrieve/get_v.h
=> fix(interactive): Avoid using label_t::max when resizing  vector

docs/sphinx_ext.py
As titled.
```bash
git clone https://github.com/alibaba/GraphScope.git -b gh-pages --single-branch
cd docs
find v0.31.0 -type f | wc -l # 6078
find v0.30.0 -type f | wc -l  #5999
find v0.29.0 -type f | wc -l  # 5909
find latest -type f | wc -l # 6204
find ./reference -type f | wc -l # 4903
```
=> docs: Keep docs for latest 1 tags

docs/flex/interactive/configuration.md, flex/engines/http_server/actor/admin_actor.act.cc, flex/engines/http_server/actor/admin_actor.act.h, flex/engines/http_server/handler/admin_http_handler.cc, flex/tests/hqps/interactive_config_test_cbo.yaml, k8s/dockerfiles/interactive-entrypoint.sh
Interactive lacks a probing method to denote whether the service could successfully process queries; we introduce `/v1/service/ready`.
Also, we modify the `interactive-entrypoint.sh` to support initializing a workspace from an empty folder.
=> feat(interactive): Expose a http api for readiness probe

interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/reader/HttpIrMetaReader.java
Previously, compiler get the schema info from the response of `GET /v1/service/status` where the schema info is in the field `graph` of response. However, we should support let compier get schema from the specific graph `GET /v1/graph/{graph_id]/schema`.
=> feat(interactive): Support compiler fetching schema from `/v1/graph/{graph_id}`

interactive_engine/executor/common/dyn_type/tests/object.rs, interactive_engine/executor/engine/pegasus/pegasus/tests/iteration_test.rs, interactive_engine/executor/ir/graph_proxy/src/utils/expr/eval.rs
As titled, this bug occurs because an Object with an empty string is incorrectly treated as NULL, leading `NULL==NULL` to evaluate as false. However, the comparison `""==""` should be true. This PR addresses and fixes the issue.
#4581
=> fix(interactive): Fix a bug in insight runtime when eval empty string

python/graphscope/gsctl/scripts/install_deps.sh
https://github.com/alibaba/GraphScope/actions/runs/14216252611/job/39833569906?pr=4591
=> ci: Configure cmake_minimum_version to 3.5 when installing libgrape-lite

coordinator/gscoordinator/flex/core/alert/alert_manager.py, coordinator/gscoordinator/flex/core/alert/alert_receiver.py, coordinator/gscoordinator/flex/core/alert/builtin_rules.py, coordinator/gscoordinator/flex/core/alert/message_collector.py, coordinator/gscoordinator/flex/core/client_wrapper.py, coordinator/gscoordinator/flex/core/config.py, coordinator/gscoordinator/flex/core/datasource.py, coordinator/gscoordinator/flex/core/deployment.py, coordinator/gscoordinator/flex/core/insight/graph.py, coordinator/gscoordinator/flex/core/insight/groot.py, coordinator/gscoordinator/flex/core/utils.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> chore: migrate to correct logger interface
